ccflags-y += -I$(KERNEL_SRC)/include/dt-bindings/xring/platform-specific/common/pm/include
ccflags-y += -I$(KERNEL_SRC)/include/dt-bindings/xring/platform-specific

# doze plat driver
obj-$(CONFIG_XRING_PM_COMM) := xr_pm_comm.o

xr_pm_comm-objs := pm_comm.o \
