load(":pineapple.bzl", "define_pineapple")
load(":pineapple_oemvm.bzl", "define_pineapple_oemvm")
load(":pineapple_tuivm.bzl", "define_pineapple_tuivm")
load(":pineapple_vms.bzl", "define_pineapple_vms")
load(":sdxkova.bzl", "define_sdxkova")
load(":sdxkova_cpe_wkk.bzl", "define_sdxkova_cpe_wkk")
load(":sun.bzl", "define_sun")
load(":sun_allyes.bzl", "define_sun_allyes")
load(":sun_le.bzl", "define_sun_le")
load(":sun_oemvm.bzl", "define_sun_oemvm")
load(":sun_tuivm.bzl", "define_sun_tuivm")
load(":sun_vms.bzl", "define_sun_vms")
load(":monaco.bzl", "define_monaco")
load(":parrot.bzl", "define_parrot")
load(":parrot_tuivm.bzl", "define_parrot_tuivm")
load(":msm_common.bzl", "define_signing_keys")
load("//build:msm_kernel_extensions.bzl", "define_top_level_rules")
load(":haotian.bzl", "define_haotian")
load(":xuanyuan.bzl", "define_xuanyuan")
load(":dada.bzl", "define_dada")
load(":miro.bzl", "define_miro")
load(":annibale.bzl", "define_annibale")
load(":bixi.bzl", "define_bixi")
load(":onyx.bzl", "define_onyx")
load(":luming.bzl", "define_luming")
load(":piano.bzl", "define_piano")
load(":yupei.bzl", "define_yupei")
load(":xiaomi_sm8750_common.bzl", "export_xiaomi_headers")

def define_msm_platforms():
    define_top_level_rules()
    define_signing_keys()
    define_pineapple()
    define_pineapple_tuivm()
    define_pineapple_oemvm()
    define_pineapple_vms()
    define_sdxkova()
    define_sdxkova_cpe_wkk()
    define_sun()
    define_sun_le()
    define_sun_tuivm()
    define_sun_oemvm()
    define_sun_vms()
    define_sun_allyes()
    define_monaco()
    define_parrot()
    define_haotian()
    define_xuanyuan()
    define_dada()
    define_miro()
    define_annibale()
    define_bixi()
    define_onyx()
    define_luming()
    define_piano()
    define_yupei()
    export_xiaomi_headers()
    define_parrot_tuivm()
