// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (C) 2022-2025, X-Ring technologies Inc., All rights reserved.
 */
#ifndef __AOC_CAMERA_COMMON__
#define __AOC_CAMERA_COMMON__

#if defined (XRISP_AOC_DEBUG)
#define CSIWDMA_HEADER_BASEADDR        (0)
#else

#include "asic/memory_layout.h"
#include "sh_mapping_business_layout.h"

#define CSIWDMA_HEADER_BASEADDR        (XR_ISP_AOC_MEM_BASE)
#define AOC_VIRT_TO_PHYS_OFFSET        (SHUB_DDR_MAPPING_AOC_ADDR - XR_ISP_AOC_MEM_BASE)
#define AOC_VIRT_TO_PHYS(addr)         ((addr) - AOC_VIRT_TO_PHYS_OFFSET)
#define AOC_PHYS_TO_VIRT(addr)         ((addr) + AOC_VIRT_TO_PHYS_OFFSET)
#endif

#define PINGPONG_RAW_BUFFER_WIDTH      (1472)
#define PINGPONG_RAW_BUFFER_HEIGHT     (1080)
#define PINGPONG_Y_BUFFER_WIDTH        (320)
#define PINGPONG_Y_BUFFER_HEIGHT       (240)

#define PINGPONG_RAW_BUFFER_SIZE       (PINGPONG_RAW_BUFFER_WIDTH * PINGPONG_RAW_BUFFER_HEIGHT)
#define PINGPONG_Y_BUFFER_SIZE         (PINGPONG_Y_BUFFER_WIDTH * PINGPONG_Y_BUFFER_HEIGHT)

#define CSIWDMA_HEADER_SIZE            (0x4000)
#define PINGPONG_BUFFER_BASEADDR       (CSIWDMA_HEADER_BASEADDR + CSIWDMA_HEADER_SIZE)
#define PINGPONG_RAW_BUFFER_HOLE       (0x100)
#define PINGPONG_RAW_BUFFER0_ADDR      (PINGPONG_BUFFER_BASEADDR)
#define PINGPONG_RAW_BUFFER0_ADDR_E    (PINGPONG_RAW_BUFFER0_ADDR + PINGPONG_RAW_BUFFER_SIZE)
#define PINGPONG_RAW_BUFFER1_ADDR      (PINGPONG_RAW_BUFFER0_ADDR_E + PINGPONG_RAW_BUFFER_HOLE)
#define PINGPONG_RAW_BUFFER1_ADDR_E    (PINGPONG_RAW_BUFFER1_ADDR + PINGPONG_RAW_BUFFER_SIZE)

#define PINGPONG_Y_BUFFER_HOLE         (0x40)
#define PINGPONG_Y_BUFFER0_ADDR        (PINGPONG_RAW_BUFFER1_ADDR_E + PINGPONG_RAW_BUFFER_HOLE)
#define PINGPONG_Y_BUFFER0_ADDR_E      (PINGPONG_Y_BUFFER0_ADDR + PINGPONG_Y_BUFFER_SIZE)
#define PINGPONG_Y_BUFFER1_ADDR        (PINGPONG_Y_BUFFER0_ADDR_E + PINGPONG_Y_BUFFER_HOLE)
#define PINGPONG_Y_BUFFER1_ADDR_E      (PINGPONG_Y_BUFFER1_ADDR + PINGPONG_Y_BUFFER_SIZE)

#define PINGPONG_BUFFER_NUM            2

#endif
