// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (C) 2022-2025, X-Ring technologies Inc., All rights reserved.
 */

#ifndef DW_APB_WDT_HEADER_H
#define DW_APB_WDT_HEADER_H

#define DW_APB_WDT_ADDRESS_BLOCK_BASEADDRESS 0x0



#define DW_APB_WDT_CR (DW_APB_WDT_ADDRESS_BLOCK_BASEADDRESS + 0x0)
#define DW_APB_WDT_CR_REGISTERSIZE 32
#define DW_APB_WDT_CR_REGISTERRESETVALUE 0x0
#define DW_APB_WDT_CR_REGISTERRESETMASK 0xffffffff





#define DW_APB_WDT_CR_WDT_EN_BITADDRESSOFFSET 0
#define DW_APB_WDT_CR_WDT_EN_REGISTERSIZE 1



#define DW_APB_WDT_CR_RMOD_BITADDRESSOFFSET 1
#define DW_APB_WDT_CR_RMOD_REGISTERSIZE 1



#define DW_APB_WDT_CR_RPL_BITADDRESSOFFSET 2
#define DW_APB_WDT_CR_RPL_REGISTERSIZE 3



#define DW_APB_WDT_CR_NO_NAME_BITADDRESSOFFSET 5
#define DW_APB_WDT_CR_NO_NAME_REGISTERSIZE 1



#define DW_APB_WDT_CR_RSVD_WDT_CR_BITADDRESSOFFSET 6
#define DW_APB_WDT_CR_RSVD_WDT_CR_REGISTERSIZE 26





#define DW_APB_WDT_TORR (DW_APB_WDT_ADDRESS_BLOCK_BASEADDRESS + 0x4)
#define DW_APB_WDT_TORR_REGISTERSIZE 32
#define DW_APB_WDT_TORR_REGISTERRESETVALUE 0x0
#define DW_APB_WDT_TORR_REGISTERRESETMASK 0xffffffff





#define DW_APB_WDT_TORR_TOP_BITADDRESSOFFSET 0
#define DW_APB_WDT_TORR_TOP_REGISTERSIZE 4



#define DW_APB_WDT_TORR_TOP_INIT_BITADDRESSOFFSET 4
#define DW_APB_WDT_TORR_TOP_INIT_REGISTERSIZE 4



#define DW_APB_WDT_TORR_RSVD_WDT_TORR_BITADDRESSOFFSET 8
#define DW_APB_WDT_TORR_RSVD_WDT_TORR_REGISTERSIZE 24





#define DW_APB_WDT_CCVR (DW_APB_WDT_ADDRESS_BLOCK_BASEADDRESS + 0x8)
#define DW_APB_WDT_CCVR_REGISTERSIZE 32
#define DW_APB_WDT_CCVR_REGISTERRESETVALUE 0xff
#define DW_APB_WDT_CCVR_REGISTERRESETMASK 0xffffffff





#define DW_APB_WDT_CCVR_WDT_CCVR_BITADDRESSOFFSET 0
#define DW_APB_WDT_CCVR_WDT_CCVR_REGISTERSIZE 32





#define DW_APB_WDT_CRR (DW_APB_WDT_ADDRESS_BLOCK_BASEADDRESS + 0xc)
#define DW_APB_WDT_CRR_REGISTERSIZE 32
#define DW_APB_WDT_CRR_REGISTERRESETVALUE 0x0
#define DW_APB_WDT_CRR_REGISTERRESETMASK 0xffffffff





#define DW_APB_WDT_CRR_WDT_CRR_BITADDRESSOFFSET 0
#define DW_APB_WDT_CRR_WDT_CRR_REGISTERSIZE 8



#define DW_APB_WDT_CRR_RSVD_WDT_CRR_BITADDRESSOFFSET 8
#define DW_APB_WDT_CRR_RSVD_WDT_CRR_REGISTERSIZE 24





#define DW_APB_WDT_STAT (DW_APB_WDT_ADDRESS_BLOCK_BASEADDRESS + 0x10)
#define DW_APB_WDT_STAT_REGISTERSIZE 32
#define DW_APB_WDT_STAT_REGISTERRESETVALUE 0x0
#define DW_APB_WDT_STAT_REGISTERRESETMASK 0xffffffff





#define DW_APB_WDT_STAT_WDT_STAT_BITADDRESSOFFSET 0
#define DW_APB_WDT_STAT_WDT_STAT_REGISTERSIZE 1



#define DW_APB_WDT_STAT_RSVD_WDT_STAT_BITADDRESSOFFSET 1
#define DW_APB_WDT_STAT_RSVD_WDT_STAT_REGISTERSIZE 31





#define DW_APB_WDT_EOI (DW_APB_WDT_ADDRESS_BLOCK_BASEADDRESS + 0x14)
#define DW_APB_WDT_EOI_REGISTERSIZE 32
#define DW_APB_WDT_EOI_REGISTERRESETVALUE 0x0
#define DW_APB_WDT_EOI_REGISTERRESETMASK 0xffffffff





#define DW_APB_WDT_EOI_WDT_EOI_BITADDRESSOFFSET 0
#define DW_APB_WDT_EOI_WDT_EOI_REGISTERSIZE 1



#define DW_APB_WDT_EOI_RSVD_WDT_EOI_BITADDRESSOFFSET 1
#define DW_APB_WDT_EOI_RSVD_WDT_EOI_REGISTERSIZE 31





#define DW_APB_WDT_PROT_LEVEL (DW_APB_WDT_ADDRESS_BLOCK_BASEADDRESS + 0x1c)
#define DW_APB_WDT_PROT_LEVEL_REGISTERSIZE 32
#define DW_APB_WDT_PROT_LEVEL_REGISTERRESETVALUE 0x2
#define DW_APB_WDT_PROT_LEVEL_REGISTERRESETMASK 0xffffffff





#define DW_APB_WDT_PROT_LEVEL_WDT_PROT_LEVEL_BITADDRESSOFFSET 0
#define DW_APB_WDT_PROT_LEVEL_WDT_PROT_LEVEL_REGISTERSIZE 3



#define DW_APB_WDT_PROT_LEVEL_RSVD_WDT_PROT_LEVEL_BITADDRESSOFFSET 3
#define DW_APB_WDT_PROT_LEVEL_RSVD_WDT_PROT_LEVEL_REGISTERSIZE 29





#define DW_APB_WDT_COMP_PARAM_5 (DW_APB_WDT_ADDRESS_BLOCK_BASEADDRESS + 0xe4)
#define DW_APB_WDT_COMP_PARAM_5_REGISTERSIZE 32
#define DW_APB_WDT_COMP_PARAM_5_REGISTERRESETVALUE 0x7fffff
#define DW_APB_WDT_COMP_PARAM_5_REGISTERRESETMASK 0xffffffff





#define DW_APB_WDT_COMP_PARAM_5_CP_WDT_USER_TOP_MAX_BITADDRESSOFFSET 0
#define DW_APB_WDT_COMP_PARAM_5_CP_WDT_USER_TOP_MAX_REGISTERSIZE 32





#define DW_APB_WDT_COMP_PARAM_4 (DW_APB_WDT_ADDRESS_BLOCK_BASEADDRESS + 0xe8)
#define DW_APB_WDT_COMP_PARAM_4_REGISTERSIZE 32
#define DW_APB_WDT_COMP_PARAM_4_REGISTERRESETVALUE 0x7fffff
#define DW_APB_WDT_COMP_PARAM_4_REGISTERRESETMASK 0xffffffff





#define DW_APB_WDT_COMP_PARAM_4_CP_WDT_USER_TOP_INIT_MAX_BITADDRESSOFFSET 0
#define DW_APB_WDT_COMP_PARAM_4_CP_WDT_USER_TOP_INIT_MAX_REGISTERSIZE 32





#define DW_APB_WDT_COMP_PARAM_3 (DW_APB_WDT_ADDRESS_BLOCK_BASEADDRESS + 0xec)
#define DW_APB_WDT_COMP_PARAM_3_REGISTERSIZE 32
#define DW_APB_WDT_COMP_PARAM_3_REGISTERRESETVALUE 0x0
#define DW_APB_WDT_COMP_PARAM_3_REGISTERRESETMASK 0xffffffff





#define DW_APB_WDT_COMP_PARAM_3_CD_WDT_TOP_RST_BITADDRESSOFFSET 0
#define DW_APB_WDT_COMP_PARAM_3_CD_WDT_TOP_RST_REGISTERSIZE 32





#define DW_APB_WDT_COMP_PARAM_2 (DW_APB_WDT_ADDRESS_BLOCK_BASEADDRESS + 0xf0)
#define DW_APB_WDT_COMP_PARAM_2_REGISTERSIZE 32
#define DW_APB_WDT_COMP_PARAM_2_REGISTERRESETVALUE 0xff
#define DW_APB_WDT_COMP_PARAM_2_REGISTERRESETMASK 0xffffffff





#define DW_APB_WDT_COMP_PARAM_2_CP_WDT_CNT_RST_BITADDRESSOFFSET 0
#define DW_APB_WDT_COMP_PARAM_2_CP_WDT_CNT_RST_REGISTERSIZE 32





#define DW_APB_WDT_COMP_PARAM_1 (DW_APB_WDT_ADDRESS_BLOCK_BASEADDRESS + 0xf4)
#define DW_APB_WDT_COMP_PARAM_1_REGISTERSIZE 32
#define DW_APB_WDT_COMP_PARAM_1_REGISTERRESETVALUE 0x10000284
#define DW_APB_WDT_COMP_PARAM_1_REGISTERRESETMASK 0xffffffff





#define DW_APB_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_BITADDRESSOFFSET 0
#define DW_APB_WDT_COMP_PARAM_1_WDT_ALWAYS_EN_REGISTERSIZE 1



#define DW_APB_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_BITADDRESSOFFSET 1
#define DW_APB_WDT_COMP_PARAM_1_WDT_DFLT_RMOD_REGISTERSIZE 1



#define DW_APB_WDT_COMP_PARAM_1_WDT_DUAL_TOP_BITADDRESSOFFSET 2
#define DW_APB_WDT_COMP_PARAM_1_WDT_DUAL_TOP_REGISTERSIZE 1



#define DW_APB_WDT_COMP_PARAM_1_WDT_HC_RMOD_BITADDRESSOFFSET 3
#define DW_APB_WDT_COMP_PARAM_1_WDT_HC_RMOD_REGISTERSIZE 1



#define DW_APB_WDT_COMP_PARAM_1_WDT_HC_RPL_BITADDRESSOFFSET 4
#define DW_APB_WDT_COMP_PARAM_1_WDT_HC_RPL_REGISTERSIZE 1



#define DW_APB_WDT_COMP_PARAM_1_WDT_HC_TOP_BITADDRESSOFFSET 5
#define DW_APB_WDT_COMP_PARAM_1_WDT_HC_TOP_REGISTERSIZE 1



#define DW_APB_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_BITADDRESSOFFSET 6
#define DW_APB_WDT_COMP_PARAM_1_WDT_USE_FIX_TOP_REGISTERSIZE 1



#define DW_APB_WDT_COMP_PARAM_1_WDT_PAUSE_BITADDRESSOFFSET 7
#define DW_APB_WDT_COMP_PARAM_1_WDT_PAUSE_REGISTERSIZE 1



#define DW_APB_WDT_COMP_PARAM_1_APB_DATA_WIDTH_BITADDRESSOFFSET 8
#define DW_APB_WDT_COMP_PARAM_1_APB_DATA_WIDTH_REGISTERSIZE 2



#define DW_APB_WDT_COMP_PARAM_1_WDT_DFLT_RPL_BITADDRESSOFFSET 10
#define DW_APB_WDT_COMP_PARAM_1_WDT_DFLT_RPL_REGISTERSIZE 3



#define DW_APB_WDT_COMP_PARAM_1_RSVD_15_13_BITADDRESSOFFSET 13
#define DW_APB_WDT_COMP_PARAM_1_RSVD_15_13_REGISTERSIZE 3



#define DW_APB_WDT_COMP_PARAM_1_WDT_DFLT_TOP_BITADDRESSOFFSET 16
#define DW_APB_WDT_COMP_PARAM_1_WDT_DFLT_TOP_REGISTERSIZE 4



#define DW_APB_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_BITADDRESSOFFSET 20
#define DW_APB_WDT_COMP_PARAM_1_WDT_DFLT_TOP_INIT_REGISTERSIZE 4



#define DW_APB_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_BITADDRESSOFFSET 24
#define DW_APB_WDT_COMP_PARAM_1_WDT_CNT_WIDTH_REGISTERSIZE 5



#define DW_APB_WDT_COMP_PARAM_1_RSVD_31_29_BITADDRESSOFFSET 29
#define DW_APB_WDT_COMP_PARAM_1_RSVD_31_29_REGISTERSIZE 3





#define DW_APB_WDT_COMP_VERSION (DW_APB_WDT_ADDRESS_BLOCK_BASEADDRESS + 0xf8)
#define DW_APB_WDT_COMP_VERSION_REGISTERSIZE 32
#define DW_APB_WDT_COMP_VERSION_REGISTERRESETVALUE 0x3131332a
#define DW_APB_WDT_COMP_VERSION_REGISTERRESETMASK 0xffffffff





#define DW_APB_WDT_COMP_VERSION_WDT_COMP_VERSION_BITADDRESSOFFSET 0
#define DW_APB_WDT_COMP_VERSION_WDT_COMP_VERSION_REGISTERSIZE 32





#define DW_APB_WDT_COMP_TYPE (DW_APB_WDT_ADDRESS_BLOCK_BASEADDRESS + 0xfc)
#define DW_APB_WDT_COMP_TYPE_REGISTERSIZE 32
#define DW_APB_WDT_COMP_TYPE_REGISTERRESETVALUE 0x44570120
#define DW_APB_WDT_COMP_TYPE_REGISTERRESETMASK 0xffffffff





#define DW_APB_WDT_COMP_TYPE_WDT_COMP_TYPE_BITADDRESSOFFSET 0
#define DW_APB_WDT_COMP_TYPE_WDT_COMP_TYPE_REGISTERSIZE 32



#endif
