// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (C) 2022-2025, X-Ring technologies Inc., All rights reserved.
 */

#ifndef DW_APB_RTC_HEADER_H
#define DW_APB_RTC_HEADER_H

#define DW_APB_RTC_ADDRESS_BLOCK_BASEADDRESS 0x0



#define DW_APB_RTC_CCVR (DW_APB_RTC_ADDRESS_BLOCK_BASEADDRESS + 0x0)
#define DW_APB_RTC_CCVR_REGISTERSIZE 32
#define DW_APB_RTC_CCVR_REGISTERRESETVALUE 0x0
#define DW_APB_RTC_CCVR_REGISTERRESETMASK 0xffffffff





#define DW_APB_RTC_CCVR_CURRENT_COUNTER_VALUE_BITADDRESSOFFSET 0
#define DW_APB_RTC_CCVR_CURRENT_COUNTER_VALUE_REGISTERSIZE 32





#define DW_APB_RTC_CMR (DW_APB_RTC_ADDRESS_BLOCK_BASEADDRESS + 0x4)
#define DW_APB_RTC_CMR_REGISTERSIZE 32
#define DW_APB_RTC_CMR_REGISTERRESETVALUE 0x0
#define DW_APB_RTC_CMR_REGISTERRESETMASK 0xffffffff





#define DW_APB_RTC_CMR_COUNTER_MATCH_BITADDRESSOFFSET 0
#define DW_APB_RTC_CMR_COUNTER_MATCH_REGISTERSIZE 32





#define DW_APB_RTC_CLR (DW_APB_RTC_ADDRESS_BLOCK_BASEADDRESS + 0x8)
#define DW_APB_RTC_CLR_REGISTERSIZE 32
#define DW_APB_RTC_CLR_REGISTERRESETVALUE 0x0
#define DW_APB_RTC_CLR_REGISTERRESETMASK 0xffffffff





#define DW_APB_RTC_CLR_COUNTER_LOAD_BITADDRESSOFFSET 0
#define DW_APB_RTC_CLR_COUNTER_LOAD_REGISTERSIZE 32





#define DW_APB_RTC_CCR (DW_APB_RTC_ADDRESS_BLOCK_BASEADDRESS + 0xc)
#define DW_APB_RTC_CCR_REGISTERSIZE 32
#define DW_APB_RTC_CCR_REGISTERRESETVALUE 0x40
#define DW_APB_RTC_CCR_REGISTERRESETMASK 0xffffffff





#define DW_APB_RTC_CCR_RTC_IEN_BITADDRESSOFFSET 0
#define DW_APB_RTC_CCR_RTC_IEN_REGISTERSIZE 1



#define DW_APB_RTC_CCR_RTC_MASK_BITADDRESSOFFSET 1
#define DW_APB_RTC_CCR_RTC_MASK_REGISTERSIZE 1



#define DW_APB_RTC_CCR_RTC_EN_BITADDRESSOFFSET 2
#define DW_APB_RTC_CCR_RTC_EN_REGISTERSIZE 1



#define DW_APB_RTC_CCR_RTC_WEN_BITADDRESSOFFSET 3
#define DW_APB_RTC_CCR_RTC_WEN_REGISTERSIZE 1



#define DW_APB_RTC_CCR_RTC_PSCLR_EN_BITADDRESSOFFSET 4
#define DW_APB_RTC_CCR_RTC_PSCLR_EN_REGISTERSIZE 1



#define DW_APB_RTC_CCR_RTC_PROT_LEVEL_BITADDRESSOFFSET 5
#define DW_APB_RTC_CCR_RTC_PROT_LEVEL_REGISTERSIZE 3



#define DW_APB_RTC_CCR_RSVD_CCR_BITADDRESSOFFSET 8
#define DW_APB_RTC_CCR_RSVD_CCR_REGISTERSIZE 24





#define DW_APB_RTC_STAT (DW_APB_RTC_ADDRESS_BLOCK_BASEADDRESS + 0x10)
#define DW_APB_RTC_STAT_REGISTERSIZE 32
#define DW_APB_RTC_STAT_REGISTERRESETVALUE 0x0
#define DW_APB_RTC_STAT_REGISTERRESETMASK 0xffffffff





#define DW_APB_RTC_STAT_RTC_STAT_BITADDRESSOFFSET 0
#define DW_APB_RTC_STAT_RTC_STAT_REGISTERSIZE 1



#define DW_APB_RTC_STAT_RSVD_RTC_STAT_BITADDRESSOFFSET 1
#define DW_APB_RTC_STAT_RSVD_RTC_STAT_REGISTERSIZE 31





#define DW_APB_RTC_RSTAT (DW_APB_RTC_ADDRESS_BLOCK_BASEADDRESS + 0x14)
#define DW_APB_RTC_RSTAT_REGISTERSIZE 32
#define DW_APB_RTC_RSTAT_REGISTERRESETVALUE 0x0
#define DW_APB_RTC_RSTAT_REGISTERRESETMASK 0xffffffff





#define DW_APB_RTC_RSTAT_RTC_RSTAT_BITADDRESSOFFSET 0
#define DW_APB_RTC_RSTAT_RTC_RSTAT_REGISTERSIZE 1



#define DW_APB_RTC_RSTAT_RSVD_RTC_RSTAT_BITADDRESSOFFSET 1
#define DW_APB_RTC_RSTAT_RSVD_RTC_RSTAT_REGISTERSIZE 31





#define DW_APB_RTC_EOI (DW_APB_RTC_ADDRESS_BLOCK_BASEADDRESS + 0x18)
#define DW_APB_RTC_EOI_REGISTERSIZE 32
#define DW_APB_RTC_EOI_REGISTERRESETVALUE 0x0
#define DW_APB_RTC_EOI_REGISTERRESETMASK 0xffffffff





#define DW_APB_RTC_EOI_RTC_EOI_BITADDRESSOFFSET 0
#define DW_APB_RTC_EOI_RTC_EOI_REGISTERSIZE 1



#define DW_APB_RTC_EOI_RSVD_RTC_EOI_BITADDRESSOFFSET 1
#define DW_APB_RTC_EOI_RSVD_RTC_EOI_REGISTERSIZE 31





#define DW_APB_RTC_COMP_VERSION (DW_APB_RTC_ADDRESS_BLOCK_BASEADDRESS + 0x1c)
#define DW_APB_RTC_COMP_VERSION_REGISTERSIZE 32
#define DW_APB_RTC_COMP_VERSION_REGISTERRESETVALUE 0x3230392a
#define DW_APB_RTC_COMP_VERSION_REGISTERRESETMASK 0xffffffff





#define DW_APB_RTC_COMP_VERSION_RTC_COMP_VERSION_BITADDRESSOFFSET 0
#define DW_APB_RTC_COMP_VERSION_RTC_COMP_VERSION_REGISTERSIZE 32





#define DW_APB_RTC_CPSR (DW_APB_RTC_ADDRESS_BLOCK_BASEADDRESS + 0x20)
#define DW_APB_RTC_CPSR_REGISTERSIZE 32
#define DW_APB_RTC_CPSR_REGISTERRESETVALUE 0x400
#define DW_APB_RTC_CPSR_REGISTERRESETMASK 0xffffffff





#define DW_APB_RTC_CPSR_COUNTER_PRESCALER_VALUE_BITADDRESSOFFSET 0
#define DW_APB_RTC_CPSR_COUNTER_PRESCALER_VALUE_REGISTERSIZE 16



#define DW_APB_RTC_CPSR_RSVD_CPSR_BITADDRESSOFFSET 16
#define DW_APB_RTC_CPSR_RSVD_CPSR_REGISTERSIZE 16





#define DW_APB_RTC_CPCVR (DW_APB_RTC_ADDRESS_BLOCK_BASEADDRESS + 0x24)
#define DW_APB_RTC_CPCVR_REGISTERSIZE 32
#define DW_APB_RTC_CPCVR_REGISTERRESETVALUE 0x0
#define DW_APB_RTC_CPCVR_REGISTERRESETMASK 0xffffffff





#define DW_APB_RTC_CPCVR_CURRENT_PRESCALER_COUNTER_VALUE_BITADDRESSOFFSET 0
#define DW_APB_RTC_CPCVR_CURRENT_PRESCALER_COUNTER_VALUE_REGISTERSIZE 16



#define DW_APB_RTC_CPCVR_RSVD_CPCVR_BITADDRESSOFFSET 16
#define DW_APB_RTC_CPCVR_RSVD_CPCVR_REGISTERSIZE 16



#endif
