// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (C) 2022-2025, X-Ring technologies Inc., All rights reserved.
 */

#ifndef DW_APB_GPIO_HEADER_H
#define DW_APB_GPIO_HEADER_H

#define DW_APB_GPIO_ADDR_BLOCK_BASEADDRESS 0X0









#define GPIO_SWPORTA_DR0 (DW_APB_GPIO_ADDR_BLOCK_BASEADDRESS + 0X8)
#define GPIO_SWPORTA_DR0_REGISTERSIZE 32
#define GPIO_SWPORTA_DR0_REGISTERRESETVALUE 0X0
#define GPIO_SWPORTA_DR0_REGISTERRESETMASK 0XFFFFFFFF

#define GPIO_SWPORTA_DR0_GPIO_SWPORTA_DR0_BITADDRESSOFFSET 0
#define GPIO_SWPORTA_DR0_GPIO_SWPORTA_DR0_REGISTERSIZE 32

#define GPIO_SWPORTA_DR1 (DW_APB_GPIO_ADDR_BLOCK_BASEADDRESS + 0XC)
#define GPIO_SWPORTA_DR1_REGISTERSIZE 32
#define GPIO_SWPORTA_DR1_REGISTERRESETVALUE 0X0
#define GPIO_SWPORTA_DR1_REGISTERRESETMASK 0XFFFFFFFF

#define GPIO_SWPORTA_DR1_GPIO_SWPORTA_DR1_BITADDRESSOFFSET 0
#define GPIO_SWPORTA_DR1_GPIO_SWPORTA_DR1_REGISTERSIZE 32




#define GPIO_SWPORTA_DDR (DW_APB_GPIO_ADDR_BLOCK_BASEADDRESS + 0X4)
#define GPIO_SWPORTA_DDR_REGISTERSIZE 32
#define GPIO_SWPORTA_DDR_REGISTERRESETVALUE 0X0
#define GPIO_SWPORTA_DDR_REGISTERRESETMASK 0XFFFFFFFF





#define GPIO_SWPORTA_DDR_GPIO_SWPORTA_DDR_BITADDRESSOFFSET 0
#define GPIO_SWPORTA_DDR_GPIO_SWPORTA_DDR_REGISTERSIZE 32





#define GPIO_INTEN (DW_APB_GPIO_ADDR_BLOCK_BASEADDRESS + 0X30)
#define GPIO_INTEN_REGISTERSIZE 32
#define GPIO_INTEN_REGISTERRESETVALUE 0X0
#define GPIO_INTEN_REGISTERRESETMASK 0XFFFFFFFF





#define GPIO_INTEN_GPIO_INTEN_BITADDRESSOFFSET 0
#define GPIO_INTEN_GPIO_INTEN_REGISTERSIZE 32





#define GPIO_INTMASK (DW_APB_GPIO_ADDR_BLOCK_BASEADDRESS + 0X34)
#define GPIO_INTMASK_REGISTERSIZE 32
#define GPIO_INTMASK_REGISTERRESETVALUE 0X0
#define GPIO_INTMASK_REGISTERRESETMASK 0XFFFFFFFF





#define GPIO_INTMASK_GPIO_INTMASK_BITADDRESSOFFSET 0
#define GPIO_INTMASK_GPIO_INTMASK_REGISTERSIZE 32





#define GPIO_INTTYPE_LEVEL (DW_APB_GPIO_ADDR_BLOCK_BASEADDRESS + 0X38)
#define GPIO_INTTYPE_LEVEL_REGISTERSIZE 32
#define GPIO_INTTYPE_LEVEL_REGISTERRESETVALUE 0X0
#define GPIO_INTTYPE_LEVEL_REGISTERRESETMASK 0XFFFFFFFF





#define GPIO_INTTYPE_LEVEL_GPIO_INTTYPE_LEVEL_BITADDRESSOFFSET 0
#define GPIO_INTTYPE_LEVEL_GPIO_INTTYPE_LEVEL_REGISTERSIZE 32





#define GPIO_INT_POLARITY (DW_APB_GPIO_ADDR_BLOCK_BASEADDRESS + 0X3C)
#define GPIO_INT_POLARITY_REGISTERSIZE 32
#define GPIO_INT_POLARITY_REGISTERRESETVALUE 0X0
#define GPIO_INT_POLARITY_REGISTERRESETMASK 0XFFFFFFFF





#define GPIO_INT_POLARITY_GPIO_INT_POLARITY_BITADDRESSOFFSET 0
#define GPIO_INT_POLARITY_GPIO_INT_POLARITY_REGISTERSIZE 32





#define GPIO_INTSTATUS (DW_APB_GPIO_ADDR_BLOCK_BASEADDRESS + 0X40)
#define GPIO_INTSTATUS_REGISTERSIZE 32
#define GPIO_INTSTATUS_REGISTERRESETVALUE 0X0
#define GPIO_INTSTATUS_REGISTERRESETMASK 0XFFFFFFFF





#define GPIO_INTSTATUS_GPIO_INTSTATUS_BITADDRESSOFFSET 0
#define GPIO_INTSTATUS_GPIO_INTSTATUS_REGISTERSIZE 32





#define GPIO_RAW_INTSTATUS (DW_APB_GPIO_ADDR_BLOCK_BASEADDRESS + 0X44)
#define GPIO_RAW_INTSTATUS_REGISTERSIZE 32
#define GPIO_RAW_INTSTATUS_REGISTERRESETVALUE 0X0
#define GPIO_RAW_INTSTATUS_REGISTERRESETMASK 0XFFFFFFFF





#define GPIO_RAW_INTSTATUS_GPIO_RAW_INTSTATUS_BITADDRESSOFFSET 0
#define GPIO_RAW_INTSTATUS_GPIO_RAW_INTSTATUS_REGISTERSIZE 32





#define GPIO_DEBOUNCE (DW_APB_GPIO_ADDR_BLOCK_BASEADDRESS + 0X48)
#define GPIO_DEBOUNCE_REGISTERSIZE 32
#define GPIO_DEBOUNCE_REGISTERRESETVALUE 0X0
#define GPIO_DEBOUNCE_REGISTERRESETMASK 0XFFFFFFFF





#define GPIO_DEBOUNCE_GPIO_DEBOUNCE_BITADDRESSOFFSET 0
#define GPIO_DEBOUNCE_GPIO_DEBOUNCE_REGISTERSIZE 32





#define GPIO_PORTA_EOI (DW_APB_GPIO_ADDR_BLOCK_BASEADDRESS + 0X4C)
#define GPIO_PORTA_EOI_REGISTERSIZE 32
#define GPIO_PORTA_EOI_REGISTERRESETVALUE 0X0
#define GPIO_PORTA_EOI_REGISTERRESETMASK 0XFFFFFFFF





#define GPIO_PORTA_EOI_GPIO_PORTA_EOI_BITADDRESSOFFSET 0
#define GPIO_PORTA_EOI_GPIO_PORTA_EOI_REGISTERSIZE 32





#define GPIO_EXT_PORTA (DW_APB_GPIO_ADDR_BLOCK_BASEADDRESS + 0X50)
#define GPIO_EXT_PORTA_REGISTERSIZE 32
#define GPIO_EXT_PORTA_REGISTERRESETVALUE 0X0
#define GPIO_EXT_PORTA_REGISTERRESETMASK 0XFFFFFFFF





#define GPIO_EXT_PORTA_GPIO_EXT_PORTA_BITADDRESSOFFSET 0
#define GPIO_EXT_PORTA_GPIO_EXT_PORTA_REGISTERSIZE 32





#define GPIO_LS_SYNC (DW_APB_GPIO_ADDR_BLOCK_BASEADDRESS + 0X60)
#define GPIO_LS_SYNC_REGISTERSIZE 32
#define GPIO_LS_SYNC_REGISTERRESETVALUE 0X0
#define GPIO_LS_SYNC_REGISTERRESETMASK 0XFFFFFFFF





#define GPIO_LS_SYNC_GPIO_LS_SYNC_BITADDRESSOFFSET 0
#define GPIO_LS_SYNC_GPIO_LS_SYNC_REGISTERSIZE 1



#define GPIO_LS_SYNC_RSVD_GPIO_LS_SYNC_BITADDRESSOFFSET 1
#define GPIO_LS_SYNC_RSVD_GPIO_LS_SYNC_REGISTERSIZE 31





#define GPIO_ID_CODE (DW_APB_GPIO_ADDR_BLOCK_BASEADDRESS + 0X64)
#define GPIO_ID_CODE_REGISTERSIZE 32
#define GPIO_ID_CODE_REGISTERRESETVALUE 0X0
#define GPIO_ID_CODE_REGISTERRESETMASK 0XFFFFFFFF





#define GPIO_ID_CODE_GPIO_ID_CODE_BITADDRESSOFFSET 0
#define GPIO_ID_CODE_GPIO_ID_CODE_REGISTERSIZE 32





#define GPIO_INT_BOTHEDGE (DW_APB_GPIO_ADDR_BLOCK_BASEADDRESS + 0X68)
#define GPIO_INT_BOTHEDGE_REGISTERSIZE 32
#define GPIO_INT_BOTHEDGE_REGISTERRESETVALUE 0X0
#define GPIO_INT_BOTHEDGE_REGISTERRESETMASK 0XFFFFFFFF





#define GPIO_INT_BOTHEDGE_GPIO_INT_BOTHEDGE_BITADDRESSOFFSET 0
#define GPIO_INT_BOTHEDGE_GPIO_INT_BOTHEDGE_REGISTERSIZE 32





#define GPIO_VER_ID_CODE (DW_APB_GPIO_ADDR_BLOCK_BASEADDRESS + 0X6C)
#define GPIO_VER_ID_CODE_REGISTERSIZE 32
#define GPIO_VER_ID_CODE_REGISTERRESETVALUE 0X3231342A
#define GPIO_VER_ID_CODE_REGISTERRESETMASK 0XFFFFFFFF





#define GPIO_VER_ID_CODE_GPIO_VER_ID_CODE_BITADDRESSOFFSET 0
#define GPIO_VER_ID_CODE_GPIO_VER_ID_CODE_REGISTERSIZE 32





#define GPIO_CONFIG_REG2 (DW_APB_GPIO_ADDR_BLOCK_BASEADDRESS + 0X70)
#define GPIO_CONFIG_REG2_REGISTERSIZE 32
#define GPIO_CONFIG_REG2_REGISTERRESETVALUE 0X39CFF
#define GPIO_CONFIG_REG2_REGISTERRESETMASK 0XFFFFFFFF





#define GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_A_BITADDRESSOFFSET 0
#define GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_A_REGISTERSIZE 5



#define GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_B_BITADDRESSOFFSET 5
#define GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_B_REGISTERSIZE 5



#define GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_C_BITADDRESSOFFSET 10
#define GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_C_REGISTERSIZE 5



#define GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_D_BITADDRESSOFFSET 15
#define GPIO_CONFIG_REG2_ENCODED_ID_PWIDTH_D_REGISTERSIZE 5



#define GPIO_CONFIG_REG2_RSVD_GPIO_CONFIG_REG2_BITADDRESSOFFSET 20
#define GPIO_CONFIG_REG2_RSVD_GPIO_CONFIG_REG2_REGISTERSIZE 12





#define GPIO_CONFIG_REG1 (DW_APB_GPIO_ADDR_BLOCK_BASEADDRESS + 0X74)
#define GPIO_CONFIG_REG1_REGISTERSIZE 32
#define GPIO_CONFIG_REG1_REGISTERRESETVALUE 0X3FF0F2
#define GPIO_CONFIG_REG1_REGISTERRESETMASK 0XFFFFFFFF





#define GPIO_CONFIG_REG1_APB_DATA_WIDTH_BITADDRESSOFFSET 0
#define GPIO_CONFIG_REG1_APB_DATA_WIDTH_REGISTERSIZE 2



#define GPIO_CONFIG_REG1_NUM_PORTS_BITADDRESSOFFSET 2
#define GPIO_CONFIG_REG1_NUM_PORTS_REGISTERSIZE 2



#define GPIO_CONFIG_REG1_PORTA_SINGLE_CTL_BITADDRESSOFFSET 4
#define GPIO_CONFIG_REG1_PORTA_SINGLE_CTL_REGISTERSIZE 1



#define GPIO_CONFIG_REG1_PORTB_SINGLE_CTL_BITADDRESSOFFSET 5
#define GPIO_CONFIG_REG1_PORTB_SINGLE_CTL_REGISTERSIZE 1



#define GPIO_CONFIG_REG1_PORTC_SINGLE_CTL_BITADDRESSOFFSET 6
#define GPIO_CONFIG_REG1_PORTC_SINGLE_CTL_REGISTERSIZE 1



#define GPIO_CONFIG_REG1_PORTD_SINGLE_CTL_BITADDRESSOFFSET 7
#define GPIO_CONFIG_REG1_PORTD_SINGLE_CTL_REGISTERSIZE 1



#define GPIO_CONFIG_REG1_HW_PORTA_BITADDRESSOFFSET 8
#define GPIO_CONFIG_REG1_HW_PORTA_REGISTERSIZE 1



#define GPIO_CONFIG_REG1_HW_PORTB_BITADDRESSOFFSET 9
#define GPIO_CONFIG_REG1_HW_PORTB_REGISTERSIZE 1



#define GPIO_CONFIG_REG1_HW_PORTC_BITADDRESSOFFSET 10
#define GPIO_CONFIG_REG1_HW_PORTC_REGISTERSIZE 1



#define GPIO_CONFIG_REG1_HW_PORTD_BITADDRESSOFFSET 11
#define GPIO_CONFIG_REG1_HW_PORTD_REGISTERSIZE 1



#define GPIO_CONFIG_REG1_PORTA_INTR_BITADDRESSOFFSET 12
#define GPIO_CONFIG_REG1_PORTA_INTR_REGISTERSIZE 1



#define GPIO_CONFIG_REG1_DEBOUNCE_BITADDRESSOFFSET 13
#define GPIO_CONFIG_REG1_DEBOUNCE_REGISTERSIZE 1



#define GPIO_CONFIG_REG1_ADD_ENCODED_PARAMS_BITADDRESSOFFSET 14
#define GPIO_CONFIG_REG1_ADD_ENCODED_PARAMS_REGISTERSIZE 1



#define GPIO_CONFIG_REG1_GPIO_ID_BITADDRESSOFFSET 15
#define GPIO_CONFIG_REG1_GPIO_ID_REGISTERSIZE 1



#define GPIO_CONFIG_REG1_ENCODED_ID_WIDTH_BITADDRESSOFFSET 16
#define GPIO_CONFIG_REG1_ENCODED_ID_WIDTH_REGISTERSIZE 5



#define GPIO_CONFIG_REG1_INTERRUPT_BOTH_EDGE_TYPE_BITADDRESSOFFSET 21
#define GPIO_CONFIG_REG1_INTERRUPT_BOTH_EDGE_TYPE_REGISTERSIZE 1



#define GPIO_CONFIG_REG1_RSVD_GPIO_CONFIG_REG1_BITADDRESSOFFSET 22
#define GPIO_CONFIG_REG1_RSVD_GPIO_CONFIG_REG1_REGISTERSIZE 10



#endif
