// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (C) 2022-2025, X-Ring technologies Inc., All rights reserved.
 */

#ifndef HSS2_TOP_REGIF_H
#define HSS2_TOP_REGIF_H

#define HSS2_TOP_NS_FIREWALL_CLEAR              0x0000
#define HSS2_TOP_NS_FIREWALL_CLEAR_HSS2_NS_FW_CLEAR_SHIFT                     0
#define HSS2_TOP_NS_FIREWALL_DCDR_FAIL0         0x0004
#define HSS2_TOP_NS_FIREWALL_DCDR_FAIL0_HSS2_NSFW_NERROR_SHIFT                0
#define HSS2_TOP_NS_FIREWALL_DCDR_FAIL0_HSS2_NSFW_NERROR_MASK                 0x00000001
#define HSS2_TOP_NS_FIREWALL_DCDR_FAIL0_HSS2_NSFW_FAIL_NMID_SHIFT             1
#define HSS2_TOP_NS_FIREWALL_DCDR_FAIL0_HSS2_NSFW_FAIL_NMID_MASK              0x000001fe
#define HSS2_TOP_NS_FIREWALL_DCDR_FAIL1         0x0008
#define HSS2_TOP_HSS2_TESTPIN_SEL               0x000c
#define HSS2_TOP_HSS2_TESTPIN_SEL_TESTPIN_SEL_SHIFT                           0
#define HSS2_TOP_HSS2_TESTPIN_SEL_TESTPIN_SEL_MASK                            0x0000000f
#define HSS2_TOP_HSS2_DOZE_MASK                 0x0010
#define HSS2_TOP_HSS2_DOZE_MASK_PCIE0_L1SS_STATE_MASK_SHIFT                   0
#define HSS2_TOP_HSS2_DOZE_MASK_PCIE0_L1SS_STATE_MASK_MASK                    0x00000001
#define HSS2_TOP_HSS2_DOZE_MASK_PCIE1_L1SS_STATE_MASK_SHIFT                   1
#define HSS2_TOP_HSS2_DOZE_MASK_PCIE1_L1SS_STATE_MASK_MASK                    0x00000002
#define HSS2_TOP_HSS2_DOZE_MASK_EMMC_CCLK_BASE_EN_N_MASK_SHIFT                2
#define HSS2_TOP_HSS2_DOZE_MASK_EMMC_CCLK_BASE_EN_N_MASK_MASK                 0x00000004
#define HSS2_TOP_HSS2_DOZE_MASK_EMMC_INTCLK_EN_N_MASK_SHIFT                   3
#define HSS2_TOP_HSS2_DOZE_MASK_EMMC_INTCLK_EN_N_MASK_MASK                    0x00000008
#define HSS2_TOP_HSS2_DOZE_STATUS               0x0014
#define HSS2_TOP_HSS2_DOZE_STATUS_PCIE0_L1SS_STATUS_SHIFT                     0
#define HSS2_TOP_HSS2_DOZE_STATUS_PCIE0_L1SS_STATUS_MASK                      0x00000001
#define HSS2_TOP_HSS2_DOZE_STATUS_PCIE1_L1SS_STATUS_SHIFT                     1
#define HSS2_TOP_HSS2_DOZE_STATUS_PCIE1_L1SS_STATUS_MASK                      0x00000002
#define HSS2_TOP_HSS2_DOZE_STATUS_EMMC_CCLK_BASE_EN_N_STATUS_SHIFT            2
#define HSS2_TOP_HSS2_DOZE_STATUS_EMMC_CCLK_BASE_EN_N_STATUS_MASK             0x00000004
#define HSS2_TOP_HSS2_DOZE_STATUS_EMMC_INTCLK_EN_N_STATUS_SHIFT               3
#define HSS2_TOP_HSS2_DOZE_STATUS_EMMC_INTCLK_EN_N_STATUS_MASK                0x00000008
#define HSS2_TOP_HSS2_BUS_CTRL                  0x0018
#define HSS2_TOP_HSS2_BUS_CTRL_HSS2_BUS_TIMEOUT_EN_SHIFT                      0
#define HSS2_TOP_HSS2_BUS_CTRL_HSS2_BUS_TIMEOUT_EN_MASK                       0x00000001
#define HSS2_TOP_EMMC_AXI3_AB_STATUS            0x0028
#define HSS2_TOP_EMMC_AXI3_AB_STATUS_EMMC_AXI3_AB_BUSY_STATUS_SHIFT           0
#define HSS2_TOP_EMMC_AXI3_AB_STATUS_EMMC_AXI3_AB_BUSY_STATUS_MASK            0x00000001
#define HSS2_TOP_EMMC_AHB_AB_STATUS0            0x002c
#define HSS2_TOP_EMMC_AHB_AB_STATUS1            0x0030
#define HSS2_TOP_EMMC_AHB_AB_STATUS1_EMMC_AHB_AB_MHBUSREQ_SHIFT               0
#define HSS2_TOP_EMMC_AHB_AB_STATUS1_EMMC_AHB_AB_MHBUSREQ_MASK                0x00000001
#define HSS2_TOP_EMMC_AHB_AB_STATUS1_EMMC_AHB_AB_SHSPLIT_SHIFT                1
#define HSS2_TOP_EMMC_AHB_AB_STATUS1_EMMC_AHB_AB_SHSPLIT_MASK                 0x0001fffe
#define HSS2_TOP_HSS2_RAM_CTRL_BUS_0            0x0034
#define HSS2_TOP_HSS2_RAM_CTRL_BUS_1            0x0038
#define HSS2_TOP_HSS2_RAM_CTRL_BUS_2            0x003c
#define HSS2_TOP_TOP_HSS2_128_NDB_CFG0          0x0040
#define HSS2_TOP_TOP_HSS2_128_NDB_CFG0_TOP_HSS2_128_NDB_MST_AUTOGATE_BYP_SHIFT 0
#define HSS2_TOP_TOP_HSS2_128_NDB_CFG0_TOP_HSS2_128_NDB_MST_AUTOGATE_BYP_MASK  0x00000001
#define HSS2_TOP_TOP_HSS2_128_NDB_CFG0_TOP_HSS2_128_NDB_OST_ZERO_FORCE_SHIFT  1
#define HSS2_TOP_TOP_HSS2_128_NDB_CFG0_TOP_HSS2_128_NDB_OST_ZERO_FORCE_MASK   0x00000002
#define HSS2_TOP_TOP_HSS2_128_NDB_CFG0_TOP_HSS2_128_NDB_SLV_AUTOGATE_BYP_SHIFT 2
#define HSS2_TOP_TOP_HSS2_128_NDB_CFG0_TOP_HSS2_128_NDB_SLV_AUTOGATE_BYP_MASK  0x00000004
#define HSS2_TOP_TOP_HSS2_128_NDB_CFG1          0x0044
#define HSS2_TOP_TOP_HSS2_128_NDB_CFG1_TOP_HSS2_128_NDB_MST_BUSY_SHIFT        0
#define HSS2_TOP_TOP_HSS2_128_NDB_CFG1_TOP_HSS2_128_NDB_MST_BUSY_MASK         0x00000001
#define HSS2_TOP_TOP_HSS2_128_NDB_CFG1_TOP_HSS2_128_NDB_SLV_BUSY_SHIFT        1
#define HSS2_TOP_TOP_HSS2_128_NDB_CFG1_TOP_HSS2_128_NDB_SLV_BUSY_MASK         0x00000002
#define HSS2_TOP_128_NDB_CFG0                   0x0048
#define HSS2_TOP_128_NDB_CFG0_128_NDB_MST_AUTOGATE_BYP_SHIFT                  0
#define HSS2_TOP_128_NDB_CFG0_128_NDB_MST_AUTOGATE_BYP_MASK                   0x00000001
#define HSS2_TOP_128_NDB_CFG0_128_NDB_OST_ZERO_FORCE_SHIFT                    1
#define HSS2_TOP_128_NDB_CFG0_128_NDB_OST_ZERO_FORCE_MASK                     0x00000002
#define HSS2_TOP_128_NDB_CFG0_128_NDB_SLV_AUTOGATE_BYP_SHIFT                  2
#define HSS2_TOP_128_NDB_CFG0_128_NDB_SLV_AUTOGATE_BYP_MASK                   0x00000004
#define HSS2_TOP_128_NDB_CFG1                   0x004c
#define HSS2_TOP_128_NDB_CFG1_128_NDB_MST_BUSY_SHIFT                          0
#define HSS2_TOP_128_NDB_CFG1_128_NDB_MST_BUSY_MASK                           0x00000001
#define HSS2_TOP_128_NDB_CFG1_128_NDB_SLV_BUSY_SHIFT                          1
#define HSS2_TOP_128_NDB_CFG1_128_NDB_SLV_BUSY_MASK                           0x00000002
#define HSS2_TOP_32_NDB_CFG0                    0x0050
#define HSS2_TOP_32_NDB_CFG0_32_NDB_MST_AUTOGATE_BYP_SHIFT                    0
#define HSS2_TOP_32_NDB_CFG0_32_NDB_MST_AUTOGATE_BYP_MASK                     0x00000001
#define HSS2_TOP_32_NDB_CFG0_32_NDB_OST_ZERO_FORCE_SHIFT                      1
#define HSS2_TOP_32_NDB_CFG0_32_NDB_OST_ZERO_FORCE_MASK                       0x00000002
#define HSS2_TOP_32_NDB_CFG0_32_NDB_SLV_AUTOGATE_BYP_SHIFT                    2
#define HSS2_TOP_32_NDB_CFG0_32_NDB_SLV_AUTOGATE_BYP_MASK                     0x00000004
#define HSS2_TOP_32_NDB_CFG1                    0x0054
#define HSS2_TOP_32_NDB_CFG1_32_NDB_MST_BUSY_SHIFT                            0
#define HSS2_TOP_32_NDB_CFG1_32_NDB_MST_BUSY_MASK                             0x00000001
#define HSS2_TOP_32_NDB_CFG1_32_NDB_SLV_BUSY_SHIFT                            1
#define HSS2_TOP_32_NDB_CFG1_32_NDB_SLV_BUSY_MASK                             0x00000002
#define HSS2_TOP_SMMU_TBU0_NS_ID                0x0058
#define HSS2_TOP_SMMU_TBU0_NS_ID_SC_PCIE0_NS_SID0_SHIFT                       0
#define HSS2_TOP_SMMU_TBU0_NS_ID_SC_PCIE0_NS_SID0_MASK                        0x000000ff
#define HSS2_TOP_SMMU_TBU0_NS_ID_SC_PCIE0_NS_SSID0_SHIFT                      8
#define HSS2_TOP_SMMU_TBU0_NS_ID_SC_PCIE0_NS_SSID0_MASK                       0x0000ff00
#define HSS2_TOP_SMMU_TBU0_NS_ID_SC_PCIE0_NS_SSIDV0_SHIFT                     16
#define HSS2_TOP_SMMU_TBU0_NS_ID_SC_PCIE0_NS_SSIDV0_MASK                      0x00010000
#define HSS2_TOP_SMMU_TBU1_NS_ID                0x005c
#define HSS2_TOP_SMMU_TBU1_NS_ID_SC_PCIE1_NS_SID0_SHIFT                       0
#define HSS2_TOP_SMMU_TBU1_NS_ID_SC_PCIE1_NS_SID0_MASK                        0x000000ff
#define HSS2_TOP_SMMU_TBU1_NS_ID_SC_PCIE1_NS_SSID0_SHIFT                      8
#define HSS2_TOP_SMMU_TBU1_NS_ID_SC_PCIE1_NS_SSID0_MASK                       0x0000ff00
#define HSS2_TOP_SMMU_TBU1_NS_ID_SC_PCIE1_NS_SSIDV0_SHIFT                     16
#define HSS2_TOP_SMMU_TBU1_NS_ID_SC_PCIE1_NS_SSIDV0_MASK                      0x00010000
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG0         0x0068
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG1         0x006c
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG2         0x0070
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG3         0x0074
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG4         0x0078
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG5         0x007c
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG6         0x0080
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG6_SW_CRG_TPC_BWC_DYN_QOS4_W_TARGET_SHIFT 0
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG6_SW_CRG_TPC_BWC_DYN_QOS4_W_TARGET_MASK  0x000000ff
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG6_SW_CRG_TPC_BWC_DYN_QOS5_W_TARGET_SHIFT 8
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG6_SW_CRG_TPC_BWC_DYN_QOS5_W_TARGET_MASK  0x0000ff00
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG6_SW_CRG_TPC_BWC_DYN_QOS6_W_TARGET_SHIFT 16
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG6_SW_CRG_TPC_BWC_DYN_QOS6_W_TARGET_MASK  0x00ff0000
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG6_SW_CRG_TPC_BWC_DYN_QOS7_W_TARGET_SHIFT 24
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG6_SW_CRG_TPC_BWC_DYN_QOS7_W_TARGET_MASK  0xff000000
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG7         0x0084
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG7_SW_CRG_TPC_BWC_DYN_QOS0_W_TARGET_SHIFT 0
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG7_SW_CRG_TPC_BWC_DYN_QOS0_W_TARGET_MASK  0x000000ff
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG7_SW_CRG_TPC_BWC_DYN_QOS1_W_TARGET_SHIFT 8
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG7_SW_CRG_TPC_BWC_DYN_QOS1_W_TARGET_MASK  0x0000ff00
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG7_SW_CRG_TPC_BWC_DYN_QOS2_W_TARGET_SHIFT 16
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG7_SW_CRG_TPC_BWC_DYN_QOS2_W_TARGET_MASK  0x00ff0000
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG7_SW_CRG_TPC_BWC_DYN_QOS3_W_TARGET_SHIFT 24
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG7_SW_CRG_TPC_BWC_DYN_QOS3_W_TARGET_MASK  0xff000000
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG8         0x0088
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG8_SW_CRG_TPC_BWC_DYN_QOS4_R_TARGET_SHIFT 0
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG8_SW_CRG_TPC_BWC_DYN_QOS4_R_TARGET_MASK  0x000000ff
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG8_SW_CRG_TPC_BWC_DYN_QOS5_R_TARGET_SHIFT 8
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG8_SW_CRG_TPC_BWC_DYN_QOS5_R_TARGET_MASK  0x0000ff00
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG8_SW_CRG_TPC_BWC_DYN_QOS6_R_TARGET_SHIFT 16
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG8_SW_CRG_TPC_BWC_DYN_QOS6_R_TARGET_MASK  0x00ff0000
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG8_SW_CRG_TPC_BWC_DYN_QOS7_R_TARGET_SHIFT 24
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG8_SW_CRG_TPC_BWC_DYN_QOS7_R_TARGET_MASK  0xff000000
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG9         0x008c
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG9_SW_CRG_TPC_BWC_DYN_QOS0_R_TARGET_SHIFT 0
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG9_SW_CRG_TPC_BWC_DYN_QOS0_R_TARGET_MASK  0x000000ff
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG9_SW_CRG_TPC_BWC_DYN_QOS1_R_TARGET_SHIFT 8
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG9_SW_CRG_TPC_BWC_DYN_QOS1_R_TARGET_MASK  0x0000ff00
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG9_SW_CRG_TPC_BWC_DYN_QOS2_R_TARGET_SHIFT 16
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG9_SW_CRG_TPC_BWC_DYN_QOS2_R_TARGET_MASK  0x00ff0000
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG9_SW_CRG_TPC_BWC_DYN_QOS3_R_TARGET_SHIFT 24
#define HSS2_TOP_TPC_NORMAL_CRG_CONFIG9_SW_CRG_TPC_BWC_DYN_QOS3_R_TARGET_MASK  0xff000000
#define HSS2_TOP_TPC0_CRG_CONFIG0               0x0090
#define HSS2_TOP_TPC0_CRG_CONFIG0_TPC0_SW_CRG_TPC_EN_SHIFT                    0
#define HSS2_TOP_TPC0_CRG_CONFIG0_TPC0_SW_CRG_TPC_EN_MASK                     0x00000001
#define HSS2_TOP_TPC0_CRG_CONFIG0_TPC0_SW_CRG_TPC_BW_COUNTER_EN_SHIFT         1
#define HSS2_TOP_TPC0_CRG_CONFIG0_TPC0_SW_CRG_TPC_BW_COUNTER_EN_MASK          0x00000002
#define HSS2_TOP_TPC0_CRG_CONFIG0_TPC0_SW_CRG_TPC_BWC_STATIC_R_EN_SHIFT       2
#define HSS2_TOP_TPC0_CRG_CONFIG0_TPC0_SW_CRG_TPC_BWC_STATIC_R_EN_MASK        0x00000004
#define HSS2_TOP_TPC0_CRG_CONFIG0_TPC0_SW_CRG_TPC_BWC_STATIC_W_EN_SHIFT       3
#define HSS2_TOP_TPC0_CRG_CONFIG0_TPC0_SW_CRG_TPC_BWC_STATIC_W_EN_MASK        0x00000008
#define HSS2_TOP_TPC0_CRG_CONFIG0_TPC0_SW_CRG_TPC_BWC_DYN_R_EN_SHIFT          4
#define HSS2_TOP_TPC0_CRG_CONFIG0_TPC0_SW_CRG_TPC_BWC_DYN_R_EN_MASK           0x00000010
#define HSS2_TOP_TPC0_CRG_CONFIG0_TPC0_SW_CRG_TPC_BWC_DYN_W_EN_SHIFT          5
#define HSS2_TOP_TPC0_CRG_CONFIG0_TPC0_SW_CRG_TPC_BWC_DYN_W_EN_MASK           0x00000020
#define HSS2_TOP_TPC0_CRG_CONFIG0_TPC0_SW_CRG_TPC_COUNT_OUTSTANDING_EN_SHIFT  6
#define HSS2_TOP_TPC0_CRG_CONFIG0_TPC0_SW_CRG_TPC_COUNT_OUTSTANDING_EN_MASK   0x00000040
#define HSS2_TOP_TPC0_CRG_CONFIG0_TPC0_SW_CRG_TPC_AFBC_ADDR_SCRAMBLE_EN_SHIFT 7
#define HSS2_TOP_TPC0_CRG_CONFIG0_TPC0_SW_CRG_TPC_AFBC_ADDR_SCRAMBLE_EN_MASK  0x00000080
#define HSS2_TOP_TPC0_CRG_CONFIG0_TPC0_SW_CRG_TPC_COUNT_AR_MAX_SHIFT          8
#define HSS2_TOP_TPC0_CRG_CONFIG0_TPC0_SW_CRG_TPC_COUNT_AR_MAX_MASK           0x00007f00
#define HSS2_TOP_TPC0_CRG_CONFIG0_RESERVED_TPC0_CFG0_1_SHIFT                  15
#define HSS2_TOP_TPC0_CRG_CONFIG0_RESERVED_TPC0_CFG0_1_MASK                   0x00008000
#define HSS2_TOP_TPC0_CRG_CONFIG0_TPC0_SW_CRG_TPC_COUNT_AW_MAX_SHIFT          16
#define HSS2_TOP_TPC0_CRG_CONFIG0_TPC0_SW_CRG_TPC_COUNT_AW_MAX_MASK           0x007f0000
#define HSS2_TOP_TPC0_CRG_CONFIG0_RESERVED_TPC0_CFG0_0_SHIFT                  23
#define HSS2_TOP_TPC0_CRG_CONFIG0_RESERVED_TPC0_CFG0_0_MASK                   0xff800000
#define HSS2_TOP_TPC0_CRG_CONFIG1               0x0094
#define HSS2_TOP_TPC0_CRG_CONFIG1_TPC0_SW_CRG_TPC_BWC_STATIC_R_TARGET_SHIFT   0
#define HSS2_TOP_TPC0_CRG_CONFIG1_TPC0_SW_CRG_TPC_BWC_STATIC_R_TARGET_MASK    0x000000ff
#define HSS2_TOP_TPC0_CRG_CONFIG1_TPC0_SW_CRG_TPC_BWC_STATIC_W_TARGET_SHIFT   8
#define HSS2_TOP_TPC0_CRG_CONFIG1_TPC0_SW_CRG_TPC_BWC_STATIC_W_TARGET_MASK    0x0000ff00
#define HSS2_TOP_TPC0_CRG_CONFIG2               0x0098
#define HSS2_TOP_TPC0_CRG_CONFIG2_TPC0_SW_CRG_TPC_QOS_0_SHIFT                 0
#define HSS2_TOP_TPC0_CRG_CONFIG2_TPC0_SW_CRG_TPC_QOS_0_MASK                  0x0000000f
#define HSS2_TOP_TPC0_CRG_CONFIG2_TPC0_SW_CRG_TPC_QOS_1_SHIFT                 4
#define HSS2_TOP_TPC0_CRG_CONFIG2_TPC0_SW_CRG_TPC_QOS_1_MASK                  0x000000f0
#define HSS2_TOP_TPC0_CRG_CONFIG2_TPC0_SW_CRG_TPC_QOS_2_SHIFT                 8
#define HSS2_TOP_TPC0_CRG_CONFIG2_TPC0_SW_CRG_TPC_QOS_2_MASK                  0x00000f00
#define HSS2_TOP_TPC0_CRG_CONFIG2_TPC0_SW_CRG_TPC_QOS_3_SHIFT                 12
#define HSS2_TOP_TPC0_CRG_CONFIG2_TPC0_SW_CRG_TPC_QOS_3_MASK                  0x0000f000
#define HSS2_TOP_TPC0_CRG_CONFIG2_TPC0_SW_CRG_TPC_QOS_4_SHIFT                 16
#define HSS2_TOP_TPC0_CRG_CONFIG2_TPC0_SW_CRG_TPC_QOS_4_MASK                  0x000f0000
#define HSS2_TOP_TPC0_CRG_CONFIG2_TPC0_SW_CRG_TPC_QOS_5_SHIFT                 20
#define HSS2_TOP_TPC0_CRG_CONFIG2_TPC0_SW_CRG_TPC_QOS_5_MASK                  0x00f00000
#define HSS2_TOP_TPC0_CRG_CONFIG2_TPC0_SW_CRG_TPC_QOS_6_SHIFT                 24
#define HSS2_TOP_TPC0_CRG_CONFIG2_TPC0_SW_CRG_TPC_QOS_6_MASK                  0x0f000000
#define HSS2_TOP_TPC0_CRG_CONFIG2_TPC0_SW_CRG_TPC_QOS_7_SHIFT                 28
#define HSS2_TOP_TPC0_CRG_CONFIG2_TPC0_SW_CRG_TPC_QOS_7_MASK                  0x70000000
#define HSS2_TOP_TPC0_CRG_CONFIG2_TPC0_SW_CRG_TPC_QOS_SEL_SHIFT               31
#define HSS2_TOP_TPC0_CRG_CONFIG2_TPC0_SW_CRG_TPC_QOS_SEL_MASK                0x80000000
#define HSS2_TOP_TPC0_CRG_CONFIG3               0x009c
#define HSS2_TOP_TPC0_CRG_CONFIG3_TPC0_SW_CRG_TPC_BWC_R_SAT_SHIFT             0
#define HSS2_TOP_TPC0_CRG_CONFIG3_TPC0_SW_CRG_TPC_BWC_R_SAT_MASK              0x0000ffff
#define HSS2_TOP_TPC0_CRG_CONFIG3_TPC0_SW_CRG_TPC_BWC_W_SAT_SHIFT             16
#define HSS2_TOP_TPC0_CRG_CONFIG3_TPC0_SW_CRG_TPC_BWC_W_SAT_MASK              0xffff0000
#define HSS2_TOP_TPC0_CRG_STATUS0               0x00a0
#define HSS2_TOP_TPC0_CRG_STATUS1               0x00a4
#define HSS2_TOP_TPC0_CRG_STATUS2               0x00a8
#define HSS2_TOP_TPC1_CRG_CONFIG0               0x00ac
#define HSS2_TOP_TPC1_CRG_CONFIG0_TPC1_SW_CRG_TPC_EN_SHIFT                    0
#define HSS2_TOP_TPC1_CRG_CONFIG0_TPC1_SW_CRG_TPC_EN_MASK                     0x00000001
#define HSS2_TOP_TPC1_CRG_CONFIG0_TPC1_SW_CRG_TPC_BW_COUNTER_EN_SHIFT         1
#define HSS2_TOP_TPC1_CRG_CONFIG0_TPC1_SW_CRG_TPC_BW_COUNTER_EN_MASK          0x00000002
#define HSS2_TOP_TPC1_CRG_CONFIG0_TPC1_SW_CRG_TPC_BWC_STATIC_R_EN_SHIFT       2
#define HSS2_TOP_TPC1_CRG_CONFIG0_TPC1_SW_CRG_TPC_BWC_STATIC_R_EN_MASK        0x00000004
#define HSS2_TOP_TPC1_CRG_CONFIG0_TPC1_SW_CRG_TPC_BWC_STATIC_W_EN_SHIFT       3
#define HSS2_TOP_TPC1_CRG_CONFIG0_TPC1_SW_CRG_TPC_BWC_STATIC_W_EN_MASK        0x00000008
#define HSS2_TOP_TPC1_CRG_CONFIG0_TPC1_SW_CRG_TPC_BWC_DYN_R_EN_SHIFT          4
#define HSS2_TOP_TPC1_CRG_CONFIG0_TPC1_SW_CRG_TPC_BWC_DYN_R_EN_MASK           0x00000010
#define HSS2_TOP_TPC1_CRG_CONFIG0_TPC1_SW_CRG_TPC_BWC_DYN_W_EN_SHIFT          5
#define HSS2_TOP_TPC1_CRG_CONFIG0_TPC1_SW_CRG_TPC_BWC_DYN_W_EN_MASK           0x00000020
#define HSS2_TOP_TPC1_CRG_CONFIG0_TPC1_SW_CRG_TPC_COUNT_OUTSTANDING_EN_SHIFT  6
#define HSS2_TOP_TPC1_CRG_CONFIG0_TPC1_SW_CRG_TPC_COUNT_OUTSTANDING_EN_MASK   0x00000040
#define HSS2_TOP_TPC1_CRG_CONFIG0_TPC1_SW_CRG_TPC_AFBC_ADDR_SCRAMBLE_EN_SHIFT 7
#define HSS2_TOP_TPC1_CRG_CONFIG0_TPC1_SW_CRG_TPC_AFBC_ADDR_SCRAMBLE_EN_MASK  0x00000080
#define HSS2_TOP_TPC1_CRG_CONFIG0_TPC1_SW_CRG_TPC_COUNT_AR_MAX_SHIFT          8
#define HSS2_TOP_TPC1_CRG_CONFIG0_TPC1_SW_CRG_TPC_COUNT_AR_MAX_MASK           0x00007f00
#define HSS2_TOP_TPC1_CRG_CONFIG0_RESERVED_TPC1_CFG0_1_SHIFT                  15
#define HSS2_TOP_TPC1_CRG_CONFIG0_RESERVED_TPC1_CFG0_1_MASK                   0x00008000
#define HSS2_TOP_TPC1_CRG_CONFIG0_TPC1_SW_CRG_TPC_COUNT_AW_MAX_SHIFT          16
#define HSS2_TOP_TPC1_CRG_CONFIG0_TPC1_SW_CRG_TPC_COUNT_AW_MAX_MASK           0x007f0000
#define HSS2_TOP_TPC1_CRG_CONFIG0_RESERVED_TPC1_CFG0_0_SHIFT                  23
#define HSS2_TOP_TPC1_CRG_CONFIG0_RESERVED_TPC1_CFG0_0_MASK                   0xff800000
#define HSS2_TOP_TPC1_CRG_CONFIG1               0x00b0
#define HSS2_TOP_TPC1_CRG_CONFIG1_TPC1_SW_CRG_TPC_BWC_STATIC_R_TARGET_SHIFT   0
#define HSS2_TOP_TPC1_CRG_CONFIG1_TPC1_SW_CRG_TPC_BWC_STATIC_R_TARGET_MASK    0x000000ff
#define HSS2_TOP_TPC1_CRG_CONFIG1_TPC1_SW_CRG_TPC_BWC_STATIC_W_TARGET_SHIFT   8
#define HSS2_TOP_TPC1_CRG_CONFIG1_TPC1_SW_CRG_TPC_BWC_STATIC_W_TARGET_MASK    0x0000ff00
#define HSS2_TOP_TPC1_CRG_CONFIG2               0x00b4
#define HSS2_TOP_TPC1_CRG_CONFIG2_TPC1_SW_CRG_TPC_QOS_0_SHIFT                 0
#define HSS2_TOP_TPC1_CRG_CONFIG2_TPC1_SW_CRG_TPC_QOS_0_MASK                  0x0000000f
#define HSS2_TOP_TPC1_CRG_CONFIG2_TPC1_SW_CRG_TPC_QOS_1_SHIFT                 4
#define HSS2_TOP_TPC1_CRG_CONFIG2_TPC1_SW_CRG_TPC_QOS_1_MASK                  0x000000f0
#define HSS2_TOP_TPC1_CRG_CONFIG2_TPC1_SW_CRG_TPC_QOS_2_SHIFT                 8
#define HSS2_TOP_TPC1_CRG_CONFIG2_TPC1_SW_CRG_TPC_QOS_2_MASK                  0x00000f00
#define HSS2_TOP_TPC1_CRG_CONFIG2_TPC1_SW_CRG_TPC_QOS_3_SHIFT                 12
#define HSS2_TOP_TPC1_CRG_CONFIG2_TPC1_SW_CRG_TPC_QOS_3_MASK                  0x0000f000
#define HSS2_TOP_TPC1_CRG_CONFIG2_TPC1_SW_CRG_TPC_QOS_4_SHIFT                 16
#define HSS2_TOP_TPC1_CRG_CONFIG2_TPC1_SW_CRG_TPC_QOS_4_MASK                  0x000f0000
#define HSS2_TOP_TPC1_CRG_CONFIG2_TPC1_SW_CRG_TPC_QOS_5_SHIFT                 20
#define HSS2_TOP_TPC1_CRG_CONFIG2_TPC1_SW_CRG_TPC_QOS_5_MASK                  0x00f00000
#define HSS2_TOP_TPC1_CRG_CONFIG2_TPC1_SW_CRG_TPC_QOS_6_SHIFT                 24
#define HSS2_TOP_TPC1_CRG_CONFIG2_TPC1_SW_CRG_TPC_QOS_6_MASK                  0x0f000000
#define HSS2_TOP_TPC1_CRG_CONFIG2_TPC1_SW_CRG_TPC_QOS_7_SHIFT                 28
#define HSS2_TOP_TPC1_CRG_CONFIG2_TPC1_SW_CRG_TPC_QOS_7_MASK                  0x70000000
#define HSS2_TOP_TPC1_CRG_CONFIG2_TPC1_SW_CRG_TPC_QOS_SEL_SHIFT               31
#define HSS2_TOP_TPC1_CRG_CONFIG2_TPC1_SW_CRG_TPC_QOS_SEL_MASK                0x80000000
#define HSS2_TOP_TPC1_CRG_CONFIG3               0x00b8
#define HSS2_TOP_TPC1_CRG_CONFIG3_TPC1_SW_CRG_TPC_BWC_R_SAT_SHIFT             0
#define HSS2_TOP_TPC1_CRG_CONFIG3_TPC1_SW_CRG_TPC_BWC_R_SAT_MASK              0x0000ffff
#define HSS2_TOP_TPC1_CRG_CONFIG3_TPC1_SW_CRG_TPC_BWC_W_SAT_SHIFT             16
#define HSS2_TOP_TPC1_CRG_CONFIG3_TPC1_SW_CRG_TPC_BWC_W_SAT_MASK              0xffff0000
#define HSS2_TOP_TPC1_CRG_STATUS0               0x00bc
#define HSS2_TOP_TPC1_CRG_STATUS1               0x00c0
#define HSS2_TOP_TPC1_CRG_STATUS2               0x00c4
#define HSS2_TOP_TPC2_CRG_CONFIG0               0x00c8
#define HSS2_TOP_TPC2_CRG_CONFIG0_TPC2_SW_CRG_TPC_EN_SHIFT                    0
#define HSS2_TOP_TPC2_CRG_CONFIG0_TPC2_SW_CRG_TPC_EN_MASK                     0x00000001
#define HSS2_TOP_TPC2_CRG_CONFIG0_TPC2_SW_CRG_TPC_BW_COUNTER_EN_SHIFT         1
#define HSS2_TOP_TPC2_CRG_CONFIG0_TPC2_SW_CRG_TPC_BW_COUNTER_EN_MASK          0x00000002
#define HSS2_TOP_TPC2_CRG_CONFIG0_TPC2_SW_CRG_TPC_BWC_STATIC_R_EN_SHIFT       2
#define HSS2_TOP_TPC2_CRG_CONFIG0_TPC2_SW_CRG_TPC_BWC_STATIC_R_EN_MASK        0x00000004
#define HSS2_TOP_TPC2_CRG_CONFIG0_TPC2_SW_CRG_TPC_BWC_STATIC_W_EN_SHIFT       3
#define HSS2_TOP_TPC2_CRG_CONFIG0_TPC2_SW_CRG_TPC_BWC_STATIC_W_EN_MASK        0x00000008
#define HSS2_TOP_TPC2_CRG_CONFIG0_TPC2_SW_CRG_TPC_BWC_DYN_R_EN_SHIFT          4
#define HSS2_TOP_TPC2_CRG_CONFIG0_TPC2_SW_CRG_TPC_BWC_DYN_R_EN_MASK           0x00000010
#define HSS2_TOP_TPC2_CRG_CONFIG0_TPC2_SW_CRG_TPC_BWC_DYN_W_EN_SHIFT          5
#define HSS2_TOP_TPC2_CRG_CONFIG0_TPC2_SW_CRG_TPC_BWC_DYN_W_EN_MASK           0x00000020
#define HSS2_TOP_TPC2_CRG_CONFIG0_TPC2_SW_CRG_TPC_COUNT_OUTSTANDING_EN_SHIFT  6
#define HSS2_TOP_TPC2_CRG_CONFIG0_TPC2_SW_CRG_TPC_COUNT_OUTSTANDING_EN_MASK   0x00000040
#define HSS2_TOP_TPC2_CRG_CONFIG0_TPC2_SW_CRG_TPC_AFBC_ADDR_SCRAMBLE_EN_SHIFT 7
#define HSS2_TOP_TPC2_CRG_CONFIG0_TPC2_SW_CRG_TPC_AFBC_ADDR_SCRAMBLE_EN_MASK  0x00000080
#define HSS2_TOP_TPC2_CRG_CONFIG0_TPC2_SW_CRG_TPC_COUNT_AR_MAX_SHIFT          8
#define HSS2_TOP_TPC2_CRG_CONFIG0_TPC2_SW_CRG_TPC_COUNT_AR_MAX_MASK           0x00007f00
#define HSS2_TOP_TPC2_CRG_CONFIG0_RESERVED_TPC2_CFG0_1_SHIFT                  15
#define HSS2_TOP_TPC2_CRG_CONFIG0_RESERVED_TPC2_CFG0_1_MASK                   0x00008000
#define HSS2_TOP_TPC2_CRG_CONFIG0_TPC2_SW_CRG_TPC_COUNT_AW_MAX_SHIFT          16
#define HSS2_TOP_TPC2_CRG_CONFIG0_TPC2_SW_CRG_TPC_COUNT_AW_MAX_MASK           0x007f0000
#define HSS2_TOP_TPC2_CRG_CONFIG0_RESERVED_TPC2_CFG0_0_SHIFT                  23
#define HSS2_TOP_TPC2_CRG_CONFIG0_RESERVED_TPC2_CFG0_0_MASK                   0xff800000
#define HSS2_TOP_TPC2_CRG_CONFIG1               0x00cc
#define HSS2_TOP_TPC2_CRG_CONFIG1_TPC2_SW_CRG_TPC_BWC_STATIC_R_TARGET_SHIFT   0
#define HSS2_TOP_TPC2_CRG_CONFIG1_TPC2_SW_CRG_TPC_BWC_STATIC_R_TARGET_MASK    0x000000ff
#define HSS2_TOP_TPC2_CRG_CONFIG1_TPC2_SW_CRG_TPC_BWC_STATIC_W_TARGET_SHIFT   8
#define HSS2_TOP_TPC2_CRG_CONFIG1_TPC2_SW_CRG_TPC_BWC_STATIC_W_TARGET_MASK    0x0000ff00
#define HSS2_TOP_TPC2_CRG_CONFIG2               0x00d0
#define HSS2_TOP_TPC2_CRG_CONFIG2_TPC2_SW_CRG_TPC_QOS_0_SHIFT                 0
#define HSS2_TOP_TPC2_CRG_CONFIG2_TPC2_SW_CRG_TPC_QOS_0_MASK                  0x0000000f
#define HSS2_TOP_TPC2_CRG_CONFIG2_TPC2_SW_CRG_TPC_QOS_1_SHIFT                 4
#define HSS2_TOP_TPC2_CRG_CONFIG2_TPC2_SW_CRG_TPC_QOS_1_MASK                  0x000000f0
#define HSS2_TOP_TPC2_CRG_CONFIG2_TPC2_SW_CRG_TPC_QOS_2_SHIFT                 8
#define HSS2_TOP_TPC2_CRG_CONFIG2_TPC2_SW_CRG_TPC_QOS_2_MASK                  0x00000f00
#define HSS2_TOP_TPC2_CRG_CONFIG2_TPC2_SW_CRG_TPC_QOS_3_SHIFT                 12
#define HSS2_TOP_TPC2_CRG_CONFIG2_TPC2_SW_CRG_TPC_QOS_3_MASK                  0x0000f000
#define HSS2_TOP_TPC2_CRG_CONFIG2_TPC2_SW_CRG_TPC_QOS_4_SHIFT                 16
#define HSS2_TOP_TPC2_CRG_CONFIG2_TPC2_SW_CRG_TPC_QOS_4_MASK                  0x000f0000
#define HSS2_TOP_TPC2_CRG_CONFIG2_TPC2_SW_CRG_TPC_QOS_5_SHIFT                 20
#define HSS2_TOP_TPC2_CRG_CONFIG2_TPC2_SW_CRG_TPC_QOS_5_MASK                  0x00f00000
#define HSS2_TOP_TPC2_CRG_CONFIG2_TPC2_SW_CRG_TPC_QOS_6_SHIFT                 24
#define HSS2_TOP_TPC2_CRG_CONFIG2_TPC2_SW_CRG_TPC_QOS_6_MASK                  0x0f000000
#define HSS2_TOP_TPC2_CRG_CONFIG2_TPC2_SW_CRG_TPC_QOS_7_SHIFT                 28
#define HSS2_TOP_TPC2_CRG_CONFIG2_TPC2_SW_CRG_TPC_QOS_7_MASK                  0x70000000
#define HSS2_TOP_TPC2_CRG_CONFIG2_TPC2_SW_CRG_TPC_QOS_SEL_SHIFT               31
#define HSS2_TOP_TPC2_CRG_CONFIG2_TPC2_SW_CRG_TPC_QOS_SEL_MASK                0x80000000
#define HSS2_TOP_TPC2_CRG_CONFIG3               0x00d4
#define HSS2_TOP_TPC2_CRG_CONFIG3_TPC2_SW_CRG_TPC_BWC_R_SAT_SHIFT             0
#define HSS2_TOP_TPC2_CRG_CONFIG3_TPC2_SW_CRG_TPC_BWC_R_SAT_MASK              0x0000ffff
#define HSS2_TOP_TPC2_CRG_CONFIG3_TPC2_SW_CRG_TPC_BWC_W_SAT_SHIFT             16
#define HSS2_TOP_TPC2_CRG_CONFIG3_TPC2_SW_CRG_TPC_BWC_W_SAT_MASK              0xffff0000
#define HSS2_TOP_TPC2_CRG_STATUS0               0x00d8
#define HSS2_TOP_TPC2_CRG_STATUS1               0x00dc
#define HSS2_TOP_TPC2_CRG_STATUS2               0x00e0
#define HSS2_TOP_NDB_ASYNC_DFX                  0x1000
#define HSS2_TOP_NDB_ASYNC_DFX_HSS2_NDB_MST_DFX_0_SHIFT                       0
#define HSS2_TOP_NDB_ASYNC_DFX_HSS2_NDB_MST_DFX_0_MASK                        0x0000001f
#define HSS2_TOP_NDB_ASYNC_DFX_HSS2_NDB_SLV_DFX_0_SHIFT                       5
#define HSS2_TOP_NDB_ASYNC_DFX_HSS2_NDB_SLV_DFX_0_MASK                        0x000003e0
#define HSS2_TOP_NDB_ASYNC_DFX_HSS2_NDB_MST_DFX_1_SHIFT                       10
#define HSS2_TOP_NDB_ASYNC_DFX_HSS2_NDB_MST_DFX_1_MASK                        0x00007c00
#define HSS2_TOP_NDB_ASYNC_DFX_HSS2_NDB_SLV_DFX_1_SHIFT                       15
#define HSS2_TOP_NDB_ASYNC_DFX_HSS2_NDB_SLV_DFX_1_MASK                        0x000f8000
#define HSS2_TOP_NDB_ASYNC_DFX_HSS2_NDB_MST_DFX_2_SHIFT                       20
#define HSS2_TOP_NDB_ASYNC_DFX_HSS2_NDB_MST_DFX_2_MASK                        0x01f00000
#define HSS2_TOP_NDB_ASYNC_DFX_HSS2_NDB_SLV_DFX_2_SHIFT                       25
#define HSS2_TOP_NDB_ASYNC_DFX_HSS2_NDB_SLV_DFX_2_MASK                        0x3e000000
#define HSS2_TOP_SMMU_TBU0_S_ID                 0x2000
#define HSS2_TOP_SMMU_TBU0_S_ID_SC_PCIE0_S_SID0_SHIFT                         0
#define HSS2_TOP_SMMU_TBU0_S_ID_SC_PCIE0_S_SID0_MASK                          0x000000ff
#define HSS2_TOP_SMMU_TBU0_S_ID_SC_PCIE0_S_SSID0_SHIFT                        8
#define HSS2_TOP_SMMU_TBU0_S_ID_SC_PCIE0_S_SSID0_MASK                         0x0000ff00
#define HSS2_TOP_SMMU_TBU0_S_ID_SC_PCIE0_S_SSIDV0_SHIFT                       16
#define HSS2_TOP_SMMU_TBU0_S_ID_SC_PCIE0_S_SSIDV0_MASK                        0x00010000
#define HSS2_TOP_SMMU_TBU1_S_ID                 0x2004
#define HSS2_TOP_SMMU_TBU1_S_ID_SC_PCIE1_S_SID0_SHIFT                         0
#define HSS2_TOP_SMMU_TBU1_S_ID_SC_PCIE1_S_SID0_MASK                          0x000000ff
#define HSS2_TOP_SMMU_TBU1_S_ID_SC_PCIE1_S_SSID0_SHIFT                        8
#define HSS2_TOP_SMMU_TBU1_S_ID_SC_PCIE1_S_SSID0_MASK                         0x0000ff00
#define HSS2_TOP_SMMU_TBU1_S_ID_SC_PCIE1_S_SSIDV0_SHIFT                       16
#define HSS2_TOP_SMMU_TBU1_S_ID_SC_PCIE1_S_SSIDV0_MASK                        0x00010000
#define HSS2_TOP_SMMU_TCU_S_IRPT_CLEAR          0x4000
#define HSS2_TOP_SMMU_TCU_S_IRPT_CLEAR_SC_SMMU_TCU_S_IRPT_CLR_SHIFT           0
#define HSS2_TOP_SMMU_TCU_S_IRPT_CLEAR_SC_SMMU_TCU_S_IRPT_CLR_MASK            0x00000007
#define HSS2_TOP_SMMU_TCU_S_IRPT_STATE          0x4004
#define HSS2_TOP_SMMU_TCU_S_IRPT_STATE_SC_SMMU_TCU_S_IRPT_ST_SHIFT            0
#define HSS2_TOP_SMMU_TCU_S_IRPT_STATE_SC_SMMU_TCU_S_IRPT_ST_MASK             0x00000007
#define HSS2_TOP_SMMU_TCU_S_TIEOFF_CFG          0x4008
#define HSS2_TOP_SMMU_TCU_S_TIEOFF_CFG_SC_SMMU_TCU_SEC_OVERRIDE_SHIFT         0
#define HSS2_TOP_SMMU_TCU_S_TIEOFF_CFG_SC_SMMU_TCU_SEC_OVERRIDE_MASK          0x00000001
#define HSS2_TOP_SMMU_TCU_IRPT_CLEAR            0x5000
#define HSS2_TOP_SMMU_TCU_IRPT_CLEAR_SC_SMMU_TCU_RAS_IRPT_CLR_SHIFT           0
#define HSS2_TOP_SMMU_TCU_IRPT_CLEAR_SC_SMMU_TCU_RAS_IRPT_CLR_MASK            0x00000001
#define HSS2_TOP_SMMU_TCU_IRPT_CLEAR_SC_SMMU_TCU_PMU_IRPT_CLR_SHIFT           1
#define HSS2_TOP_SMMU_TCU_IRPT_CLEAR_SC_SMMU_TCU_PMU_IRPT_CLR_MASK            0x00000002
#define HSS2_TOP_SMMU_TCU_IRPT_CLEAR_SC_SMMU_TCU_NS_IRPT_CLR_SHIFT            2
#define HSS2_TOP_SMMU_TCU_IRPT_CLEAR_SC_SMMU_TCU_NS_IRPT_CLR_MASK             0x0000001c
#define HSS2_TOP_SMMU_TCU_IRPT_STATE            0x5004
#define HSS2_TOP_SMMU_TCU_IRPT_STATE_SC_SMMU_TCU_PMU_IRPT_ST_SHIFT            0
#define HSS2_TOP_SMMU_TCU_IRPT_STATE_SC_SMMU_TCU_PMU_IRPT_ST_MASK             0x00000001
#define HSS2_TOP_SMMU_TCU_IRPT_STATE_SC_SMMU_TCU_RAS_IRPT_ST_SHIFT            1
#define HSS2_TOP_SMMU_TCU_IRPT_STATE_SC_SMMU_TCU_RAS_IRPT_ST_MASK             0x00000002
#define HSS2_TOP_SMMU_TCU_IRPT_STATE_SC_SMMU_TCU_NS_IRPT_ST_SHIFT             2
#define HSS2_TOP_SMMU_TCU_IRPT_STATE_SC_SMMU_TCU_NS_IRPT_ST_MASK              0x0000001c
#define HSS2_TOP_SMMU_TCU_QCH_CG_CTRL           0x5008
#define HSS2_TOP_SMMU_TCU_QCH_CG_CTRL_SC_SMMU_TCU_QACTIVE_CG_THRESH_SHIFT     0
#define HSS2_TOP_SMMU_TCU_QCH_CG_CTRL_SC_SMMU_TCU_QACTIVE_CG_THRESH_MASK      0x0000ffff
#define HSS2_TOP_SMMU_TCU_QCH_CG_CTRL_SC_SMMU_TCU_QREQN_CG_SET_SHIFT          16
#define HSS2_TOP_SMMU_TCU_QCH_CG_CTRL_SC_SMMU_TCU_QREQN_CG_SET_MASK           0x00010000
#define HSS2_TOP_SMMU_TCU_QCH_CG_CTRL_SC_SMMU_TCU_QCH_CG_CTRL_EN_SHIFT        17
#define HSS2_TOP_SMMU_TCU_QCH_CG_CTRL_SC_SMMU_TCU_QCH_CG_CTRL_EN_MASK         0x00020000
#define HSS2_TOP_SMMU_TCU_QCH_CG_STATE          0x500c
#define HSS2_TOP_SMMU_TCU_QCH_CG_STATE_SC_SMMU_TCU_QCH_CG_STATE_NXT_SHIFT     0
#define HSS2_TOP_SMMU_TCU_QCH_CG_STATE_SC_SMMU_TCU_QCH_CG_STATE_NXT_MASK      0x00000003
#define HSS2_TOP_SMMU_TCU_QCH_CG_STATE_SC_SMMU_TCU_QCH_CG_STATE_SHIFT         2
#define HSS2_TOP_SMMU_TCU_QCH_CG_STATE_SC_SMMU_TCU_QCH_CG_STATE_MASK          0x0000000c
#define HSS2_TOP_SMMU_TCU_QCH_CG_STATE_SC_SMMU_TCU_QCTRL_CLKEN_ST_SHIFT       4
#define HSS2_TOP_SMMU_TCU_QCH_CG_STATE_SC_SMMU_TCU_QCTRL_CLKEN_ST_MASK        0x00000010
#define HSS2_TOP_SMMU_TCU_QCH_CG_STATE_SC_SMMU_TCU_QACTIVE_CG_ST_SHIFT        5
#define HSS2_TOP_SMMU_TCU_QCH_CG_STATE_SC_SMMU_TCU_QACTIVE_CG_ST_MASK         0x00000020
#define HSS2_TOP_SMMU_TCU_QCH_CG_STATE_SC_SMMU_TCU_QDENY_CG_ST_SHIFT          6
#define HSS2_TOP_SMMU_TCU_QCH_CG_STATE_SC_SMMU_TCU_QDENY_CG_ST_MASK           0x00000040
#define HSS2_TOP_SMMU_TCU_QCH_CG_STATE_SC_SMMU_TCU_QACCEPTN_CG_ST_SHIFT       7
#define HSS2_TOP_SMMU_TCU_QCH_CG_STATE_SC_SMMU_TCU_QACCEPTN_CG_ST_MASK        0x00000080
#define HSS2_TOP_SMMU_TCU_QCH_CG_STATE_SC_SMMU_TCU_QREQN_CG_ST_SHIFT          8
#define HSS2_TOP_SMMU_TCU_QCH_CG_STATE_SC_SMMU_TCU_QREQN_CG_ST_MASK           0x00000100
#define HSS2_TOP_SMMU_TCU_QCH_PD_CTRL           0x5010
#define HSS2_TOP_SMMU_TCU_QCH_PD_CTRL_SC_SMMU_TCU_QREQN_PD_SHIFT              0
#define HSS2_TOP_SMMU_TCU_QCH_PD_CTRL_SC_SMMU_TCU_QREQN_PD_MASK               0x00000001
#define HSS2_TOP_SMMU_TCU_QCH_PD_STATE          0x5014
#define HSS2_TOP_SMMU_TCU_QCH_PD_STATE_SC_SMMU_TCU_QACTIVE_PD_SHIFT           0
#define HSS2_TOP_SMMU_TCU_QCH_PD_STATE_SC_SMMU_TCU_QACTIVE_PD_MASK            0x00000001
#define HSS2_TOP_SMMU_TCU_QCH_PD_STATE_SC_SMMU_TCU_QDENY_PD_SHIFT             1
#define HSS2_TOP_SMMU_TCU_QCH_PD_STATE_SC_SMMU_TCU_QDENY_PD_MASK              0x00000002
#define HSS2_TOP_SMMU_TCU_QCH_PD_STATE_SC_SMMU_TCU_QACCEPTN_PD_SHIFT          2
#define HSS2_TOP_SMMU_TCU_QCH_PD_STATE_SC_SMMU_TCU_QACCEPTN_PD_MASK           0x00000004
#define HSS2_TOP_SMMU_TCU_PMU_SNAP_REQ          0x5018
#define HSS2_TOP_SMMU_TCU_PMU_SNAP_REQ_SC_SMMU_TCU_PMUSNAPSHOT_REQ_SHIFT      0
#define HSS2_TOP_SMMU_TCU_PMU_SNAP_REQ_SC_SMMU_TCU_PMUSNAPSHOT_REQ_MASK       0x00000001
#define HSS2_TOP_SMMU_TCU_PMU_SNAP_ACK          0x501c
#define HSS2_TOP_SMMU_TCU_PMU_SNAP_ACK_SC_SMMU_TCU_PMUSNAPSHOT_ACK_SHIFT      0
#define HSS2_TOP_SMMU_TCU_PMU_SNAP_ACK_SC_SMMU_TCU_PMUSNAPSHOT_ACK_MASK       0x00000001
#define HSS2_TOP_SMMU_TBU0_S_TIEOFF_CFG         0x6000
#define HSS2_TOP_SMMU_TBU0_S_TIEOFF_CFG_SC_SMMU_TBU0_SEC_OVERRIDE_SHIFT       0
#define HSS2_TOP_SMMU_TBU0_S_TIEOFF_CFG_SC_SMMU_TBU0_SEC_OVERRIDE_MASK        0x00000001
#define HSS2_TOP_SMMU_TBU1_S_TIEOFF_CFG         0x6004
#define HSS2_TOP_SMMU_TBU1_S_TIEOFF_CFG_SC_SMMU_TBU1_SEC_OVERRIDE_SHIFT       0
#define HSS2_TOP_SMMU_TBU1_S_TIEOFF_CFG_SC_SMMU_TBU1_SEC_OVERRIDE_MASK        0x00000001
#define HSS2_TOP_SMMU_TBU0_IRPT_CLEAR           0x7000
#define HSS2_TOP_SMMU_TBU0_IRPT_CLEAR_SC_SMMU_TBU0_RAS_IRPT_CLR_SHIFT         0
#define HSS2_TOP_SMMU_TBU0_IRPT_CLEAR_SC_SMMU_TBU0_RAS_IRPT_CLR_MASK          0x00000001
#define HSS2_TOP_SMMU_TBU0_IRPT_CLEAR_SC_SMMU_TBU0_PMU_IRPT_CLR_SHIFT         1
#define HSS2_TOP_SMMU_TBU0_IRPT_CLEAR_SC_SMMU_TBU0_PMU_IRPT_CLR_MASK          0x00000002
#define HSS2_TOP_SMMU_TBU0_IRPT_STATE           0x7004
#define HSS2_TOP_SMMU_TBU0_IRPT_STATE_SC_SMMU_TBU0_RAS_IRPT_ST_SHIFT          0
#define HSS2_TOP_SMMU_TBU0_IRPT_STATE_SC_SMMU_TBU0_RAS_IRPT_ST_MASK           0x00000001
#define HSS2_TOP_SMMU_TBU0_IRPT_STATE_SC_SMMU_TBU0_PMU_IRPT_ST_SHIFT          1
#define HSS2_TOP_SMMU_TBU0_IRPT_STATE_SC_SMMU_TBU0_PMU_IRPT_ST_MASK           0x00000002
#define HSS2_TOP_SMMU_TBU0_TIEOFF_CFG           0x7008
#define HSS2_TOP_SMMU_TBU0_TIEOFF_CFG_SC_SMMU_TBU0_UTLB_ROUNDROBIN_SHIFT      0
#define HSS2_TOP_SMMU_TBU0_TIEOFF_CFG_SC_SMMU_TBU0_UTLB_ROUNDROBIN_MASK       0x00000001
#define HSS2_TOP_SMMU_TBU0_TIEOFF_CFG_SC_SMMU_TBU0_MAX_TOK_TRANS_SHIFT        1
#define HSS2_TOP_SMMU_TBU0_TIEOFF_CFG_SC_SMMU_TBU0_MAX_TOK_TRANS_MASK         0x0000007e
#define HSS2_TOP_SMMU_TBU0_QCH_CG_CTRL          0x700c
#define HSS2_TOP_SMMU_TBU0_QCH_CG_CTRL_SC_SMMU_TBU0_QACTIVE_CG_THRESH_SHIFT   0
#define HSS2_TOP_SMMU_TBU0_QCH_CG_CTRL_SC_SMMU_TBU0_QACTIVE_CG_THRESH_MASK    0x0000ffff
#define HSS2_TOP_SMMU_TBU0_QCH_CG_CTRL_SC_SMMU_TBU0_QREQN_CG_SET_SHIFT        16
#define HSS2_TOP_SMMU_TBU0_QCH_CG_CTRL_SC_SMMU_TBU0_QREQN_CG_SET_MASK         0x00010000
#define HSS2_TOP_SMMU_TBU0_QCH_CG_CTRL_SC_SMMU_TBU0_QCH_CG_CTRL_EN_SHIFT      17
#define HSS2_TOP_SMMU_TBU0_QCH_CG_CTRL_SC_SMMU_TBU0_QCH_CG_CTRL_EN_MASK       0x00020000
#define HSS2_TOP_SMMU_TBU0_QCH_CG_STATE         0x7010
#define HSS2_TOP_SMMU_TBU0_QCH_CG_STATE_SC_SMMU_TBU0_QCH_CG_STATE_NXT_SHIFT   0
#define HSS2_TOP_SMMU_TBU0_QCH_CG_STATE_SC_SMMU_TBU0_QCH_CG_STATE_NXT_MASK    0x00000003
#define HSS2_TOP_SMMU_TBU0_QCH_CG_STATE_SC_SMMU_TBU0_QCH_CG_STATE_SHIFT       2
#define HSS2_TOP_SMMU_TBU0_QCH_CG_STATE_SC_SMMU_TBU0_QCH_CG_STATE_MASK        0x0000000c
#define HSS2_TOP_SMMU_TBU0_QCH_CG_STATE_SC_SMMU_TBU0_QCTRL_CLKEN_ST_SHIFT     4
#define HSS2_TOP_SMMU_TBU0_QCH_CG_STATE_SC_SMMU_TBU0_QCTRL_CLKEN_ST_MASK      0x00000010
#define HSS2_TOP_SMMU_TBU0_QCH_CG_STATE_SC_SMMU_TBU0_QACTIVE_CG_ST_SHIFT      5
#define HSS2_TOP_SMMU_TBU0_QCH_CG_STATE_SC_SMMU_TBU0_QACTIVE_CG_ST_MASK       0x00000020
#define HSS2_TOP_SMMU_TBU0_QCH_CG_STATE_SC_SMMU_TBU0_QDENY_CG_ST_SHIFT        6
#define HSS2_TOP_SMMU_TBU0_QCH_CG_STATE_SC_SMMU_TBU0_QDENY_CG_ST_MASK         0x00000040
#define HSS2_TOP_SMMU_TBU0_QCH_CG_STATE_SC_SMMU_TBU0_QACCEPTN_CG_ST_SHIFT     7
#define HSS2_TOP_SMMU_TBU0_QCH_CG_STATE_SC_SMMU_TBU0_QACCEPTN_CG_ST_MASK      0x00000080
#define HSS2_TOP_SMMU_TBU0_QCH_CG_STATE_SC_SMMU_TBU0_QREQN_CG_ST_SHIFT        8
#define HSS2_TOP_SMMU_TBU0_QCH_CG_STATE_SC_SMMU_TBU0_QREQN_CG_ST_MASK         0x00000100
#define HSS2_TOP_SMMU_TBU0_QCH_PD_CTRL          0x7014
#define HSS2_TOP_SMMU_TBU0_QCH_PD_CTRL_SC_SMMU_TBU0_QREQN_PD_SHIFT            0
#define HSS2_TOP_SMMU_TBU0_QCH_PD_CTRL_SC_SMMU_TBU0_QREQN_PD_MASK             0x00000001
#define HSS2_TOP_SMMU_TBU0_QCH_PD_STATE         0x7018
#define HSS2_TOP_SMMU_TBU0_QCH_PD_STATE_SC_SMMU_TBU0_QACTIVE_PD_SHIFT         0
#define HSS2_TOP_SMMU_TBU0_QCH_PD_STATE_SC_SMMU_TBU0_QACTIVE_PD_MASK          0x00000001
#define HSS2_TOP_SMMU_TBU0_QCH_PD_STATE_SC_SMMU_TBU0_QDENY_PD_SHIFT           1
#define HSS2_TOP_SMMU_TBU0_QCH_PD_STATE_SC_SMMU_TBU0_QDENY_PD_MASK            0x00000002
#define HSS2_TOP_SMMU_TBU0_QCH_PD_STATE_SC_SMMU_TBU0_QACCEPTN_PD_SHIFT        2
#define HSS2_TOP_SMMU_TBU0_QCH_PD_STATE_SC_SMMU_TBU0_QACCEPTN_PD_MASK         0x00000004
#define HSS2_TOP_SMMU_TBU0_PMU_SNAP_REQ         0x701c
#define HSS2_TOP_SMMU_TBU0_PMU_SNAP_REQ_SC_SMMU_TBU0_PMUSNAPSHOT_REQ_SHIFT    0
#define HSS2_TOP_SMMU_TBU0_PMU_SNAP_REQ_SC_SMMU_TBU0_PMUSNAPSHOT_REQ_MASK     0x00000001
#define HSS2_TOP_SMMU_TBU0_PMU_SNAP_ACK         0x7020
#define HSS2_TOP_SMMU_TBU0_PMU_SNAP_ACK_SC_SMMU_TBU0_PMUSNAPSHOT_ACK_SHIFT    0
#define HSS2_TOP_SMMU_TBU0_PMU_SNAP_ACK_SC_SMMU_TBU0_PMUSNAPSHOT_ACK_MASK     0x00000001
#define HSS2_TOP_SMMU_TBU1_IRPT_CLEAR           0x7800
#define HSS2_TOP_SMMU_TBU1_IRPT_CLEAR_SC_SMMU_TBU1_RAS_IRPT_CLR_SHIFT         0
#define HSS2_TOP_SMMU_TBU1_IRPT_CLEAR_SC_SMMU_TBU1_RAS_IRPT_CLR_MASK          0x00000001
#define HSS2_TOP_SMMU_TBU1_IRPT_CLEAR_SC_SMMU_TBU1_PMU_IRPT_CLR_SHIFT         1
#define HSS2_TOP_SMMU_TBU1_IRPT_CLEAR_SC_SMMU_TBU1_PMU_IRPT_CLR_MASK          0x00000002
#define HSS2_TOP_SMMU_TBU1_IRPT_STATE           0x7804
#define HSS2_TOP_SMMU_TBU1_IRPT_STATE_SC_SMMU_TBU1_RAS_IRPT_ST_SHIFT          0
#define HSS2_TOP_SMMU_TBU1_IRPT_STATE_SC_SMMU_TBU1_RAS_IRPT_ST_MASK           0x00000001
#define HSS2_TOP_SMMU_TBU1_IRPT_STATE_SC_SMMU_TBU1_PMU_IRPT_ST_SHIFT          1
#define HSS2_TOP_SMMU_TBU1_IRPT_STATE_SC_SMMU_TBU1_PMU_IRPT_ST_MASK           0x00000002
#define HSS2_TOP_SMMU_TBU1_TIEOFF_CFG           0x7808
#define HSS2_TOP_SMMU_TBU1_TIEOFF_CFG_SC_SMMU_TBU1_UTLB_ROUNDROBIN_SHIFT      0
#define HSS2_TOP_SMMU_TBU1_TIEOFF_CFG_SC_SMMU_TBU1_UTLB_ROUNDROBIN_MASK       0x00000001
#define HSS2_TOP_SMMU_TBU1_TIEOFF_CFG_SC_SMMU_TBU1_MAX_TOK_TRANS_SHIFT        1
#define HSS2_TOP_SMMU_TBU1_TIEOFF_CFG_SC_SMMU_TBU1_MAX_TOK_TRANS_MASK         0x0000007e
#define HSS2_TOP_SMMU_TBU1_QCH_CG_CTRL          0x780c
#define HSS2_TOP_SMMU_TBU1_QCH_CG_CTRL_SC_SMMU_TBU1_QACTIVE_CG_THRESH_SHIFT   0
#define HSS2_TOP_SMMU_TBU1_QCH_CG_CTRL_SC_SMMU_TBU1_QACTIVE_CG_THRESH_MASK    0x0000ffff
#define HSS2_TOP_SMMU_TBU1_QCH_CG_CTRL_SC_SMMU_TBU1_QREQN_CG_SET_SHIFT        16
#define HSS2_TOP_SMMU_TBU1_QCH_CG_CTRL_SC_SMMU_TBU1_QREQN_CG_SET_MASK         0x00010000
#define HSS2_TOP_SMMU_TBU1_QCH_CG_CTRL_SC_SMMU_TBU1_QCH_CG_CTRL_EN_SHIFT      17
#define HSS2_TOP_SMMU_TBU1_QCH_CG_CTRL_SC_SMMU_TBU1_QCH_CG_CTRL_EN_MASK       0x00020000
#define HSS2_TOP_SMMU_TBU1_QCH_CG_STATE         0x7810
#define HSS2_TOP_SMMU_TBU1_QCH_CG_STATE_SC_SMMU_TBU1_QCH_CG_STATE_NXT_SHIFT   0
#define HSS2_TOP_SMMU_TBU1_QCH_CG_STATE_SC_SMMU_TBU1_QCH_CG_STATE_NXT_MASK    0x00000003
#define HSS2_TOP_SMMU_TBU1_QCH_CG_STATE_SC_SMMU_TBU1_QCH_CG_STATE_SHIFT       2
#define HSS2_TOP_SMMU_TBU1_QCH_CG_STATE_SC_SMMU_TBU1_QCH_CG_STATE_MASK        0x0000000c
#define HSS2_TOP_SMMU_TBU1_QCH_CG_STATE_SC_SMMU_TBU1_QCTRL_CLKEN_ST_SHIFT     4
#define HSS2_TOP_SMMU_TBU1_QCH_CG_STATE_SC_SMMU_TBU1_QCTRL_CLKEN_ST_MASK      0x00000010
#define HSS2_TOP_SMMU_TBU1_QCH_CG_STATE_SC_SMMU_TBU1_QACTIVE_CG_ST_SHIFT      5
#define HSS2_TOP_SMMU_TBU1_QCH_CG_STATE_SC_SMMU_TBU1_QACTIVE_CG_ST_MASK       0x00000020
#define HSS2_TOP_SMMU_TBU1_QCH_CG_STATE_SC_SMMU_TBU1_QDENY_CG_ST_SHIFT        6
#define HSS2_TOP_SMMU_TBU1_QCH_CG_STATE_SC_SMMU_TBU1_QDENY_CG_ST_MASK         0x00000040
#define HSS2_TOP_SMMU_TBU1_QCH_CG_STATE_SC_SMMU_TBU1_QACCEPTN_CG_ST_SHIFT     7
#define HSS2_TOP_SMMU_TBU1_QCH_CG_STATE_SC_SMMU_TBU1_QACCEPTN_CG_ST_MASK      0x00000080
#define HSS2_TOP_SMMU_TBU1_QCH_CG_STATE_SC_SMMU_TBU1_QREQN_CG_ST_SHIFT        8
#define HSS2_TOP_SMMU_TBU1_QCH_CG_STATE_SC_SMMU_TBU1_QREQN_CG_ST_MASK         0x00000100
#define HSS2_TOP_SMMU_TBU1_QCH_PD_CTRL          0x7814
#define HSS2_TOP_SMMU_TBU1_QCH_PD_CTRL_SC_SMMU_TBU1_QREQN_PD_SHIFT            0
#define HSS2_TOP_SMMU_TBU1_QCH_PD_CTRL_SC_SMMU_TBU1_QREQN_PD_MASK             0x00000001
#define HSS2_TOP_SMMU_TBU1_QCH_PD_STATE         0x7818
#define HSS2_TOP_SMMU_TBU1_QCH_PD_STATE_SC_SMMU_TBU1_QACTIVE_PD_SHIFT         0
#define HSS2_TOP_SMMU_TBU1_QCH_PD_STATE_SC_SMMU_TBU1_QACTIVE_PD_MASK          0x00000001
#define HSS2_TOP_SMMU_TBU1_QCH_PD_STATE_SC_SMMU_TBU1_QDENY_PD_SHIFT           1
#define HSS2_TOP_SMMU_TBU1_QCH_PD_STATE_SC_SMMU_TBU1_QDENY_PD_MASK            0x00000002
#define HSS2_TOP_SMMU_TBU1_QCH_PD_STATE_SC_SMMU_TBU1_QACCEPTN_PD_SHIFT        2
#define HSS2_TOP_SMMU_TBU1_QCH_PD_STATE_SC_SMMU_TBU1_QACCEPTN_PD_MASK         0x00000004
#define HSS2_TOP_SMMU_TBU1_PMU_SNAP_REQ         0x781c
#define HSS2_TOP_SMMU_TBU1_PMU_SNAP_REQ_SC_SMMU_TBU1_PMUSNAPSHOT_REQ_SHIFT    0
#define HSS2_TOP_SMMU_TBU1_PMU_SNAP_REQ_SC_SMMU_TBU1_PMUSNAPSHOT_REQ_MASK     0x00000001
#define HSS2_TOP_SMMU_TBU1_PMU_SNAP_ACK         0x7820
#define HSS2_TOP_SMMU_TBU1_PMU_SNAP_ACK_SC_SMMU_TBU1_PMUSNAPSHOT_ACK_SHIFT    0
#define HSS2_TOP_SMMU_TBU1_PMU_SNAP_ACK_SC_SMMU_TBU1_PMUSNAPSHOT_ACK_MASK     0x00000001
#define HSS2_TOP_REGFILE_CGBYPASS               0x7824
#define HSS2_TOP_REGFILE_CGBYPASS_REGFILE_CGBYPASS_SHIFT                      0
#define HSS2_TOP_REGFILE_CGBYPASS_REGFILE_CGBYPASS_MASK                       0x00000001


typedef union {
    unsigned int val;
    struct {
        unsigned int hss2_ns_fw_clear :  1;
        unsigned int reserved_0       : 31;
    } reg;
}hss2_top_ns_firewall_clear_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int hss2_nsfw_nerror    :  1;
        unsigned int hss2_nsfw_fail_nmid :  8;
        unsigned int reserved_0          : 23;
    } reg;
}hss2_top_ns_firewall_dcdr_fail0_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int hss2_nsfw_fail_naddr : 32;
    } reg;
}hss2_top_ns_firewall_dcdr_fail1_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int testpin_sel :  4;
        unsigned int reserved_0  : 28;
    } reg;
}hss2_top_hss2_testpin_sel_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int pcie0_l1ss_state_mask    :  1;
        unsigned int pcie1_l1ss_state_mask    :  1;
        unsigned int emmc_cclk_base_en_n_mask :  1;
        unsigned int emmc_intclk_en_n_mask    :  1;
        unsigned int reserved_0               : 28;
    } reg;
}hss2_top_hss2_doze_mask_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int pcie0_l1ss_status          :  1;
        unsigned int pcie1_l1ss_status          :  1;
        unsigned int emmc_cclk_base_en_n_status :  1;
        unsigned int emmc_intclk_en_n_status    :  1;
        unsigned int reserved_0                 : 28;
    } reg;
}hss2_top_hss2_doze_status_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int hss2_bus_timeout_en :  1;
        unsigned int reserved_0          : 31;
    } reg;
}hss2_top_hss2_bus_ctrl_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int emmc_axi3_ab_busy_status :  1;
        unsigned int reserved_0               : 31;
    } reg;
}hss2_top_emmc_axi3_ab_status_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int emmc_ahb_ab_bus_id : 32;
    } reg;
}hss2_top_emmc_ahb_ab_status0_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int emmc_ahb_ab_mhbusreq :  1;
        unsigned int emmc_ahb_ab_shsplit  : 16;
        unsigned int reserved_0           : 15;
    } reg;
}hss2_top_emmc_ahb_ab_status1_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int hss2_mem_cfg_reg_0 : 32;
    } reg;
}hss2_top_hss2_ram_ctrl_bus_0_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int hss2_mem_cfg_reg_1 : 32;
    } reg;
}hss2_top_hss2_ram_ctrl_bus_1_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int hss2_mem_cfg_reg_2 : 32;
    } reg;
}hss2_top_hss2_ram_ctrl_bus_2_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int top_hss2_128_ndb_mst_autogate_byp :  1;
        unsigned int top_hss2_128_ndb_ost_zero_force   :  1;
        unsigned int top_hss2_128_ndb_slv_autogate_byp :  1;
        unsigned int reserved_0                        : 29;
    } reg;
}hss2_top_top_hss2_128_ndb_cfg0_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int top_hss2_128_ndb_mst_busy :  1;
        unsigned int top_hss2_128_ndb_slv_busy :  1;
        unsigned int reserved_0                : 30;
    } reg;
}hss2_top_top_hss2_128_ndb_cfg1_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int hss2_top_128_ndb_mst_autogate_byp :  1;
        unsigned int hss2_top_128_ndb_ost_zero_force   :  1;
        unsigned int hss2_top_128_ndb_slv_autogate_byp :  1;
        unsigned int reserved_0                        : 29;
    } reg;
}hss2_top_128_ndb_cfg0_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int hss2_top_128_ndb_mst_busy :  1;
        unsigned int hss2_top_128_ndb_slv_busy :  1;
        unsigned int reserved_0                : 30;
    } reg;
}hss2_top_128_ndb_cfg1_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int hss2_top_32_ndb_mst_autogate_byp :  1;
        unsigned int hss2_top_32_ndb_ost_zero_force   :  1;
        unsigned int hss2_top_32_ndb_slv_autogate_byp :  1;
        unsigned int reserved_0                       : 29;
    } reg;
}hss2_top_32_ndb_cfg0_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int hss2_top_32_ndb_mst_busy :  1;
        unsigned int hss2_top_32_ndb_slv_busy :  1;
        unsigned int reserved_0               : 30;
    } reg;
}hss2_top_32_ndb_cfg1_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_pcie0_ns_sid0   :  8;
        unsigned int sc_pcie0_ns_ssid0  :  8;
        unsigned int sc_pcie0_ns_ssidv0 :  1;
        unsigned int reserved_0         : 15;
    } reg;
}hss2_top_smmu_tbu0_ns_id_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_pcie1_ns_sid0   :  8;
        unsigned int sc_pcie1_ns_ssid0  :  8;
        unsigned int sc_pcie1_ns_ssidv0 :  1;
        unsigned int reserved_0         : 15;
    } reg;
}hss2_top_smmu_tbu1_ns_id_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sw_crg_tpc_ocm_addr_range0_32l : 32;
    } reg;
}hss2_top_tpc_normal_crg_config0_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sw_crg_tpc_ocm_addr_range0_32h : 32;
    } reg;
}hss2_top_tpc_normal_crg_config1_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sw_crg_tpc_ocm_addr_range1_32l : 32;
    } reg;
}hss2_top_tpc_normal_crg_config2_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sw_crg_tpc_ocm_addr_range1_32h : 32;
    } reg;
}hss2_top_tpc_normal_crg_config3_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sw_crg_tpc_ocm_addr_range2_32l : 32;
    } reg;
}hss2_top_tpc_normal_crg_config4_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sw_crg_tpc_ocm_addr_range2_32h : 32;
    } reg;
}hss2_top_tpc_normal_crg_config5_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sw_crg_tpc_bwc_dyn_qos4_w_target :  8;
        unsigned int sw_crg_tpc_bwc_dyn_qos5_w_target :  8;
        unsigned int sw_crg_tpc_bwc_dyn_qos6_w_target :  8;
        unsigned int sw_crg_tpc_bwc_dyn_qos7_w_target :  8;
    } reg;
}hss2_top_tpc_normal_crg_config6_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sw_crg_tpc_bwc_dyn_qos0_w_target :  8;
        unsigned int sw_crg_tpc_bwc_dyn_qos1_w_target :  8;
        unsigned int sw_crg_tpc_bwc_dyn_qos2_w_target :  8;
        unsigned int sw_crg_tpc_bwc_dyn_qos3_w_target :  8;
    } reg;
}hss2_top_tpc_normal_crg_config7_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sw_crg_tpc_bwc_dyn_qos4_r_target :  8;
        unsigned int sw_crg_tpc_bwc_dyn_qos5_r_target :  8;
        unsigned int sw_crg_tpc_bwc_dyn_qos6_r_target :  8;
        unsigned int sw_crg_tpc_bwc_dyn_qos7_r_target :  8;
    } reg;
}hss2_top_tpc_normal_crg_config8_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sw_crg_tpc_bwc_dyn_qos0_r_target :  8;
        unsigned int sw_crg_tpc_bwc_dyn_qos1_r_target :  8;
        unsigned int sw_crg_tpc_bwc_dyn_qos2_r_target :  8;
        unsigned int sw_crg_tpc_bwc_dyn_qos3_r_target :  8;
    } reg;
}hss2_top_tpc_normal_crg_config9_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tpc0_sw_crg_tpc_en                    :  1;
        unsigned int tpc0_sw_crg_tpc_bw_counter_en         :  1;
        unsigned int tpc0_sw_crg_tpc_bwc_static_r_en       :  1;
        unsigned int tpc0_sw_crg_tpc_bwc_static_w_en       :  1;
        unsigned int tpc0_sw_crg_tpc_bwc_dyn_r_en          :  1;
        unsigned int tpc0_sw_crg_tpc_bwc_dyn_w_en          :  1;
        unsigned int tpc0_sw_crg_tpc_count_outstanding_en  :  1;
        unsigned int tpc0_sw_crg_tpc_afbc_addr_scramble_en :  1;
        unsigned int tpc0_sw_crg_tpc_count_ar_max          :  7;
        unsigned int reserved_tpc0_cfg0_1                  :  1;
        unsigned int tpc0_sw_crg_tpc_count_aw_max          :  7;
        unsigned int reserved_tpc0_cfg0_0                  :  9;
    } reg;
}hss2_top_tpc0_crg_config0_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tpc0_sw_crg_tpc_bwc_static_r_target :  8;
        unsigned int tpc0_sw_crg_tpc_bwc_static_w_target :  8;
        unsigned int reserved_0                          : 16;
    } reg;
}hss2_top_tpc0_crg_config1_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tpc0_sw_crg_tpc_qos_0   :  4;
        unsigned int tpc0_sw_crg_tpc_qos_1   :  4;
        unsigned int tpc0_sw_crg_tpc_qos_2   :  4;
        unsigned int tpc0_sw_crg_tpc_qos_3   :  4;
        unsigned int tpc0_sw_crg_tpc_qos_4   :  4;
        unsigned int tpc0_sw_crg_tpc_qos_5   :  4;
        unsigned int tpc0_sw_crg_tpc_qos_6   :  4;
        unsigned int tpc0_sw_crg_tpc_qos_7   :  3;
        unsigned int tpc0_sw_crg_tpc_qos_sel :  1;
    } reg;
}hss2_top_tpc0_crg_config2_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tpc0_sw_crg_tpc_bwc_r_sat : 16;
        unsigned int tpc0_sw_crg_tpc_bwc_w_sat : 16;
    } reg;
}hss2_top_tpc0_crg_config3_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tpc0_sw_crg_tpc_w_byte_counter_all : 32;
    } reg;
}hss2_top_tpc0_crg_status0_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tpc0_sw_crg_tpc_r_byte_counter_all : 32;
    } reg;
}hss2_top_tpc0_crg_status1_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tpc0_sw_crg_tpc_cycle_counter_all : 32;
    } reg;
}hss2_top_tpc0_crg_status2_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tpc1_sw_crg_tpc_en                    :  1;
        unsigned int tpc1_sw_crg_tpc_bw_counter_en         :  1;
        unsigned int tpc1_sw_crg_tpc_bwc_static_r_en       :  1;
        unsigned int tpc1_sw_crg_tpc_bwc_static_w_en       :  1;
        unsigned int tpc1_sw_crg_tpc_bwc_dyn_r_en          :  1;
        unsigned int tpc1_sw_crg_tpc_bwc_dyn_w_en          :  1;
        unsigned int tpc1_sw_crg_tpc_count_outstanding_en  :  1;
        unsigned int tpc1_sw_crg_tpc_afbc_addr_scramble_en :  1;
        unsigned int tpc1_sw_crg_tpc_count_ar_max          :  7;
        unsigned int reserved_tpc1_cfg0_1                  :  1;
        unsigned int tpc1_sw_crg_tpc_count_aw_max          :  7;
        unsigned int reserved_tpc1_cfg0_0                  :  9;
    } reg;
}hss2_top_tpc1_crg_config0_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tpc1_sw_crg_tpc_bwc_static_r_target :  8;
        unsigned int tpc1_sw_crg_tpc_bwc_static_w_target :  8;
        unsigned int reserved_0                          : 16;
    } reg;
}hss2_top_tpc1_crg_config1_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tpc1_sw_crg_tpc_qos_0   :  4;
        unsigned int tpc1_sw_crg_tpc_qos_1   :  4;
        unsigned int tpc1_sw_crg_tpc_qos_2   :  4;
        unsigned int tpc1_sw_crg_tpc_qos_3   :  4;
        unsigned int tpc1_sw_crg_tpc_qos_4   :  4;
        unsigned int tpc1_sw_crg_tpc_qos_5   :  4;
        unsigned int tpc1_sw_crg_tpc_qos_6   :  4;
        unsigned int tpc1_sw_crg_tpc_qos_7   :  3;
        unsigned int tpc1_sw_crg_tpc_qos_sel :  1;
    } reg;
}hss2_top_tpc1_crg_config2_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tpc1_sw_crg_tpc_bwc_r_sat : 16;
        unsigned int tpc1_sw_crg_tpc_bwc_w_sat : 16;
    } reg;
}hss2_top_tpc1_crg_config3_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tpc1_sw_crg_tpc_w_byte_counter_all : 32;
    } reg;
}hss2_top_tpc1_crg_status0_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tpc1_sw_crg_tpc_r_byte_counter_all : 32;
    } reg;
}hss2_top_tpc1_crg_status1_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tpc1_sw_crg_tpc_cycle_counter_all : 32;
    } reg;
}hss2_top_tpc1_crg_status2_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tpc2_sw_crg_tpc_en                    :  1;
        unsigned int tpc2_sw_crg_tpc_bw_counter_en         :  1;
        unsigned int tpc2_sw_crg_tpc_bwc_static_r_en       :  1;
        unsigned int tpc2_sw_crg_tpc_bwc_static_w_en       :  1;
        unsigned int tpc2_sw_crg_tpc_bwc_dyn_r_en          :  1;
        unsigned int tpc2_sw_crg_tpc_bwc_dyn_w_en          :  1;
        unsigned int tpc2_sw_crg_tpc_count_outstanding_en  :  1;
        unsigned int tpc2_sw_crg_tpc_afbc_addr_scramble_en :  1;
        unsigned int tpc2_sw_crg_tpc_count_ar_max          :  7;
        unsigned int reserved_tpc2_cfg0_1                  :  1;
        unsigned int tpc2_sw_crg_tpc_count_aw_max          :  7;
        unsigned int reserved_tpc2_cfg0_0                  :  9;
    } reg;
}hss2_top_tpc2_crg_config0_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tpc2_sw_crg_tpc_bwc_static_r_target :  8;
        unsigned int tpc2_sw_crg_tpc_bwc_static_w_target :  8;
        unsigned int reserved_0                          : 16;
    } reg;
}hss2_top_tpc2_crg_config1_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tpc2_sw_crg_tpc_qos_0   :  4;
        unsigned int tpc2_sw_crg_tpc_qos_1   :  4;
        unsigned int tpc2_sw_crg_tpc_qos_2   :  4;
        unsigned int tpc2_sw_crg_tpc_qos_3   :  4;
        unsigned int tpc2_sw_crg_tpc_qos_4   :  4;
        unsigned int tpc2_sw_crg_tpc_qos_5   :  4;
        unsigned int tpc2_sw_crg_tpc_qos_6   :  4;
        unsigned int tpc2_sw_crg_tpc_qos_7   :  3;
        unsigned int tpc2_sw_crg_tpc_qos_sel :  1;
    } reg;
}hss2_top_tpc2_crg_config2_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tpc2_sw_crg_tpc_bwc_r_sat : 16;
        unsigned int tpc2_sw_crg_tpc_bwc_w_sat : 16;
    } reg;
}hss2_top_tpc2_crg_config3_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tpc2_sw_crg_tpc_w_byte_counter_all : 32;
    } reg;
}hss2_top_tpc2_crg_status0_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tpc2_sw_crg_tpc_r_byte_counter_all : 32;
    } reg;
}hss2_top_tpc2_crg_status1_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tpc2_sw_crg_tpc_cycle_counter_all : 32;
    } reg;
}hss2_top_tpc2_crg_status2_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int hss2_ndb_mst_dfx_0 :  5;
        unsigned int hss2_ndb_slv_dfx_0 :  5;
        unsigned int hss2_ndb_mst_dfx_1 :  5;
        unsigned int hss2_ndb_slv_dfx_1 :  5;
        unsigned int hss2_ndb_mst_dfx_2 :  5;
        unsigned int hss2_ndb_slv_dfx_2 :  5;
        unsigned int reserved_0         :  2;
    } reg;
}hss2_top_ndb_async_dfx_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_pcie0_s_sid0   :  8;
        unsigned int sc_pcie0_s_ssid0  :  8;
        unsigned int sc_pcie0_s_ssidv0 :  1;
        unsigned int reserved_0        : 15;
    } reg;
}hss2_top_smmu_tbu0_s_id_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_pcie1_s_sid0   :  8;
        unsigned int sc_pcie1_s_ssid0  :  8;
        unsigned int sc_pcie1_s_ssidv0 :  1;
        unsigned int reserved_0        : 15;
    } reg;
}hss2_top_smmu_tbu1_s_id_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tcu_s_irpt_clr :  3;
        unsigned int reserved_0             : 29;
    } reg;
}hss2_top_smmu_tcu_s_irpt_clear_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tcu_s_irpt_st :  3;
        unsigned int reserved_0            : 29;
    } reg;
}hss2_top_smmu_tcu_s_irpt_state_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tcu_sec_override :  1;
        unsigned int reserved_0               : 31;
    } reg;
}hss2_top_smmu_tcu_s_tieoff_cfg_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tcu_ras_irpt_clr :  1;
        unsigned int sc_smmu_tcu_pmu_irpt_clr :  1;
        unsigned int sc_smmu_tcu_ns_irpt_clr  :  3;
        unsigned int reserved_0               : 27;
    } reg;
}hss2_top_smmu_tcu_irpt_clear_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tcu_pmu_irpt_st :  1;
        unsigned int sc_smmu_tcu_ras_irpt_st :  1;
        unsigned int sc_smmu_tcu_ns_irpt_st  :  3;
        unsigned int reserved_0              : 27;
    } reg;
}hss2_top_smmu_tcu_irpt_state_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tcu_qactive_cg_thresh : 16;
        unsigned int sc_smmu_tcu_qreqn_cg_set      :  1;
        unsigned int sc_smmu_tcu_qch_cg_ctrl_en    :  1;
        unsigned int reserved_0                    : 14;
    } reg;
}hss2_top_smmu_tcu_qch_cg_ctrl_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tcu_qch_cg_state_nxt :  2;
        unsigned int sc_smmu_tcu_qch_cg_state     :  2;
        unsigned int sc_smmu_tcu_qctrl_clken_st   :  1;
        unsigned int sc_smmu_tcu_qactive_cg_st    :  1;
        unsigned int sc_smmu_tcu_qdeny_cg_st      :  1;
        unsigned int sc_smmu_tcu_qacceptn_cg_st   :  1;
        unsigned int sc_smmu_tcu_qreqn_cg_st      :  1;
        unsigned int reserved_0                   : 23;
    } reg;
}hss2_top_smmu_tcu_qch_cg_state_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tcu_qreqn_pd :  1;
        unsigned int reserved_0           : 31;
    } reg;
}hss2_top_smmu_tcu_qch_pd_ctrl_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tcu_qactive_pd  :  1;
        unsigned int sc_smmu_tcu_qdeny_pd    :  1;
        unsigned int sc_smmu_tcu_qacceptn_pd :  1;
        unsigned int reserved_0              : 29;
    } reg;
}hss2_top_smmu_tcu_qch_pd_state_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tcu_pmusnapshot_req :  1;
        unsigned int reserved_0                  : 31;
    } reg;
}hss2_top_smmu_tcu_pmu_snap_req_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tcu_pmusnapshot_ack :  1;
        unsigned int reserved_0                  : 31;
    } reg;
}hss2_top_smmu_tcu_pmu_snap_ack_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tbu0_sec_override :  1;
        unsigned int reserved_0                : 31;
    } reg;
}hss2_top_smmu_tbu0_s_tieoff_cfg_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tbu1_sec_override :  1;
        unsigned int reserved_0                : 31;
    } reg;
}hss2_top_smmu_tbu1_s_tieoff_cfg_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tbu0_ras_irpt_clr :  1;
        unsigned int sc_smmu_tbu0_pmu_irpt_clr :  1;
        unsigned int reserved_0                : 30;
    } reg;
}hss2_top_smmu_tbu0_irpt_clear_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tbu0_ras_irpt_st :  1;
        unsigned int sc_smmu_tbu0_pmu_irpt_st :  1;
        unsigned int reserved_0               : 30;
    } reg;
}hss2_top_smmu_tbu0_irpt_state_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tbu0_utlb_roundrobin :  1;
        unsigned int sc_smmu_tbu0_max_tok_trans   :  6;
        unsigned int reserved_0                   : 25;
    } reg;
}hss2_top_smmu_tbu0_tieoff_cfg_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tbu0_qactive_cg_thresh : 16;
        unsigned int sc_smmu_tbu0_qreqn_cg_set      :  1;
        unsigned int sc_smmu_tbu0_qch_cg_ctrl_en    :  1;
        unsigned int reserved_0                     : 14;
    } reg;
}hss2_top_smmu_tbu0_qch_cg_ctrl_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tbu0_qch_cg_state_nxt :  2;
        unsigned int sc_smmu_tbu0_qch_cg_state     :  2;
        unsigned int sc_smmu_tbu0_qctrl_clken_st   :  1;
        unsigned int sc_smmu_tbu0_qactive_cg_st    :  1;
        unsigned int sc_smmu_tbu0_qdeny_cg_st      :  1;
        unsigned int sc_smmu_tbu0_qacceptn_cg_st   :  1;
        unsigned int sc_smmu_tbu0_qreqn_cg_st      :  1;
        unsigned int reserved_0                    : 23;
    } reg;
}hss2_top_smmu_tbu0_qch_cg_state_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tbu0_qreqn_pd :  1;
        unsigned int reserved_0            : 31;
    } reg;
}hss2_top_smmu_tbu0_qch_pd_ctrl_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tbu0_qactive_pd  :  1;
        unsigned int sc_smmu_tbu0_qdeny_pd    :  1;
        unsigned int sc_smmu_tbu0_qacceptn_pd :  1;
        unsigned int reserved_0               : 29;
    } reg;
}hss2_top_smmu_tbu0_qch_pd_state_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tbu0_pmusnapshot_req :  1;
        unsigned int reserved_0                   : 31;
    } reg;
}hss2_top_smmu_tbu0_pmu_snap_req_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tbu0_pmusnapshot_ack :  1;
        unsigned int reserved_0                   : 31;
    } reg;
}hss2_top_smmu_tbu0_pmu_snap_ack_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tbu1_ras_irpt_clr :  1;
        unsigned int sc_smmu_tbu1_pmu_irpt_clr :  1;
        unsigned int reserved_0                : 30;
    } reg;
}hss2_top_smmu_tbu1_irpt_clear_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tbu1_ras_irpt_st :  1;
        unsigned int sc_smmu_tbu1_pmu_irpt_st :  1;
        unsigned int reserved_0               : 30;
    } reg;
}hss2_top_smmu_tbu1_irpt_state_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tbu1_utlb_roundrobin :  1;
        unsigned int sc_smmu_tbu1_max_tok_trans   :  6;
        unsigned int reserved_0                   : 25;
    } reg;
}hss2_top_smmu_tbu1_tieoff_cfg_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tbu1_qactive_cg_thresh : 16;
        unsigned int sc_smmu_tbu1_qreqn_cg_set      :  1;
        unsigned int sc_smmu_tbu1_qch_cg_ctrl_en    :  1;
        unsigned int reserved_0                     : 14;
    } reg;
}hss2_top_smmu_tbu1_qch_cg_ctrl_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tbu1_qch_cg_state_nxt :  2;
        unsigned int sc_smmu_tbu1_qch_cg_state     :  2;
        unsigned int sc_smmu_tbu1_qctrl_clken_st   :  1;
        unsigned int sc_smmu_tbu1_qactive_cg_st    :  1;
        unsigned int sc_smmu_tbu1_qdeny_cg_st      :  1;
        unsigned int sc_smmu_tbu1_qacceptn_cg_st   :  1;
        unsigned int sc_smmu_tbu1_qreqn_cg_st      :  1;
        unsigned int reserved_0                    : 23;
    } reg;
}hss2_top_smmu_tbu1_qch_cg_state_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tbu1_qreqn_pd :  1;
        unsigned int reserved_0            : 31;
    } reg;
}hss2_top_smmu_tbu1_qch_pd_ctrl_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tbu1_qactive_pd  :  1;
        unsigned int sc_smmu_tbu1_qdeny_pd    :  1;
        unsigned int sc_smmu_tbu1_qacceptn_pd :  1;
        unsigned int reserved_0               : 29;
    } reg;
}hss2_top_smmu_tbu1_qch_pd_state_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tbu1_pmusnapshot_req :  1;
        unsigned int reserved_0                   : 31;
    } reg;
}hss2_top_smmu_tbu1_pmu_snap_req_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_smmu_tbu1_pmusnapshot_ack :  1;
        unsigned int reserved_0                   : 31;
    } reg;
}hss2_top_smmu_tbu1_pmu_snap_ack_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int regfile_cgbypass :  1;
        unsigned int reserved_0       : 31;
    } reg;
}hss2_top_regfile_cgbypass_t;

#endif
