// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (C) 2022-2025, X-Ring technologies Inc., All rights reserved.
 */

#ifndef _INTR_ACPU_H_
#define _INTR_ACPU_H_

#define INTR_SPI_BASE                    32

#define INTR_RAS_FAULT_HANDLING_CORE0    (362 + INTR_SPI_BASE)
#define INTR_RAS_FAULT_HANDLING_CORE1    (363 + INTR_SPI_BASE)
#define INTR_RAS_FAULT_HANDLING_CORE2    (364 + INTR_SPI_BASE)
#define INTR_RAS_FAULT_HANDLING_CORE3    (365 + INTR_SPI_BASE)
#define INTR_RAS_FAULT_HANDLING_CORE4    (366 + INTR_SPI_BASE)
#define INTR_RAS_FAULT_HANDLING_CORE5    (367 + INTR_SPI_BASE)
#define INTR_RAS_FAULT_HANDLING_CORE6    (368 + INTR_SPI_BASE)
#define INTR_RAS_FAULT_HANDLING_CORE7    (369 + INTR_SPI_BASE)
#define INTR_RAS_FAULT_HANDLING_CORE8    (370 + INTR_SPI_BASE)
#define INTR_RAS_FAULT_HANDLING_CORE9    (371 + INTR_SPI_BASE)
#define INTR_RAS_FAULT_HANDLING_COMPLEX  (372 + INTR_SPI_BASE)
#define INTR_RAS_FAULT_HANDLING_DSU      (523 + INTR_SPI_BASE)

#define INTR_RAS_ERR_RECOVERY_CORE0      (374 + INTR_SPI_BASE)
#define INTR_RAS_ERR_RECOVERY_CORE1      (375 + INTR_SPI_BASE)
#define INTR_RAS_ERR_RECOVERY_CORE2      (376 + INTR_SPI_BASE)
#define INTR_RAS_ERR_RECOVERY_CORE3      (377 + INTR_SPI_BASE)
#define INTR_RAS_ERR_RECOVERY_CORE4      (378 + INTR_SPI_BASE)
#define INTR_RAS_ERR_RECOVERY_CORE5      (379 + INTR_SPI_BASE)
#define INTR_RAS_ERR_RECOVERY_CORE6      (380 + INTR_SPI_BASE)
#define INTR_RAS_ERR_RECOVERY_CORE7      (520 + INTR_SPI_BASE)
#define INTR_RAS_ERR_RECOVERY_CORE8      (521 + INTR_SPI_BASE)
#define INTR_RAS_ERR_RECOVERY_CORE9      (522 + INTR_SPI_BASE)
#define INTR_RAS_ERR_RECOVERY_COMPLEX    (373 + INTR_SPI_BASE)
#define INTR_RAS_ERR_RECOVERY_DSU        (524 + INTR_SPI_BASE)

#define INTR_RAS_CRITICAL_ERR_DSU        (525 + INTR_SPI_BASE)

#endif 
