// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (C) 2022-2025, X-Ring technologies Inc., All rights reserved.
 */


#ifndef __IPC_RESOURCE_H__
#define __IPC_RESOURCE_H__

#define IPC_GENE_ACK			(0)
#define IPC_FAST_ACK			(1)

#define IPC_PERI                        (0)
#define IPC_LPIS                        (1)

#define IPC_PRIV_MAILBOX                (0)
#define IPC_COM_MAILBOX                 (1)




#define IPC_CHN_PERI_NS0_LP_AP_0	(0)
#define IPC_CHN_PERI_NS0_LP_AP_1	(1)
#define IPC_CHN_PERI_NS0_ADSP_AP_0	(2)
#define IPC_CHN_PERI_NS0_SH_AP_0	(3)
#define IPC_CHN_PERI_NS0_ISP_AP_0	(4)
#define IPC_CHN_PERI_NS0_LP_AP_2	(5)
#define IPC_CHN_PERI_NS0_LP_AP_3	(6)
#define IPC_CHN_PERI_NS0_RESV_AP_0	(7)
#define IPC_CHN_PERI_NS0_RESV_AP_1	(8)

#define IPC_CHN_PERI_NS0_AP_SH_0	(9)
#define IPC_CHN_PERI_NS0_RESV_SH_0	(10)
#define IPC_CHN_PERI_NS0_RESV_SH_1	(11)
#define IPC_CHN_PERI_NS0_RESV_SH_2	(12)
#define IPC_CHN_PERI_NS0_RESV_SH_3	(13)

#define IPC_CHN_PERI_NS0_AP_LP_0	(14)
#define IPC_CHN_PERI_NS0_RESV_LP_0	(15)
#define IPC_CHN_PERI_NS0_AP_LP_1	(16)
#define IPC_CHN_PERI_NS0_AP_LP_2	(17)
#define IPC_CHN_PERI_NS0_AP_LP_3	(18)
#define IPC_CHN_PERI_NS0_RESV_LP_1	(19)
#define IPC_CHN_PERI_NS0_RESV_LP_2	(20)
#define IPC_CHN_PERI_NS0_RESV_LP_3	(21)
#define IPC_CHN_PERI_NS0_RESV_LP_4	(22)

#define IPC_CHN_PERI_NS0_AP_ADSP_0	(23)
#define IPC_CHN_PERI_NS0_RESV_ADSP_0	(24)
#define IPC_CHN_PERI_NS0_RESV_ADSP_1	(25)

#define IPC_CHN_PERI_NS0_AP_ISP_0	(26)
#define IPC_CHN_PERI_NS0_RESV_ISP_0	(27)
#define IPC_CHN_PERI_NS0_RESV_ISP_1	(28)
#define IPC_CHN_PERI_NS0_RESV_ISP_2	(29)



#define IPC_CHN_PERI_NS1_AP_XCPU_0	(0)
#define IPC_CHN_PERI_NS1_AP_XCPU_1	(1)
#define IPC_CHN_PERI_NS1_AP_XCPU_2	(2)
#define IPC_CHN_PERI_NS1_RESV_XCPU_0	(3)

#define IPC_CHN_PERI_NS1_AP_XDDR_0	(4)
#define IPC_CHN_PERI_NS1_RESV_XDDR_0	(5)

#define IPC_CHN_PERI_NS1_XRSE_AP_0	(6)

#define IPC_CHN_PERI_NS1_AP_XRSE_0	(7)
#define IPC_CHN_PERI_NS1_RESV_XRSE_0	(8)

#define IPC_CHN_PERI_NS1_COMMON_0	(9)
#define IPC_CHN_PERI_NS1_COMMON_1	(10)
#define IPC_CHN_PERI_NS1_COMMON_2	(11)

#define IPC_CHN_PERI_NS1_XCPU_AP_0	(12)
#define IPC_CHN_PERI_NS1_XCPU_AP_1	(13)
#define IPC_CHN_PERI_NS1_XCPU_AP_2	(14)
#define IPC_CHN_PERI_NS1_RESV_AP_0	(15)
#define IPC_CHN_PERI_NS1_RESV_AP_1	(16)
#define IPC_CHN_PERI_NS1_XDDR_AP_0	(17)



#define IPC_CHN_AO_NS_SH_AP_0		(0)
#define IPC_CHN_AO_NS_SH_AP_1		(1)
#define IPC_CHN_AO_NS_SH_AP_2		(2)
#define IPC_CHN_AO_NS_SH_AP_3		(3)
#define IPC_CHN_AO_NS_ADSP_AP_0		(4)
#define IPC_CHN_AO_NS_SH_AP_4		(5)
#define IPC_CHN_AO_NS_SH_AP_5		(6)

#define IPC_CHN_AO_NS_AP_SH_0		(7)
#define IPC_CHN_AO_NS_AP_SH_1		(8)
#define IPC_CHN_AO_NS_ISP_SH_0		(9)
#define IPC_CHN_AO_NS_AP_SH_2		(10)
#define IPC_CHN_AO_NS_ADSP_SH_0		(11)
#define IPC_CHN_AO_NS_AP_SH_3		(12)

#define IPC_CHN_AO_NS_RESV_LP_0		(13)

#define IPC_CHN_AO_NS_SH_ADSP_0		(14)
#define IPC_CHN_AO_NS_RESV_ADSP_0	(15)

#define IPC_CHN_AO_NS_SH_ISP_0		(16)

#define IPC_CHN_AO_NS_COMMON_0		(17)
#define IPC_CHN_AO_NS_COMMON_1		(18)
#define IPC_CHN_AO_NS_COMMON_2		(19)

#define IPC_CHN_AO_NS_AP_ADSP_0		(20)



#define IPC_CHN_PERI_S_SH_AP_0		(0)
#define IPC_CHN_PERI_S_LP_AP_0		(1)
#define IPC_CHN_PERI_S_XCPU_AP_0	(2)
#define IPC_CHN_PERI_S_XCPU_AP_1	(3)

#define IPC_CHN_PERI_S_RESV_SH_0	(4)
#define IPC_CHN_PERI_S_RESV_SH_1	(5)
#define IPC_CHN_PERI_S_RESV_SH_2	(6)

#define IPC_CHN_PERI_S_AP_XCPU_0	(7)
#define IPC_CHN_PERI_S_AP_XCPU_1	(8)
#define IPC_CHN_PERI_S_AP_XCPU_2	(9)
#define IPC_CHN_PERI_S_LP_XCPU_0	(10)
#define IPC_CHN_PERI_S_RESV_XCPU_0	(11)
#define IPC_CHN_PERI_S_AP_XCPU_4	(12)
#define IPC_CHN_PERI_S_XDDR_XCPU_0	(13)
#define IPC_CHN_PERI_S_RESV_XRCTL_1	(14)

#define IPC_CHN_PERI_S_LP_XDDR_0	(15)
#define IPC_CHN_PERI_S_XCPU_XDDR_0	(16)
#define IPC_CHN_PERI_S_RESV_XDDR_0	(17)

#define IPC_CHN_PERI_S_XCPU_LP_0	(18)
#define IPC_CHN_PERI_S_RESV_LP_0	(19)
#define IPC_CHN_PERI_S_AP_LP_0		(20)
#define IPC_CHN_PERI_S_RESV_LP_1	(21)
#define IPC_CHN_PERI_S_XDDR_LP_0	(22)

#define IPC_CHN_PERI_S_COMMON_0		(23)
#define IPC_CHN_PERI_S_COMMON_1		(24)

#define IPC_CHN_PERI_S_XCPU_AP_2	(25)
#define IPC_CHN_PERI_S_XCPU_AP_3	(26)
#define IPC_CHN_PERI_S_RESV_AP_0	(27)
#define IPC_CHN_PERI_S_RESV_AP_1	(28)
#define IPC_CHN_PERI_S_RESV_AP_2	(29)



#define IPC_CHN_AO_S_SH_AP_0		(0)
#define IPC_CHN_AO_S_RESV_AP_0		(1)
#define IPC_CHN_AO_S_RESV_AP_1		(2)
#define IPC_CHN_AO_S_RESV_AP_2		(3)

#define IPC_CHN_AO_S_LP_SH_0		(4)
#define IPC_CHN_AO_S_LP_SH_1		(5)
#define IPC_CHN_AO_S_AP_SH_0		(6)
#define IPC_CHN_AO_S_ADSP_SH_0		(7)
#define IPC_CHN_AO_S_RESV_SH_0		(8)

#define IPC_CHN_AO_S_SH_LP_0		(9)
#define IPC_CHN_AO_S_SH_LP_1		(10)
#define IPC_CHN_AO_S_RESV_LP_0		(11)
#define IPC_CHN_AO_S_RESV_LP_1		(12)

#define IPC_CHN_AO_S_SH_ADSP_0		(13)

#define IPC_CHN_AO_S_COMMON_0		(14)
#define IPC_CHN_AO_S_COMMON_1		(15)
#define IPC_CHN_AO_S_COMMON_2		(16)
#define IPC_CHN_AO_S_COMMON_3		(17)


#define IPC_CHN_XRSE0_AP_XRSE_TEE		(0)
#define IPC_CHN_XRSE0_AP_XRSE_BL31		(1)
#define IPC_CHN_XRSE0_LP_XRSE			(2)
#define IPC_CHN_XRSE0_SH_XRSE			(3)
#define IPC_CHN_XRSE0_AP_XRSE_KERNEL		(4)
#define IPC_CHN_XRSE0_XRSE_AP_TEE		(5)
#define IPC_CHN_XRSE0_XRSE_AP_BL31		(6)
#define IPC_CHN_XRSE0_XRSE_LP			(7)
#define IPC_CHN_XRSE0_XRSE_SH			(8)
#define IPC_CHN_XRSE0_XRSE_AP_KERNEL		(9)


#define IPC_CHN_NPU_S_NPU_SH			(0)
#define IPC_CHN_NPU_S_SH_NPU			(4)


#define IPC_CHN_NPU_NS_NPU_SH			(0)
#define IPC_CHN_NPU_NS_SH_NPU			(6)




#define IPC_MBOX_PERI_NS0_AP_START	(0)
#define IPC_MBOX_PERI_NS0_AP(n)		(IPC_MBOX_PERI_NS0_AP_START + n)
#define IPC_MBOX_PERI_NS0_AP_NUM	(9)
#define IPC_MBOX_PERI_NS0_AP_END	(IPC_MBOX_PERI_NS0_AP_START + IPC_MBOX_PERI_NS0_AP_NUM - 1)

#define IPC_MBOX_PERI_NS0_LP_START	(IPC_MBOX_PERI_NS0_AP_END + 1)
#define IPC_MBOX_PERI_NS0_LP(n)		(IPC_MBOX_PERI_NS0_LP_START + n)
#define IPC_MBOX_PERI_NS0_LP_NUM	(6)
#define IPC_MBOX_PERI_NS0_LP_END	(IPC_MBOX_PERI_NS0_LP_START + IPC_MBOX_PERI_NS0_LP_NUM - 1)

#define IPC_MBOX_PERI_NS0_SH_START	(IPC_MBOX_PERI_NS0_LP_END + 1)
#define IPC_MBOX_PERI_NS0_SH(n)		(IPC_MBOX_PERI_NS0_SH_START + n)
#define IPC_MBOX_PERI_NS0_SH_NUM	(3)
#define IPC_MBOX_PERI_NS0_SH_END	(IPC_MBOX_PERI_NS0_SH_START + IPC_MBOX_PERI_NS0_SH_NUM - 1)

#define IPC_MBOX_PERI_NS0_ADSP_START	(IPC_MBOX_PERI_NS0_SH_END + 1)
#define IPC_MBOX_PERI_NS0_ADSP(n)	(IPC_MBOX_PERI_NS0_ADSP_START + n)
#define IPC_MBOX_PERI_NS0_ADSP_NUM	(2)
#define IPC_MBOX_PERI_NS0_ADSP_END	(IPC_MBOX_PERI_NS0_ADSP_START + IPC_MBOX_PERI_NS0_ADSP_NUM - 1)

#define IPC_MBOX_PERI_NS0_ISP_START	(IPC_MBOX_PERI_NS0_ADSP_END + 1)
#define IPC_MBOX_PERI_NS0_ISP(n)	(IPC_MBOX_PERI_NS0_ISP_START + n)
#define IPC_MBOX_PERI_NS0_ISP_NUM	(3)
#define IPC_MBOX_PERI_NS0_ISP_END	(IPC_MBOX_PERI_NS0_ISP_START + IPC_MBOX_PERI_NS0_ISP_NUM - 1)



#define IPC_MBOX_PERI_NS1_AP_START	(0)
#define IPC_MBOX_PERI_NS1_AP(n)		(IPC_MBOX_PERI_NS1_AP_START + n)
#define IPC_MBOX_PERI_NS1_AP_NUM	(7)
#define IPC_MBOX_PERI_NS1_AP_END	(IPC_MBOX_PERI_NS1_AP_START + IPC_MBOX_PERI_NS1_AP_NUM - 1)

#define IPC_MBOX_PERI_NS1_XRSE_START	(IPC_MBOX_PERI_NS1_AP_END + 1)
#define IPC_MBOX_PERI_NS1_XRSE(n)	(IPC_MBOX_PERI_NS1_XRSE_START + n)
#define IPC_MBOX_PERI_NS1_XRSE_NUM	(2)
#define IPC_MBOX_PERI_NS1_XRSE_END	(IPC_MBOX_PERI_NS1_XRSE_START + IPC_MBOX_PERI_NS1_XRSE_NUM - 1)

#define IPC_MBOX_PERI_NS1_XCPU_START	(IPC_MBOX_PERI_NS1_XRSE_END + 1)
#define IPC_MBOX_PERI_NS1_XCPU(n)	(IPC_MBOX_PERI_NS1_XCPU_START + n)
#define IPC_MBOX_PERI_NS1_XCPU_NUM	(4)
#define IPC_MBOX_PERI_NS1_XCPU_END	(IPC_MBOX_PERI_NS1_XCPU_START + IPC_MBOX_PERI_NS1_XCPU_NUM - 1)

#define IPC_MBOX_PERI_NS1_XDDR_START	(IPC_MBOX_PERI_NS1_XCPU_END + 1)
#define IPC_MBOX_PERI_NS1_XDDR(n)	(IPC_MBOX_PERI_NS1_XDDR_START + n)
#define IPC_MBOX_PERI_NS1_XDDR_NUM	(2)
#define IPC_MBOX_PERI_NS1_XDDR_END	(IPC_MBOX_PERI_NS1_XDDR_START + IPC_MBOX_PERI_NS1_XDDR_NUM - 1)



#define IPC_MBOX_AO_NS_AP_START		(0)
#define IPC_MBOX_AO_NS_AP(n)		(IPC_MBOX_AO_NS_AP_START + n)
#define IPC_MBOX_AO_NS_AP_NUM		(7)
#define IPC_MBOX_AO_NS_AP_END		(IPC_MBOX_AO_NS_AP_START + IPC_MBOX_AO_NS_AP_NUM - 1)

#define IPC_MBOX_AO_NS_SH_START		(IPC_MBOX_AO_NS_AP_END + 1)
#define IPC_MBOX_AO_NS_SH(n)		(IPC_MBOX_AO_NS_SH_START + n)
#define IPC_MBOX_AO_NS_SH_NUM		(10)
#define IPC_MBOX_AO_NS_SH_END		(IPC_MBOX_AO_NS_SH_START + IPC_MBOX_AO_NS_SH_NUM - 1)

#define IPC_MBOX_AO_NS_ADSP_START	(IPC_MBOX_AO_NS_SH_END + 1)
#define IPC_MBOX_AO_NS_ADSP(n)		(IPC_MBOX_AO_NS_ADSP_START + n)
#define IPC_MBOX_AO_NS_ADSP_NUM		(4)
#define IPC_MBOX_AO_NS_ADSP_END		(IPC_MBOX_AO_NS_ADSP_START + IPC_MBOX_AO_NS_ADSP_NUM - 1)

#define IPC_MBOX_AO_NS_ISP_START	(IPC_MBOX_AO_NS_ADSP_END + 1)
#define IPC_MBOX_AO_NS_ISP(n)		(IPC_MBOX_AO_NS_ISP_START + n)
#define IPC_MBOX_AO_NS_ISP_NUM		(2)
#define IPC_MBOX_AO_NS_ISP_END		(IPC_MBOX_AO_NS_ISP_START + IPC_MBOX_AO_NS_ISP_NUM - 1)

#define IPC_MBOX_AO_NS_LP_START		(IPC_MBOX_AO_NS_ISP_END + 1)
#define IPC_MBOX_AO_NS_LP(n)		(IPC_MBOX_AO_NS_LP_START + n)
#define IPC_MBOX_AO_NS_LP_NUM		(1)
#define IPC_MBOX_AO_NS_LP_END		(IPC_MBOX_AO_NS_LP_START + IPC_MBOX_AO_NS_LP_NUM - 1)



#define IPC_MBOX_PERI_S_AP_START	(0)
#define IPC_MBOX_PERI_S_AP(n)		(IPC_MBOX_PERI_S_AP_START + n)
#define IPC_MBOX_PERI_S_AP_NUM		(8)
#define IPC_MBOX_PERI_S_AP_END		(IPC_MBOX_PERI_S_AP_START + IPC_MBOX_PERI_S_AP_NUM - 1)

#define IPC_MBOX_PERI_S_LP_START	(IPC_MBOX_PERI_S_AP_END + 1)
#define IPC_MBOX_PERI_S_LP(n)		(IPC_MBOX_PERI_S_LP_START + n)
#define IPC_MBOX_PERI_S_LP_NUM		(5)
#define IPC_MBOX_PERI_S_LP_END		(IPC_MBOX_PERI_S_LP_START + IPC_MBOX_PERI_S_LP_NUM - 1)

#define IPC_MBOX_PERI_S_SH_START	(IPC_MBOX_PERI_S_LP_END + 1)
#define IPC_MBOX_PERI_S_SH(n)		(IPC_MBOX_PERI_S_SH_START + n)
#define IPC_MBOX_PERI_S_SH_NUM		(2)
#define IPC_MBOX_PERI_S_SH_END		(IPC_MBOX_PERI_S_SH_START + IPC_MBOX_PERI_S_SH_NUM - 1)

#define IPC_MBOX_PERI_S_XCPU_START	(IPC_MBOX_PERI_S_SH_END + 1)
#define IPC_MBOX_PERI_S_XCPU(n)		(IPC_MBOX_PERI_S_XCPU_START + n)
#define IPC_MBOX_PERI_S_XCPU_NUM	(8)
#define IPC_MBOX_PERI_S_XCPU_END	(IPC_MBOX_PERI_S_XCPU_START + IPC_MBOX_PERI_S_XCPU_NUM - 1)

#define IPC_MBOX_PERI_S_XDDR_START	(IPC_MBOX_PERI_S_XCPU_END + 1)
#define IPC_MBOX_PERI_S_XDDR(n)		(IPC_MBOX_PERI_S_XDDR_START + n)
#define IPC_MBOX_PERI_S_XDDR_NUM	(4)
#define IPC_MBOX_PERI_S_XDDR_END	(IPC_MBOX_PERI_S_XDDR_START + IPC_MBOX_PERI_S_XDDR_NUM - 1)



#define IPC_MBOX_AO_S_AP_START		(0)
#define IPC_MBOX_AO_S_AP(n)		(IPC_MBOX_AO_S_AP_START + n)
#define IPC_MBOX_AO_S_AP_NUM		(2)
#define IPC_MBOX_AO_S_AP_END		(IPC_MBOX_AO_S_AP_START + IPC_MBOX_AO_S_AP_NUM - 1)

#define IPC_MBOX_AO_S_LP_START		(IPC_MBOX_AO_S_AP_END + 1)
#define IPC_MBOX_AO_S_LP(n)		(IPC_MBOX_AO_S_LP_START + n)
#define IPC_MBOX_AO_S_LP_NUM		(4)
#define IPC_MBOX_AO_S_LP_END		(IPC_MBOX_AO_S_LP_START + IPC_MBOX_AO_S_LP_NUM - 1)

#define IPC_MBOX_AO_S_SH_START		(IPC_MBOX_AO_S_LP_END + 1)
#define IPC_MBOX_AO_S_SH(n)		(IPC_MBOX_AO_S_SH_START + n)
#define IPC_MBOX_AO_S_SH_NUM		(6)
#define IPC_MBOX_AO_S_SH_END		(IPC_MBOX_AO_S_SH_START + IPC_MBOX_AO_S_SH_NUM - 1)

#define IPC_MBOX_AO_S_ADSP_START	(IPC_MBOX_AO_S_SH_END + 1)
#define IPC_MBOX_AO_S_ADSP(n)		(IPC_MBOX_AO_S_ADSP_START + n)
#define IPC_MBOX_AO_S_ADSP_NUM		(2)
#define IPC_MBOX_AO_S_ADSP_END		(IPC_MBOX_AO_S_ADSP_START + IPC_MBOX_AO_S_ADSP_NUM - 1)



#define IPC_MBOX_XRSE0_START			(0)
#define IPC_MBOX_XRSE0(n)			(IPC_MBOX_XRSE0_START + n)
#define IPC_MBOX_XRSE0_NUM			(10)
#define IPC_MBOX_XRSE0_END			(IPC_MBOX_XRSE0_START + IPC_MBOX_XRSE0_NUM - 1)



#define IPC_MBOX_NPU_S_NPU_SH		(4)

#define IPC_MBOX_NPU_S_SH_NPU		(14)



#define IPC_MBOX_NPU_NS_NPU_SH		(4)

#define IPC_MBOX_NPU_NS_SH_NPU		(14)


#define IPC_IP_ID_PERI_NS0		(0)
#define IPC_IP_ID_PERI_NS1		(1)
#define IPC_IP_ID_AO_NS			(2)
#define IPC_IP_ID_PERI_S		(3)
#define IPC_IP_ID_AO_S			(4)
#define IPC_IP_ID_XRES			(5)
#define IPC_IP_ID_NPU_S			(6)
#define IPC_IP_ID_NPU_NS		(7)
#define IPC_IP_NUM			(8)


#define IPC_VC_NUM_PER_IP		(32)
#define IPC_VC_PERI_NS0_START		(0)
#define IPC_VC_PERI_NS0_END		(IPC_VC_PERI_NS0_START + IPC_VC_NUM_PER_IP)
#define IPC_VC_PERI_NS1_START		(IPC_VC_NUM_PER_IP)
#define IPC_VC_PERI_NS1_END		(IPC_VC_PERI_NS1_START + IPC_VC_NUM_PER_IP)
#define IPC_VC_AO_NS_START		(IPC_VC_NUM_PER_IP * 2)
#define IPC_VC_AO_NS_END		(IPC_VC_AO_NS_START + IPC_VC_NUM_PER_IP)
#define IPC_VC_PERI_S_START		(IPC_VC_NUM_PER_IP * 3)
#define IPC_VC_PERI_S_END		(IPC_VC_PERI_S_START + IPC_VC_NUM_PER_IP)
#define IPC_VC_AO_S_START		(IPC_VC_NUM_PER_IP * 4)
#define IPC_VC_AO_S_END			(IPC_VC_AO_S_START + IPC_VC_NUM_PER_IP)
#define IPC_VC_XRSE0_START		(IPC_VC_NUM_PER_IP * 5)
#define IPC_VC_XRSE0_END		(IPC_VC_XRSE0_START + IPC_VC_NUM_PER_IP)

#define IPC_VC_NPU_S_START		(IPC_VC_NUM_PER_IP * 6)
#define IPC_VC_NPU_S_END		(IPC_VC_NPU_S_START + IPC_VC_NUM_PER_IP)
#define IPC_VC_NPU_NS_START		(IPC_VC_NUM_PER_IP * 7)
#define IPC_VC_NPU_NS_END		(IPC_VC_NPU_NS_START + IPC_VC_NUM_PER_IP)



#define IPC_VC_PERI_NS_AP_SH_RESV		(IPC_VC_PERI_NS0_START)


#define IPC_VC_PERI_NS_AP_LP_CLOCK		(IPC_VC_PERI_NS0_START + 1)


#define IPC_VC_PERI_NS_AP_LP_COMMON_0		(IPC_VC_PERI_NS0_START + 2)


#define IPC_VC_PERI_NS_AP_LP_XDDR		(IPC_VC_PERI_NS0_START + 3)


#define IPC_VC_PERI_NS_AP_LP_COMMON_1		(IPC_VC_PERI_NS0_START + 4)


#define IPC_VC_PERI_NS_AP_ADSP_AUDIO		(IPC_VC_PERI_NS0_START + 5)


#define IPC_VC_PERI_NS_AP_ISP_CAMERA		(IPC_VC_PERI_NS0_START + 6)


#define IPC_VC_PERI_NS_AP_ISP0 			(IPC_VC_PERI_NS0_START + 7)


#define IPC_VC_PERI_NS_AP_ISP1			(IPC_VC_PERI_NS0_START + 8)




#define IPC_VC_PERI_NS_AP_XCPU_COMMON		(IPC_VC_PERI_NS1_START + 0)


#define IPC_VC_PERI_NS_AP_XCPU_GPU_FREQ		(IPC_VC_PERI_NS1_START + 1)


#define IPC_VC_PERI_NS_AP_XCPU_CPU_FREQ		(IPC_VC_PERI_NS1_START + 2)


#define IPC_VC_PERI_NS_AP_XCPU_XDDR_FREQ	(IPC_VC_PERI_NS1_START + 3)


#define IPC_VC_PERI_NS_XRSE_AP_COMMON		(IPC_VC_PERI_NS1_START + 4)




#define IPC_VC_AO_NS_SH_AP_DATA_TRANS		(IPC_VC_AO_NS_START + 0)


#define IPC_VC_AO_NS_SH_AP_TP		(IPC_VC_AO_NS_START + 1)


#define IPC_VC_AO_NS_SH_AP_DEFAULT		(IPC_VC_AO_NS_START + 2)


#define IPC_VC_AO_NS_SH_AP_AOD			(IPC_VC_AO_NS_START + 3)


#define IPC_VC_AO_NS_SH_ISP_COMMON		(IPC_VC_AO_NS_START + 4)


#define IPC_VC_AO_NS_SH_AP_CHRE		(IPC_VC_AO_NS_START + 5)


#define IPC_VC_AO_NS_ADSP_SH_AUDIO_DET		(IPC_VC_AO_NS_START + 6)


#define IPC_VC_AO_NS_SH_AP_OIS			(IPC_VC_AO_NS_START + 7)


#define IPC_VC_AO_NS_ADSP_AP_WACKUP		(IPC_VC_AO_NS_START + 8)


#define IPC_VC_AO_NS_ADSP_LP_RSVD		(IPC_VC_AO_NS_START + 9)



#define IPC_VC_PERI_S_SH_AP_COMMON		(IPC_VC_PERI_S_START + 0)


#define IPC_VC_PERI_S_AP_LP_PWR_DOMAIN		(IPC_VC_PERI_S_START + 1)


#define IPC_VC_PERI_S_AP_XCPU_GPU_PWR_CTRL	(IPC_VC_PERI_S_START + 2)


#define IPC_VC_PERI_S_AP_XCPU_CPUS_PWR_CTRL	(IPC_VC_PERI_S_START + 3)


#define IPC_VC_PERI_S_AP_XCPU_CPUM_PWR_CTRL	(IPC_VC_PERI_S_START + 4)


#define IPC_VC_PERI_S_AP_XCPU_CPUL_PWR_CTRL	(IPC_VC_PERI_S_START + 5)


#define IPC_VC_PERI_S_XCPU_LP_COMMON		(IPC_VC_PERI_S_START + 6)


#define IPC_VC_PERI_S_XDDR_LP_FREQ_SWITCH	(IPC_VC_PERI_S_START + 7)


#define IPC_VC_PERI_S_XCPU_XDDR_FREQ_SWITCH	(IPC_VC_PERI_S_START + 8)




#define IPC_VC_AO_S_AP_SH_SEC_BUSINESS		(IPC_VC_AO_S_START + 0)


#define IPC_VC_AO_S_LP_SH_SENSOR_DATA		(IPC_VC_AO_S_START + 1)



#define IPC_VC_AO_S_LP_SH_PWR_CTRL		(IPC_VC_AO_S_START + 2)


#define IPC_VC_AO_S_SH_ADSP_COMMON		(IPC_VC_AO_S_START + 3)

#define IPC_CHN_XRSE0_XRSE_AP_0			(6)
#define IPC_MBOX_XRSE0_XRSE			(6)
#define IPC_CHN_XRSE0_AP_XRSE_0			(1)
#define IPC_MBOX_XRSE0_AP			(1)


#define IPC_VC_XRSE0_AP_XRSE		(IPC_VC_XRSE0_START + 0)


#define IPC_VC_XRSE0_AP_XRSE_TEE	(IPC_VC_XRSE0_START + 0)


#define IPC_VC_XRSE0_AP_XRSE_BL31	(IPC_VC_XRSE0_START + 1)


#define IPC_VC_XRSE0_LPCORE_XRSE	(IPC_VC_XRSE0_START + 2)


#define IPC_VC_XRSE0_SENSORHUB_XRSE	(IPC_VC_XRSE0_START + 3)


#define IPC_VC_XRSE0_AP_XRSE_KERNEL	(IPC_VC_XRSE0_START + 4)


#define IPC_VC_NPU_S_SENSORHUB_NPU	(IPC_VC_NPU_S_START + 0)

#define IPC_VC_NPU_NS_SENSORHUB_NPU	(IPC_VC_NPU_NS_START + 0)

#endif 
