// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (C) 2022-2025, X-Ring technologies Inc., All rights reserved.
 */

#ifndef LPIS_CRG_REGIF_H
#define LPIS_CRG_REGIF_H

#define LPIS_CRG_CLKGT2_W1S                        0x0010
#define LPIS_CRG_CLKGT2_W1S_GT_CLK_AUD_BUS_CFG_SHIFT                            0
#define LPIS_CRG_CLKGT2_W1S_GT_CLK_AUD_BUS_DATA_SHIFT                           1
#define LPIS_CRG_CLKGT2_W1S_GT_PCLK_IPC_NS_SHIFT                                2
#define LPIS_CRG_CLKGT2_W1S_GT_CLK_I3C2_SHIFT                                   3
#define LPIS_CRG_CLKGT2_W1S_GT_CLK_I3C1_SHIFT                                   4
#define LPIS_CRG_CLKGT2_W1S_GT_CLK_I2C19_SHIFT                                  5
#define LPIS_CRG_CLKGT2_W1S_GT_CLK_I2C18_SHIFT                                  6
#define LPIS_CRG_CLKGT2_W1S_GT_PCLK_I3C2_SHIFT                                  7
#define LPIS_CRG_CLKGT2_W1S_GT_PCLK_I3C1_SHIFT                                  8
#define LPIS_CRG_CLKGT2_W1S_GT_PCLK_I2C19_SHIFT                                 9
#define LPIS_CRG_CLKGT2_W1S_GT_PCLK_I2C18_SHIFT                                 10
#define LPIS_CRG_CLKGT2_W1S_GT_CLK_CAM0_SHIFT                                   11
#define LPIS_CRG_CLKGT2_W1S_GT_CLK_CAM1_SHIFT                                   12
#define LPIS_CRG_CLKGT2_W1S_GT_CLK_CAM2_SHIFT                                   13
#define LPIS_CRG_CLKGT2_W1S_GT_CLK_CAM3_SHIFT                                   14
#define LPIS_CRG_CLKGT2_W1S_GT_CLK_CAM4_SHIFT                                   15
#define LPIS_CRG_CLKGT2_W1S_GT_CLK_CAM5_SHIFT                                   16
#define LPIS_CRG_CLKGT2_W1S_GT_CLK_OUT0_SHIFT                                   17
#define LPIS_CRG_RST2_W1S                          0x0020
#define LPIS_CRG_RST2_W1S_IP_PRST_IPC_NS_N_SHIFT                                0
#define LPIS_CRG_RST2_W1S_IP_RST_I3C2_N_SHIFT                                   1
#define LPIS_CRG_RST2_W1S_IP_RST_I3C1_N_SHIFT                                   2
#define LPIS_CRG_RST2_W1S_IP_RST_I2C19_N_SHIFT                                  3
#define LPIS_CRG_RST2_W1S_IP_RST_I2C18_N_SHIFT                                  4
#define LPIS_CRG_RST2_W1S_IP_PRST_I3C2_N_SHIFT                                  5
#define LPIS_CRG_RST2_W1S_IP_PRST_I3C1_N_SHIFT                                  6
#define LPIS_CRG_RST2_W1S_IP_PRST_I2C19_N_SHIFT                                 7
#define LPIS_CRG_RST2_W1S_IP_PRST_I2C18_N_SHIFT                                 8
#define LPIS_CRG_RST2_W1C                          0x0024
#define LPIS_CRG_RST2_W1C_IP_PRST_IPC_NS_N_SHIFT                                0
#define LPIS_CRG_RST2_W1C_IP_RST_I3C2_N_SHIFT                                   1
#define LPIS_CRG_RST2_W1C_IP_RST_I3C1_N_SHIFT                                   2
#define LPIS_CRG_RST2_W1C_IP_RST_I2C19_N_SHIFT                                  3
#define LPIS_CRG_RST2_W1C_IP_RST_I2C18_N_SHIFT                                  4
#define LPIS_CRG_RST2_W1C_IP_PRST_I3C2_N_SHIFT                                  5
#define LPIS_CRG_RST2_W1C_IP_PRST_I3C1_N_SHIFT                                  6
#define LPIS_CRG_RST2_W1C_IP_PRST_I2C19_N_SHIFT                                 7
#define LPIS_CRG_RST2_W1C_IP_PRST_I2C18_N_SHIFT                                 8
#define LPIS_CRG_RST2_RO                           0x0028
#define LPIS_CRG_RST2_RO_IP_PRST_IPC_NS_N_SHIFT                                 0
#define LPIS_CRG_RST2_RO_IP_PRST_IPC_NS_N_MASK                                  0x00000001
#define LPIS_CRG_RST2_RO_IP_RST_I3C2_N_SHIFT                                    1
#define LPIS_CRG_RST2_RO_IP_RST_I3C2_N_MASK                                     0x00000002
#define LPIS_CRG_RST2_RO_IP_RST_I3C1_N_SHIFT                                    2
#define LPIS_CRG_RST2_RO_IP_RST_I3C1_N_MASK                                     0x00000004
#define LPIS_CRG_RST2_RO_IP_RST_I2C19_N_SHIFT                                   3
#define LPIS_CRG_RST2_RO_IP_RST_I2C19_N_MASK                                    0x00000008
#define LPIS_CRG_RST2_RO_IP_RST_I2C18_N_SHIFT                                   4
#define LPIS_CRG_RST2_RO_IP_RST_I2C18_N_MASK                                    0x00000010
#define LPIS_CRG_RST2_RO_IP_PRST_I3C2_N_SHIFT                                   5
#define LPIS_CRG_RST2_RO_IP_PRST_I3C2_N_MASK                                    0x00000020
#define LPIS_CRG_RST2_RO_IP_PRST_I3C1_N_SHIFT                                   6
#define LPIS_CRG_RST2_RO_IP_PRST_I3C1_N_MASK                                    0x00000040
#define LPIS_CRG_RST2_RO_IP_PRST_I2C19_N_SHIFT                                  7
#define LPIS_CRG_RST2_RO_IP_PRST_I2C19_N_MASK                                   0x00000080
#define LPIS_CRG_RST2_RO_IP_PRST_I2C18_N_SHIFT                                  8
#define LPIS_CRG_RST2_RO_IP_PRST_I2C18_N_MASK                                   0x00000100
#define LPIS_CRG_CLKDIV13                          0x0040
#define LPIS_CRG_CLKDIV13_DIV_CLK_CAM_DIV_PRE_SHIFT                             0
#define LPIS_CRG_CLKDIV13_DIV_CLK_CAM_DIV_PRE_MASK                              0x0000003f
#define LPIS_CRG_CLKDIV13_DIV_CLK_CAM_SHIFT                                     6
#define LPIS_CRG_CLKDIV13_DIV_CLK_CAM_MASK                                      0x000000c0
#define LPIS_CRG_CLKDIV13_SC_GT_CLK_CAM_DIV_SHIFT                               12
#define LPIS_CRG_CLKDIV13_SC_GT_CLK_CAM_DIV_MASK                                0x00001000
#define LPIS_CRG_CLKDIV14                          0x0050
#define LPIS_CRG_CLKDIV14_SEL_CLK_CAM0_SHIFT                                    2
#define LPIS_CRG_CLKDIV14_SEL_CLK_CAM0_MASK                                     0x00000004
#define LPIS_CRG_CLKDIV14_SEL_CLK_CAM1_SHIFT                                    3
#define LPIS_CRG_CLKDIV14_SEL_CLK_CAM1_MASK                                     0x00000008
#define LPIS_CRG_CLKDIV14_SEL_CLK_CAM2_SHIFT                                    4
#define LPIS_CRG_CLKDIV14_SEL_CLK_CAM2_MASK                                     0x00000010
#define LPIS_CRG_CLKDIV14_SEL_CLK_CAM3_SHIFT                                    5
#define LPIS_CRG_CLKDIV14_SEL_CLK_CAM3_MASK                                     0x00000020
#define LPIS_CRG_CLKDIV14_SEL_CLK_CAM4_SHIFT                                    6
#define LPIS_CRG_CLKDIV14_SEL_CLK_CAM4_MASK                                     0x00000040
#define LPIS_CRG_CLKDIV14_SEL_CLK_CAM5_SHIFT                                    7
#define LPIS_CRG_CLKDIV14_SEL_CLK_CAM5_MASK                                     0x00000080
#define LPIS_CRG_CLKDIV14_SEL_CLK_CAM_MUX_SHIFT                                 11
#define LPIS_CRG_CLKDIV14_SEL_CLK_CAM_MUX_MASK                                  0x00000800
#define LPIS_CRG_DIV_STAT0                         0x0100
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_GPLL_LMS_SHIFT                          0
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_GPLL_LMS_MASK                           0x00000001
#define LPIS_CRG_DIV_STAT0_DIV_DONE_PCLK_LPIS_BUS_GPLL_DIV_SHIFT                1
#define LPIS_CRG_DIV_STAT0_DIV_DONE_PCLK_LPIS_BUS_GPLL_DIV_MASK                 0x00000002
#define LPIS_CRG_DIV_STAT0_DIV_DONE_PCLK_LPIS_BUS_LPPLL_DIV_SHIFT               2
#define LPIS_CRG_DIV_STAT0_DIV_DONE_PCLK_LPIS_BUS_LPPLL_DIV_MASK                0x00000004
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_LPIS_BUS_GPLL_DIV_SHIFT                 3
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_LPIS_BUS_GPLL_DIV_MASK                  0x00000008
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_LPIS_BUS_LPPLL_DIV_SHIFT                4
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_LPIS_BUS_LPPLL_DIV_MASK                 0x00000010
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_I2C_SHIFT                               5
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_I2C_MASK                                0x00000020
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_SPI_DMAC_SHIFT                          6
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_SPI_DMAC_MASK                           0x00000040
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_XRSE_AO_SHIFT                           7
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_XRSE_AO_MASK                            0x00000080
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_LPCTRL_GPLL_DIV_SHIFT                   8
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_LPCTRL_GPLL_DIV_MASK                    0x00000100
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_LPCTRL_LPPLL_DIV_SHIFT                  9
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_LPCTRL_LPPLL_DIV_MASK                   0x00000200
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_MEMREPAIR_SHIFT                         10
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_MEMREPAIR_MASK                          0x00000400
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_I3C_SHIFT                               11
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_I3C_MASK                                0x00000800
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_LPIS_AUDIO_SHIFT                        12
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_LPIS_AUDIO_MASK                         0x00001000
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_DEBUG_AO_APB_SHIFT                      13
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_DEBUG_AO_APB_MASK                       0x00002000
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_DEBUG_ATB_LPIS_SHIFT                    14
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_DEBUG_ATB_LPIS_MASK                     0x00004000
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_CAM_DIV_PRE_SHIFT                       15
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_CAM_DIV_PRE_MASK                        0x00008000
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_CAM_DIV_SHIFT                           16
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_CAM_DIV_MASK                            0x00010000
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_GPLL_SH_SHIFT                           17
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_GPLL_SH_MASK                            0x00020000
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_LPPLL_SH_SHIFT                          18
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_LPPLL_SH_MASK                           0x00040000
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_LPIS2AUDIO_I2S_SHIFT                    19
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_LPIS2AUDIO_I2S_MASK                     0x00080000
#define LPIS_CRG_DIV_STAT0_DIV_DONE_PCLK_CRG_LPCTRL_GPLL_DIV_SHIFT              20
#define LPIS_CRG_DIV_STAT0_DIV_DONE_PCLK_CRG_LPCTRL_GPLL_DIV_MASK               0x00100000
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_LPIS_GPIODB_SE_SHIFT                    21
#define LPIS_CRG_DIV_STAT0_DIV_DONE_CLK_LPIS_GPIODB_SE_MASK                     0x00200000
#define LPIS_CRG_DIV_STAT0_DIV_DONE_PCLK_CRG_LPCTRL_LPPLL_DIV_SHIFT             22
#define LPIS_CRG_DIV_STAT0_DIV_DONE_PCLK_CRG_LPCTRL_LPPLL_DIV_MASK              0x00400000
#define LPIS_CRG_RST0_W1S                          0x0820
#define LPIS_CRG_RST0_W1S_IP_PRST_ACTRL_N_SHIFT                                 0
#define LPIS_CRG_RST0_W1S_IP_PRST_IOC_N_SHIFT                                   1
#define LPIS_CRG_RST0_W1S_IP_PRST_LPIS_GPIO_SE_N_SHIFT                          2
#define LPIS_CRG_RST0_W1S_IP_PRST_LPIS_BUS_N_SHIFT                              3
#define LPIS_CRG_RST0_W1S_IP_RST_LPIS_GPIODB_SE_N_SHIFT                         4
#define LPIS_CRG_RST0_W1S_IP_PRST_LPIS_SPI_DMAC_N_SHIFT                         8
#define LPIS_CRG_RST0_W1S_IP_PRST_LPIS_DMA_N_SHIFT                              9
#define LPIS_CRG_RST0_W1S_IP_PRST_IPC_S_N_SHIFT                                 13
#define LPIS_CRG_RST0_W1S_IP_PRST_SPINLOCK_N_SHIFT                              14
#define LPIS_CRG_RST0_W1S_IP_RST_LPIS_BUS_N_SHIFT                               15
#define LPIS_CRG_RST0_W1S_IP_RST_LPIS_DMA_AXI2TO1_N_SHIFT                       17
#define LPIS_CRG_RST0_W1S_IP_RST_LPIS_DMA_N_SHIFT                               18
#define LPIS_CRG_RST0_W1S_IP_RST_SPI_DMAC_N_SHIFT                               19
#define LPIS_CRG_RST0_W1S_IP_RST_XRSE_AO_N_SHIFT                                20
#define LPIS_CRG_RST0_W1S_IP_RST_XRSE_AO_SENSOR_104M_N_SHIFT                    21
#define LPIS_CRG_RST0_W1S_IP_RST_XRSE_AO_SENSOR_32K_N_SHIFT                     22
#define LPIS_CRG_RST0_W1S_IP_RST_DEBUG_AO_N_SHIFT                               25
#define LPIS_CRG_RST0_W1S_IP_RST_LPISBUS2SYSBUS_NDB_SLV_N_SHIFT                 26
#define LPIS_CRG_RST0_W1S_IP_RST_LPCTRL2DDRCFG_NDB_SLV_N_SHIFT                  27
#define LPIS_CRG_RST0_W1C                          0x0824
#define LPIS_CRG_RST0_W1C_IP_PRST_ACTRL_N_SHIFT                                 0
#define LPIS_CRG_RST0_W1C_IP_PRST_IOC_N_SHIFT                                   1
#define LPIS_CRG_RST0_W1C_IP_PRST_LPIS_GPIO_SE_N_SHIFT                          2
#define LPIS_CRG_RST0_W1C_IP_PRST_LPIS_BUS_N_SHIFT                              3
#define LPIS_CRG_RST0_W1C_IP_RST_LPIS_GPIODB_SE_N_SHIFT                         4
#define LPIS_CRG_RST0_W1C_IP_PRST_LPIS_SPI_DMAC_N_SHIFT                         8
#define LPIS_CRG_RST0_W1C_IP_PRST_LPIS_DMA_N_SHIFT                              9
#define LPIS_CRG_RST0_W1C_IP_PRST_IPC_S_N_SHIFT                                 13
#define LPIS_CRG_RST0_W1C_IP_PRST_SPINLOCK_N_SHIFT                              14
#define LPIS_CRG_RST0_W1C_IP_RST_LPIS_BUS_N_SHIFT                               15
#define LPIS_CRG_RST0_W1C_IP_RST_LPIS_DMA_AXI2TO1_N_SHIFT                       17
#define LPIS_CRG_RST0_W1C_IP_RST_LPIS_DMA_N_SHIFT                               18
#define LPIS_CRG_RST0_W1C_IP_RST_SPI_DMAC_N_SHIFT                               19
#define LPIS_CRG_RST0_W1C_IP_RST_XRSE_AO_N_SHIFT                                20
#define LPIS_CRG_RST0_W1C_IP_RST_XRSE_AO_SENSOR_104M_N_SHIFT                    21
#define LPIS_CRG_RST0_W1C_IP_RST_XRSE_AO_SENSOR_32K_N_SHIFT                     22
#define LPIS_CRG_RST0_W1C_IP_RST_DEBUG_AO_N_SHIFT                               25
#define LPIS_CRG_RST0_W1C_IP_RST_LPISBUS2SYSBUS_NDB_SLV_N_SHIFT                 26
#define LPIS_CRG_RST0_W1C_IP_RST_LPCTRL2DDRCFG_NDB_SLV_N_SHIFT                  27
#define LPIS_CRG_RST0_RO                           0x0828
#define LPIS_CRG_RST0_RO_IP_PRST_ACTRL_N_SHIFT                                  0
#define LPIS_CRG_RST0_RO_IP_PRST_ACTRL_N_MASK                                   0x00000001
#define LPIS_CRG_RST0_RO_IP_PRST_IOC_N_SHIFT                                    1
#define LPIS_CRG_RST0_RO_IP_PRST_IOC_N_MASK                                     0x00000002
#define LPIS_CRG_RST0_RO_IP_PRST_LPIS_GPIO_SE_N_SHIFT                           2
#define LPIS_CRG_RST0_RO_IP_PRST_LPIS_GPIO_SE_N_MASK                            0x00000004
#define LPIS_CRG_RST0_RO_IP_PRST_LPIS_BUS_N_SHIFT                               3
#define LPIS_CRG_RST0_RO_IP_PRST_LPIS_BUS_N_MASK                                0x00000008
#define LPIS_CRG_RST0_RO_IP_RST_LPIS_GPIODB_SE_N_SHIFT                          4
#define LPIS_CRG_RST0_RO_IP_RST_LPIS_GPIODB_SE_N_MASK                           0x00000010
#define LPIS_CRG_RST0_RO_IP_PRST_LPIS_SPI_DMAC_N_SHIFT                          8
#define LPIS_CRG_RST0_RO_IP_PRST_LPIS_SPI_DMAC_N_MASK                           0x00000100
#define LPIS_CRG_RST0_RO_IP_PRST_LPIS_DMA_N_SHIFT                               9
#define LPIS_CRG_RST0_RO_IP_PRST_LPIS_DMA_N_MASK                                0x00000200
#define LPIS_CRG_RST0_RO_IP_PRST_IPC_S_N_SHIFT                                  13
#define LPIS_CRG_RST0_RO_IP_PRST_IPC_S_N_MASK                                   0x00002000
#define LPIS_CRG_RST0_RO_IP_PRST_SPINLOCK_N_SHIFT                               14
#define LPIS_CRG_RST0_RO_IP_PRST_SPINLOCK_N_MASK                                0x00004000
#define LPIS_CRG_RST0_RO_IP_RST_LPIS_BUS_N_SHIFT                                15
#define LPIS_CRG_RST0_RO_IP_RST_LPIS_BUS_N_MASK                                 0x00008000
#define LPIS_CRG_RST0_RO_IP_RST_LPIS_DMA_AXI2TO1_N_SHIFT                        17
#define LPIS_CRG_RST0_RO_IP_RST_LPIS_DMA_AXI2TO1_N_MASK                         0x00020000
#define LPIS_CRG_RST0_RO_IP_RST_LPIS_DMA_N_SHIFT                                18
#define LPIS_CRG_RST0_RO_IP_RST_LPIS_DMA_N_MASK                                 0x00040000
#define LPIS_CRG_RST0_RO_IP_RST_SPI_DMAC_N_SHIFT                                19
#define LPIS_CRG_RST0_RO_IP_RST_SPI_DMAC_N_MASK                                 0x00080000
#define LPIS_CRG_RST0_RO_IP_RST_XRSE_AO_N_SHIFT                                 20
#define LPIS_CRG_RST0_RO_IP_RST_XRSE_AO_N_MASK                                  0x00100000
#define LPIS_CRG_RST0_RO_IP_RST_XRSE_AO_SENSOR_104M_N_SHIFT                     21
#define LPIS_CRG_RST0_RO_IP_RST_XRSE_AO_SENSOR_104M_N_MASK                      0x00200000
#define LPIS_CRG_RST0_RO_IP_RST_XRSE_AO_SENSOR_32K_N_SHIFT                      22
#define LPIS_CRG_RST0_RO_IP_RST_XRSE_AO_SENSOR_32K_N_MASK                       0x00400000
#define LPIS_CRG_RST0_RO_IP_RST_DEBUG_AO_N_SHIFT                                25
#define LPIS_CRG_RST0_RO_IP_RST_DEBUG_AO_N_MASK                                 0x02000000
#define LPIS_CRG_RST0_RO_IP_RST_LPISBUS2SYSBUS_NDB_SLV_N_SHIFT                  26
#define LPIS_CRG_RST0_RO_IP_RST_LPISBUS2SYSBUS_NDB_SLV_N_MASK                   0x04000000
#define LPIS_CRG_RST0_RO_IP_RST_LPCTRL2DDRCFG_NDB_SLV_N_SHIFT                   27
#define LPIS_CRG_RST0_RO_IP_RST_LPCTRL2DDRCFG_NDB_SLV_N_MASK                    0x08000000
#endif
