// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (C) 2022-2025, X-Ring technologies Inc., All rights reserved.
 */

#ifndef ONE_WIRE_REGIF_H
#define ONE_WIRE_REGIF_H

#define ONE_WIRE_M_CMD_START                          0x0000
#define ONE_WIRE_M_CMD_START_START_EN_SHIFT                                       0
#define ONE_WIRE_M_CMD_START_START_EN_MASK                                        0x00000001
#define ONE_WIRE_M_CMD_MSG                            0x0004
#define ONE_WIRE_M_CMD_MSG_FUN_PARA_LEN_SHIFT                                     0
#define ONE_WIRE_M_CMD_MSG_FUN_PARA_LEN_MASK                                      0x000000ff
#define ONE_WIRE_M_ROM_CMD                            0x0008
#define ONE_WIRE_M_ROM_CMD_ROM_CMD_SHIFT                                          0
#define ONE_WIRE_M_ROM_CMD_ROM_CMD_MASK                                           0x000000ff
#define ONE_WIRE_M_FUN_CMD                            0x000c
#define ONE_WIRE_M_FUN_CMD_FUN_CMD_SHIFT                                          0
#define ONE_WIRE_M_FUN_CMD_FUN_CMD_MASK                                           0x000000ff
#define ONE_WIRE_M_FUN_PARA                           0x0010
#define ONE_WIRE_M_FUN_PARA_FUN_PARA_VALUE_SHIFT                                  0
#define ONE_WIRE_M_FUN_PARA_FUN_PARA_VALUE_MASK                                   0x000000ff
#define ONE_WIRE_M_CMD_STATU                          0x0014
#define ONE_WIRE_M_CMD_STATU_ROM_CMD_STATU_SHIFT                                  0
#define ONE_WIRE_M_CMD_STATU_ROM_CMD_STATU_MASK                                   0x000000ff
#define ONE_WIRE_M_TW1L_TIME                          0x0018
#define ONE_WIRE_M_TW1L_TIME_TW1L_TIME_SHIFT                                      0
#define ONE_WIRE_M_TW1L_TIME_TW1L_TIME_MASK                                       0x00001fff
#define ONE_WIRE_M_TW0L_TIME                          0x001c
#define ONE_WIRE_M_TW0L_TIME_TW0L_TIME_SHIFT                                      0
#define ONE_WIRE_M_TW0L_TIME_TW0L_TIME_MASK                                       0x00001fff
#define ONE_WIRE_M_TIMEOUT_CFG                        0x0020
#define ONE_WIRE_M_TWSLOT_TIME                        0x0024
#define ONE_WIRE_M_TWSLOT_TIME_TWSLOT_TIME_SHIFT                                  0
#define ONE_WIRE_M_TWSLOT_TIME_TWSLOT_TIME_MASK                                   0x00001fff
#define ONE_WIRE_M_TRL_TIME                           0x0028
#define ONE_WIRE_M_TRL_TIME_TRL_TIME_SHIFT                                        0
#define ONE_WIRE_M_TRL_TIME_TRL_TIME_MASK                                         0x00001fff
#define ONE_WIRE_M_TRSAMP_TIME                        0x002c
#define ONE_WIRE_M_TRSAMP_TIME_TRSAMP_TIME_SHIFT                                  0
#define ONE_WIRE_M_TRSAMP_TIME_TRSAMP_TIME_MASK                                   0x00001fff
#define ONE_WIRE_M_SEARCH_DISCREPANCY_LOC_CFG         0x0030
#define ONE_WIRE_M_SEARCH_DISCREPANCY_LOC_CFG_SEARCH_DISCREPANCY_LOC_CFG_SHIFT    0
#define ONE_WIRE_M_SEARCH_DISCREPANCY_LOC_CFG_SEARCH_DISCREPANCY_LOC_CFG_MASK     0x0000003f
#define ONE_WIRE_M_SEARCH_DISCREPANCY_LOC_CFG_SEARCH_DISCREPANCY_LOC_CFG_VLD_SHIFT 6
#define ONE_WIRE_M_SEARCH_DISCREPANCY_LOC_CFG_SEARCH_DISCREPANCY_LOC_CFG_VLD_MASK  0x00000040
#define ONE_WIRE_M_TRSLOT_TIME                        0x0034
#define ONE_WIRE_M_TRSLOT_TIME_TRSLOT_TIME_SHIFT                                  0
#define ONE_WIRE_M_TRSLOT_TIME_TRSLOT_TIME_MASK                                   0x00001fff
#define ONE_WIRE_M_RESP_DELAY                         0x0038
#define ONE_WIRE_M_RESP_DELAY_TRESP_DELAY_SHIFT                                   0
#define ONE_WIRE_M_RESP_DELAY_TRESP_DELAY_MASK                                    0x001fffff
#define ONE_WIRE_M_TRSTH_TIME                         0x003c
#define ONE_WIRE_M_TRSTH_TIME_TRSTH_TIME_SHIFT                                    0
#define ONE_WIRE_M_TRSTH_TIME_TRSTH_TIME_MASK                                     0x00007fff
#define ONE_WIRE_M_TRSTL_TIME                         0x0040
#define ONE_WIRE_M_TRSTL_TIME_TRSTL_TIME_SHIFT                                    0
#define ONE_WIRE_M_TRSTL_TIME_TRSTL_TIME_MASK                                     0x00000fff
#define ONE_WIRE_M_TRSTREC_TIME                       0x0044
#define ONE_WIRE_M_TRSTREC_TIME_TRSTREC_TIME_SHIFT                                0
#define ONE_WIRE_M_TRSTREC_TIME_TRSTREC_TIME_MASK                                 0x00007fff
#define ONE_WIRE_M_TX_ROMID0                          0x0048
#define ONE_WIRE_M_TX_ROMID1                          0x004c
#define ONE_WIRE_M_TX_ROMID1_TX_ROMID1_SHIFT                                      0
#define ONE_WIRE_M_TX_ROMID1_TX_ROMID1_MASK                                       0x00ffffff
#define ONE_WIRE_M_MEMORY_WDATA0                      0x0050
#define ONE_WIRE_M_MEMORY_WDATA1                      0x0054
#define ONE_WIRE_M_MEMORY_WDATA2                      0x0058
#define ONE_WIRE_M_MEMORY_WDATA3                      0x005c
#define ONE_WIRE_M_MEMORY_WDATA4                      0x0060
#define ONE_WIRE_M_MEMORY_WDATA5                      0x0064
#define ONE_WIRE_M_MEMORY_WDATA6                      0x0068
#define ONE_WIRE_M_MEMORY_WDATA7                      0x006c
#define ONE_WIRE_M_MEMORY_RDATA0                      0x0070
#define ONE_WIRE_M_MEMORY_RDATA1                      0x0074
#define ONE_WIRE_M_MEMORY_RDATA2                      0x0078
#define ONE_WIRE_M_MEMORY_RDATA3                      0x007c
#define ONE_WIRE_M_MEMORY_RDATA4                      0x0080
#define ONE_WIRE_M_MEMORY_RDATA5                      0x0084
#define ONE_WIRE_M_MEMORY_RDATA6                      0x0088
#define ONE_WIRE_M_MEMORY_RDATA7                      0x008c
#define ONE_WIRE_M_MEMORY_RDATA8                      0x0090
#define ONE_WIRE_M_MEMORY_RDATA9                      0x0094
#define ONE_WIRE_M_MEMORY_RDATA10                     0x0098
#define ONE_WIRE_M_MEMORY_RDATA11                     0x009c
#define ONE_WIRE_M_MEMORY_RDATA12                     0x00a0
#define ONE_WIRE_M_MEMORY_RDATA13                     0x00a4
#define ONE_WIRE_M_MEMORY_RDATA14                     0x00a8
#define ONE_WIRE_M_MEMORY_RDATA15                     0x00ac
#define ONE_WIRE_M_RPT_WARNING                        0x00b0
#define ONE_WIRE_M_RPT_WARNING_PARA_ERR_SHIFT                                     0
#define ONE_WIRE_M_RPT_WARNING_PARA_ERR_MASK                                      0x00000001
#define ONE_WIRE_M_RPT_WARNING_CRC_ERR_SHIFT                                      1
#define ONE_WIRE_M_RPT_WARNING_CRC_ERR_MASK                                       0x00000002
#define ONE_WIRE_M_RPT_WARNING_RX_COMMU_ERR_SHIFT                                 2
#define ONE_WIRE_M_RPT_WARNING_RX_COMMU_ERR_MASK                                  0x00000004
#define ONE_WIRE_M_RPT_WARNING_TX_COMMU_ERR_SHIFT                                 3
#define ONE_WIRE_M_RPT_WARNING_TX_COMMU_ERR_MASK                                  0x00000008
#define ONE_WIRE_M_RPT_WARNING_CMD_UNSUPPORT_SHIFT                                4
#define ONE_WIRE_M_RPT_WARNING_CMD_UNSUPPORT_MASK                                 0x00000010
#define ONE_WIRE_M_RPT_WARNING_ACCESS_LIMT_ERR_SHIFT                              5
#define ONE_WIRE_M_RPT_WARNING_ACCESS_LIMT_ERR_MASK                               0x00000020
#define ONE_WIRE_M_RPT_WARNING_EEPROM_ERR_SHIFT                                   6
#define ONE_WIRE_M_RPT_WARNING_EEPROM_ERR_MASK                                    0x00000040
#define ONE_WIRE_M_RPT_WARNING_ACCESS_CMD_ERR_SHIFT                               7
#define ONE_WIRE_M_RPT_WARNING_ACCESS_CMD_ERR_MASK                                0x00000080
#define ONE_WIRE_M_RPT_WARNING_ECDSA_FAIL_SHIFT                                   8
#define ONE_WIRE_M_RPT_WARNING_ECDSA_FAIL_MASK                                    0x00000100
#define ONE_WIRE_M_RPT_WARNING_CHIP_UNVALID_ERR_SHIFT                             9
#define ONE_WIRE_M_RPT_WARNING_CHIP_UNVALID_ERR_MASK                              0x00000200
#define ONE_WIRE_M_RPT_WARNING_RX_CRC_ERR_SHIFT                                   10
#define ONE_WIRE_M_RPT_WARNING_RX_CRC_ERR_MASK                                    0x00000400
#define ONE_WIRE_M_RPT_WARNING_CMD_SUCCESS_SHIFT                                  11
#define ONE_WIRE_M_RPT_WARNING_CMD_SUCCESS_MASK                                   0x00000800
#define ONE_WIRE_M_RPT_WARNING_SEARCH_DISCREPANCY_SHIFT                           12
#define ONE_WIRE_M_RPT_WARNING_SEARCH_DISCREPANCY_MASK                            0x00001000
#define ONE_WIRE_M_RPT_WARNING_SLV_NO_PRESENT_SHIFT                               13
#define ONE_WIRE_M_RPT_WARNING_SLV_NO_PRESENT_MASK                                0x00002000
#define ONE_WIRE_M_RPT_WARNING_TIMEOUT_WARNING_SHIFT                              14
#define ONE_WIRE_M_RPT_WARNING_TIMEOUT_WARNING_MASK                               0x00004000
#define ONE_WIRE_M_RPT_WARNING_SEARCH_SLV_NO_PRESENT_SHIFT                        15
#define ONE_WIRE_M_RPT_WARNING_SEARCH_SLV_NO_PRESENT_MASK                         0x00008000
#define ONE_WIRE_M_RX_ROMID0                          0x00b4
#define ONE_WIRE_M_RX_ROMID1                          0x00b8
#define ONE_WIRE_M_RX_ROMID1_RX_ROMID1_SHIFT                                      0
#define ONE_WIRE_M_RX_ROMID1_RX_ROMID1_MASK                                       0x00ffffff
#define ONE_WIRE_M_SEARCH_DISCREPANCY_LOC             0x00bc
#define ONE_WIRE_M_SEARCH_DISCREPANCY_LOC_SEARCH_DISCREPANCY_LOC_SHIFT            0
#define ONE_WIRE_M_SEARCH_DISCREPANCY_LOC_SEARCH_DISCREPANCY_LOC_MASK             0x0000003f
#define ONE_WIRE_INT_1_WIRE_IRQ_INT_RAW               0x0200
#define ONE_WIRE_INT_1_WIRE_IRQ_INT_RAW_INT_COMPLETE_RAW_SHIFT                    0
#define ONE_WIRE_INT_1_WIRE_IRQ_INT_FORCE             0x0204
#define ONE_WIRE_INT_1_WIRE_IRQ_INT_FORCE_INT_COMPLETE_RAW_SHIFT                  0
#define ONE_WIRE_INT_1_WIRE_IRQ_INT_MASK              0x0208
#define ONE_WIRE_INT_1_WIRE_IRQ_INT_MASK_INT_COMPLETE_MASK_SHIFT                  0
#define ONE_WIRE_INT_1_WIRE_IRQ_INT_MASK_INT_COMPLETE_MASK_MASK                   0x00000001
#define ONE_WIRE_INT_1_WIRE_IRQ_INT_STATUS            0x020c
#define ONE_WIRE_INT_1_WIRE_IRQ_INT_STATUS_INT_COMPLETE_STATUS_SHIFT              0
#define ONE_WIRE_INT_1_WIRE_IRQ_INT_STATUS_INT_COMPLETE_STATUS_MASK               0x00000001
#define ONE_WIRE_CGBYPASS                             0x0210
#define ONE_WIRE_CGBYPASS_CGBYPASS_SHIFT                                          0
#define ONE_WIRE_CGBYPASS_CGBYPASS_MASK                                           0x00000001


#endif
