// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (C) 2022-2025, X-Ring technologies Inc., All rights reserved.
 */
#ifndef __SENSORHUB_DDR_LAYOUT_H__
#define __SENSORHUB_DDR_LAYOUT_H__

#define SHUB_NS_DDR_LOG_BUFFER_ADDR     (0x45000000)
#define SHUB_NS_DDR_LOG_BUFFER_SIZE     (0x100000)

#define SHUB_NS_DDR_DUMP_ADDR           (SHUB_NS_DDR_LOG_BUFFER_ADDR + SHUB_NS_DDR_LOG_BUFFER_SIZE)
#define SHUB_NS_DDR_DUMP_SIZE           (0x200000)

#define SHUB_NS_DDR_SHM_DTS_ADDR        (SHUB_NS_DDR_DUMP_ADDR + SHUB_NS_DDR_DUMP_SIZE)
#define SHUB_NS_DDR_SHM_DTS_SIZE        (0x10000)

#define SHUB_NS_DDR_SHM_IPC_ADDR        (SHUB_NS_DDR_SHM_DTS_ADDR + SHUB_NS_DDR_SHM_DTS_SIZE)
#define MCU_SHUB_NS_DDR_SHM_IPC_ADDR    (MCU_SHUB_NS_DDR_SHM_DTS_ADDR + SHUB_NS_DDR_SHM_DTS_SIZE)
#define SHUB_NS_DDR_SHM_IPC_SIZE        (0x70000)

#define SHUB_NS_DDR_SDC_MEM_ADDR        (SHUB_NS_DDR_SHM_IPC_ADDR + SHUB_NS_DDR_SHM_IPC_SIZE)
#define SHUB_NS_DDR_SDC_MEM_SIZE        (0x100000)

#endif
