// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (C) 2022-2025, X-Ring technologies Inc., All rights reserved.
 */

#ifndef SPI_DMA_REGIF_REGIF_H
#define SPI_DMA_REGIF_REGIF_H

#define SPI_DMA_REGIF_SPI_DMA_EN                                  0x0100
#define SPI_DMA_REGIF_SPI_DMA_EN_SPI_DMA_EN_SHIFT                                   0
#define SPI_DMA_REGIF_SPI_DMA_EN_SPI_DMA_EN_MASK                                    0x00000001
#define SPI_DMA_REGIF_SPI_DMA_FRAME                               0x0104
#define SPI_DMA_REGIF_SPI_DMA_AXI_ADDR_L                          0x0108
#define SPI_DMA_REGIF_SPI_DMA_AXI_ADDR_H                          0x010c
#define SPI_DMA_REGIF_SPI_DMA_AXI_CTL                             0x0110
#define SPI_DMA_REGIF_SPI_DMA_AXI_CTL_AXI_AWID_SHIFT                                0
#define SPI_DMA_REGIF_SPI_DMA_AXI_CTL_AXI_AWID_MASK                                 0x0000000f
#define SPI_DMA_REGIF_SPI_DMA_AXI_CTL_AXI_AWCACHE_SHIFT                             4
#define SPI_DMA_REGIF_SPI_DMA_AXI_CTL_AXI_AWCACHE_MASK                              0x000000f0
#define SPI_DMA_REGIF_SPI_DMA_AXI_CTL_AXI_AWPROT_RAW_SHIFT                          8
#define SPI_DMA_REGIF_SPI_DMA_AXI_CTL_AXI_AWPROT_RAW_MASK                           0x00000700
#define SPI_DMA_REGIF_SPI_DMA_AXI_CTL_AXI_AWQOS_SHIFT                               11
#define SPI_DMA_REGIF_SPI_DMA_AXI_CTL_AXI_AWQOS_MASK                                0x00007800
#define SPI_DMA_REGIF_SPI_DMA_TIMECNT                             0x0114
#define SPI_DMA_REGIF_SPI_DMA_STATE                               0x0118
#define SPI_DMA_REGIF_SPI_DMA_STATE_TIMEOUT_SHIFT                                   0
#define SPI_DMA_REGIF_SPI_DMA_STATE_TIMEOUT_MASK                                    0x00000001
#define SPI_DMA_REGIF_SPI_DMA_STATE_FIFO_CNT_SHIFT                                  1
#define SPI_DMA_REGIF_SPI_DMA_STATE_FIFO_CNT_MASK                                   0x0000003e
#define SPI_DMA_REGIF_SPI_DMA_APB_CNT                             0x011c
#define SPI_DMA_REGIF_SPI_DMA_AXI_CNT                             0x0120
#define SPI_DMA_REGIF_SPI_DMA_GIF_CNT                             0x0124
#define SPI_DMA_REGIF_INT_SPI_DMA_IRQ_INT_RAW                     0x0130
#define SPI_DMA_REGIF_INT_SPI_DMA_IRQ_INT_RAW_EVENT_FRAME_END_RAW_SHIFT             0
#define SPI_DMA_REGIF_INT_SPI_DMA_IRQ_INT_FORCE                   0x0134
#define SPI_DMA_REGIF_INT_SPI_DMA_IRQ_INT_FORCE_EVENT_FRAME_END_RAW_SHIFT           0
#define SPI_DMA_REGIF_INT_SPI_DMA_IRQ_INT_MASK                    0x0138
#define SPI_DMA_REGIF_INT_SPI_DMA_IRQ_INT_MASK_EVENT_FRAME_END_MASK_SHIFT           0
#define SPI_DMA_REGIF_INT_SPI_DMA_IRQ_INT_MASK_EVENT_FRAME_END_MASK_MASK            0x00000001
#define SPI_DMA_REGIF_INT_SPI_DMA_IRQ_INT_STATUS                  0x013c
#define SPI_DMA_REGIF_INT_SPI_DMA_IRQ_INT_STATUS_EVENT_FRAME_END_STATUS_SHIFT       0
#define SPI_DMA_REGIF_INT_SPI_DMA_IRQ_INT_STATUS_EVENT_FRAME_END_STATUS_MASK        0x00000001
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_RAW                 0x0140
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_RAW_EVENT_GIF_DEC_ERR_RAW_SHIFT       0
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_RAW_EVENT_GIF_ADDR_ERR_RAW_SHIFT      1
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_RAW_EVENT_APB_ERR_RAW_SHIFT           2
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_RAW_EVENT_FIFO_UD_ERR_RAW_SHIFT       3
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_RAW_EVENT_FIFO_OV_ERR_RAW_SHIFT       4
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_FORCE               0x0144
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_FORCE_EVENT_GIF_DEC_ERR_RAW_SHIFT     0
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_FORCE_EVENT_GIF_ADDR_ERR_RAW_SHIFT    1
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_FORCE_EVENT_APB_ERR_RAW_SHIFT         2
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_FORCE_EVENT_FIFO_UD_ERR_RAW_SHIFT     3
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_FORCE_EVENT_FIFO_OV_ERR_RAW_SHIFT     4
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_MASK                0x0148
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_MASK_EVENT_GIF_DEC_ERR_MASK_SHIFT     0
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_MASK_EVENT_GIF_DEC_ERR_MASK_MASK      0x00000001
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_MASK_EVENT_GIF_ADDR_ERR_MASK_SHIFT    1
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_MASK_EVENT_GIF_ADDR_ERR_MASK_MASK     0x00000002
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_MASK_EVENT_APB_ERR_MASK_SHIFT         2
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_MASK_EVENT_APB_ERR_MASK_MASK          0x00000004
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_MASK_EVENT_FIFO_UD_ERR_MASK_SHIFT     3
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_MASK_EVENT_FIFO_UD_ERR_MASK_MASK      0x00000008
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_MASK_EVENT_FIFO_OV_ERR_MASK_SHIFT     4
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_MASK_EVENT_FIFO_OV_ERR_MASK_MASK      0x00000010
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_STATUS              0x014c
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_STATUS_EVENT_GIF_DEC_ERR_STATUS_SHIFT 0
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_STATUS_EVENT_GIF_DEC_ERR_STATUS_MASK  0x00000001
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_STATUS_EVENT_GIF_ADDR_ERR_STATUS_SHIFT 1
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_STATUS_EVENT_GIF_ADDR_ERR_STATUS_MASK  0x00000002
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_STATUS_EVENT_APB_ERR_STATUS_SHIFT     2
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_STATUS_EVENT_APB_ERR_STATUS_MASK      0x00000004
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_STATUS_EVENT_FIFO_UD_ERR_STATUS_SHIFT 3
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_STATUS_EVENT_FIFO_UD_ERR_STATUS_MASK  0x00000008
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_STATUS_EVENT_FIFO_OV_ERR_STATUS_SHIFT 4
#define SPI_DMA_REGIF_INT_SPI_DMA_ERR_IRQ_INT_STATUS_EVENT_FIFO_OV_ERR_STATUS_MASK  0x00000010


#endif
