// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (C) 2022-2025, X-Ring technologies Inc., All rights reserved.
 */

#ifndef UFS_SYS_CTRL_REGIF_H
#define UFS_SYS_CTRL_REGIF_H

#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_W1S                0x0000
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_W1S_RESET_N_SW_SHIFT                  0
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_W1S_ARESETN_SW_SHIFT                  1
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_W1S_UFS_ESI_RST_N_SW_SHIFT            2
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_W1S_UFS_MISC_RST_N_SW_SHIFT           3
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_W1S_MPHY_APB_RST_N_SW_SHIFT           4
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_W1S_SRAMC_CLK_EN_SW_SHIFT             8
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_W1S_REF_ALT_CLK_EN_SW_SHIFT           9
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_W1C                0x0004
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_W1C_RESET_N_SW_SHIFT                  0
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_W1C_ARESETN_SW_SHIFT                  1
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_W1C_UFS_ESI_RST_N_SW_SHIFT            2
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_W1C_UFS_MISC_RST_N_SW_SHIFT           3
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_W1C_MPHY_APB_RST_N_SW_SHIFT           4
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_W1C_SRAMC_CLK_EN_SW_SHIFT             8
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_W1C_REF_ALT_CLK_EN_SW_SHIFT           9
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_RO                 0x0008
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_RO_RESET_N_SW_SHIFT                   0
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_RO_RESET_N_SW_MASK                    0x00000001
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_RO_ARESETN_SW_SHIFT                   1
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_RO_ARESETN_SW_MASK                    0x00000002
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_RO_UFS_ESI_RST_N_SW_SHIFT             2
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_RO_UFS_ESI_RST_N_SW_MASK              0x00000004
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_RO_UFS_MISC_RST_N_SW_SHIFT            3
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_RO_UFS_MISC_RST_N_SW_MASK             0x00000008
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_RO_MPHY_APB_RST_N_SW_SHIFT            4
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_RO_MPHY_APB_RST_N_SW_MASK             0x00000010
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_RO_SRAMC_CLK_EN_SW_SHIFT              8
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_RO_SRAMC_CLK_EN_SW_MASK               0x00000100
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_RO_REF_ALT_CLK_EN_SW_SHIFT            9
#define UFS_SYS_CTRL_UFS_SYS_RST_SWGT_RO_REF_ALT_CLK_EN_SW_MASK             0x00000200
#define UFS_SYS_CTRL_RSVD_0                              0x000c
#define UFS_SYS_CTRL_RSVD_1                              0x0010
#define UFS_SYS_CTRL_DWC_UFSHC_CTRL                      0x0014
#define UFS_SYS_CTRL_DWC_UFSHC_CTRL_IES_EN_MASK_SHIFT                       0
#define UFS_SYS_CTRL_DWC_UFSHC_CTRL_IES_EN_MASK_MASK                        0x00000001
#define UFS_SYS_CTRL_DWC_UFSHC_CTRL_LA_RESETMODEREQ_SHIFT                   1
#define UFS_SYS_CTRL_DWC_UFSHC_CTRL_LA_RESETMODEREQ_MASK                    0x00000002
#define UFS_SYS_CTRL_DWC_UFSHC_STAT                      0x0018
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_UFS_IDLE_IND_SHIFT                      0
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_UFS_IDLE_IND_MASK                       0x00000001
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_TX_PWRENBL_SHIFT                        1
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_TX_PWRENBL_MASK                         0x00000006
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_RX_PWRENBL_SHIFT                        3
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_RX_PWRENBL_MASK                         0x00000018
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_UFS_HIBERNATE_STATE_SHIFT               5
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_UFS_HIBERNATE_STATE_MASK                0x00000020
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_LP_RESETCOMPLETE_SHIFT                  6
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_LP_RESETCOMPLETE_MASK                   0x00000040
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_CG_SYSCLKREQ_SHIFT                      8
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_CG_SYSCLKREQ_MASK                       0x00000100
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_CG_CLK_TREQ_SHIFT                       9
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_CG_CLK_TREQ_MASK                        0x00000200
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_CG_LP_CLK_TREQ_SHIFT                    10
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_CG_LP_CLK_TREQ_MASK                     0x00000400
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_CG_PCLKREQ_SHIFT                        11
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_CG_PCLKREQ_MASK                         0x00000800
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_DWC_MPHY_CFGCLK_EN_SHIFT                12
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_DWC_MPHY_CFGCLK_EN_MASK                 0x00001000
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_LP_RXCLK_SEL_SHIFT                      13
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_LP_RXCLK_SEL_MASK                       0x00002000
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_CG_PXRXUSABLE_SHIFT                     14
#define UFS_SYS_CTRL_DWC_UFSHC_STAT_CG_PXRXUSABLE_MASK                      0x0000c000
#define UFS_SYS_CTRL_RSVD_4                              0x001c
#define UFS_SYS_CTRL_DWC_MPHY_CTRL                       0x0020
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_CFG_CLOCK_SEL_SHIFT                      0
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_CFG_CLOCK_SEL_MASK                       0x00000007
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_REF_CLOCK_SEL_SHIFT                      3
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_REF_CLOCK_SEL_MASK                       0x00000038
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_MPHY_CFG_SHIFT                           6
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_MPHY_CFG_MASK                            0x000000c0
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_RES_EXT_RCAL_SHIFT                       8
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_RES_EXT_RCAL_MASK                        0x00003f00
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_RES_EXT_EN_SHIFT                         14
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_RES_EXT_EN_MASK                          0x00004000
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_ANA_PWR_EN_OVERRIDE_SHIFT                15
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_ANA_PWR_EN_OVERRIDE_MASK                 0x00008000
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_SRAM_BYPASS_MODE_SHIFT                   16
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_SRAM_BYPASS_MODE_MASK                    0x00030000
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_SRAM_BOOTLOAD_BYPASS_MODE_SHIFT          18
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_SRAM_BOOTLOAD_BYPASS_MODE_MASK           0x000c0000
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_SRAM_EXT_LD_DONE_SHIFT                   20
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_SRAM_EXT_LD_DONE_MASK                    0x00100000
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_REF_PRE_VREG_BYPASS_SHIFT                24
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_REF_PRE_VREG_BYPASS_MASK                 0x01000000
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_DWC_MPHY_ULPH8_EN_SHIFT                  28
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_DWC_MPHY_ULPH8_EN_MASK                   0x10000000
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_DWC_MPHY_CFGCLK_CGEN_SHIFT               29
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_DWC_MPHY_CFGCLK_CGEN_MASK                0x20000000
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_DWC_MPHY_REFCLK_CGEN_SHIFT               30
#define UFS_SYS_CTRL_DWC_MPHY_CTRL_DWC_MPHY_REFCLK_CGEN_MASK                0x40000000
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD                   0x0024
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_PHY_RESET_SHIFT                      0
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_PHY_RESET_MASK                       0x00000001
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_MPHY_DISABLE_OVRD_V_SHIFT            1
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_MPHY_DISABLE_OVRD_V_MASK             0x00000002
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_TX_RESET_0_OVRD_V_SHIFT              2
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_TX_RESET_0_OVRD_V_MASK               0x00000004
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_TX_RESET_1_OVRD_V_SHIFT              3
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_TX_RESET_1_OVRD_V_MASK               0x00000008
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_TX_MAIN_RESET_0_OVRD_V_SHIFT         4
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_TX_MAIN_RESET_0_OVRD_V_MASK          0x00000010
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_TX_MAIN_RESET_1_OVRD_V_SHIFT         5
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_TX_MAIN_RESET_1_OVRD_V_MASK          0x00000020
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_RX_RESET_0_OVRD_V_SHIFT              6
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_RX_RESET_0_OVRD_V_MASK               0x00000040
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_RX_RESET_1_OVRD_V_SHIFT              7
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_RX_RESET_1_OVRD_V_MASK               0x00000080
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_RX_MAIN_RESET_0_OVRD_V_SHIFT         8
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_RX_MAIN_RESET_0_OVRD_V_MASK          0x00000100
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_RX_MAIN_RESET_1_OVRD_V_SHIFT         9
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_RX_MAIN_RESET_1_OVRD_V_MASK          0x00000200
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_MPHY_DISABLE_OVRD_EN_SHIFT           17
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_MPHY_DISABLE_OVRD_EN_MASK            0x00020000
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_TX_RESET_0_OVRD_EN_SHIFT             18
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_TX_RESET_0_OVRD_EN_MASK              0x00040000
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_TX_RESET_1_OVRD_EN_SHIFT             19
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_TX_RESET_1_OVRD_EN_MASK              0x00080000
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_TX_MAIN_RESET_0_OVRD_EN_SHIFT        20
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_TX_MAIN_RESET_0_OVRD_EN_MASK         0x00100000
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_TX_MAIN_RESET_1_OVRD_EN_SHIFT        21
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_TX_MAIN_RESET_1_OVRD_EN_MASK         0x00200000
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_RX_RESET_0_OVRD_EN_SHIFT             22
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_RX_RESET_0_OVRD_EN_MASK              0x00400000
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_RX_RESET_1_OVRD_EN_SHIFT             23
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_RX_RESET_1_OVRD_EN_MASK              0x00800000
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_RX_MAIN_RESET_0_OVRD_EN_SHIFT        24
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_RX_MAIN_RESET_0_OVRD_EN_MASK         0x01000000
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_RX_MAIN_RESET_1_OVRD_EN_SHIFT        25
#define UFS_SYS_CTRL_DWC_MPHY_RST_OVRD_RX_MAIN_RESET_1_OVRD_EN_MASK         0x02000000
#define UFS_SYS_CTRL_DWC_MPHY_STAT                       0x0028
#define UFS_SYS_CTRL_DWC_MPHY_STAT_SRAM_INIT_DONE_SHIFT                     0
#define UFS_SYS_CTRL_DWC_MPHY_STAT_SRAM_INIT_DONE_MASK                      0x00000001
#define UFS_SYS_CTRL_DWC_MPHY_STAT_REF_CLK_REQ_SHIFT                        1
#define UFS_SYS_CTRL_DWC_MPHY_STAT_REF_CLK_REQ_MASK                         0x00000002
#define UFS_SYS_CTRL_DWC_MPHY_STAT_TX_BUSY_0_SHIFT                          2
#define UFS_SYS_CTRL_DWC_MPHY_STAT_TX_BUSY_0_MASK                           0x00000004
#define UFS_SYS_CTRL_DWC_MPHY_STAT_TX_BUSY_1_SHIFT                          3
#define UFS_SYS_CTRL_DWC_MPHY_STAT_TX_BUSY_1_MASK                           0x00000008
#define UFS_SYS_CTRL_DWC_MPHY_STAT_RX_BUSY_0_SHIFT                          4
#define UFS_SYS_CTRL_DWC_MPHY_STAT_RX_BUSY_0_MASK                           0x00000010
#define UFS_SYS_CTRL_DWC_MPHY_STAT_RX_BUSY_1_SHIFT                          5
#define UFS_SYS_CTRL_DWC_MPHY_STAT_RX_BUSY_1_MASK                           0x00000020
#define UFS_SYS_CTRL_DWC_MPHY_STAT_TX_CFGRDYN_0_SHIFT                       6
#define UFS_SYS_CTRL_DWC_MPHY_STAT_TX_CFGRDYN_0_MASK                        0x00000040
#define UFS_SYS_CTRL_DWC_MPHY_STAT_TX_CFGRDYN_1_SHIFT                       7
#define UFS_SYS_CTRL_DWC_MPHY_STAT_TX_CFGRDYN_1_MASK                        0x00000080
#define UFS_SYS_CTRL_DWC_MPHY_STAT_RX_CFGRDYN_0_SHIFT                       8
#define UFS_SYS_CTRL_DWC_MPHY_STAT_RX_CFGRDYN_0_MASK                        0x00000100
#define UFS_SYS_CTRL_DWC_MPHY_STAT_RX_CFGRDYN_1_SHIFT                       9
#define UFS_SYS_CTRL_DWC_MPHY_STAT_RX_CFGRDYN_1_MASK                        0x00000200
#define UFS_SYS_CTRL_DWC_MPHY_STAT_RX_SQ_RCVD_0_SHIFT                       10
#define UFS_SYS_CTRL_DWC_MPHY_STAT_RX_SQ_RCVD_0_MASK                        0x00000400
#define UFS_SYS_CTRL_DWC_MPHY_STAT_RX_SQ_RCVD_1_SHIFT                       11
#define UFS_SYS_CTRL_DWC_MPHY_STAT_RX_SQ_RCVD_1_MASK                        0x00000800
#define UFS_SYS_CTRL_DWC_MPHY_STAT_ANA_PWR_STABLE_SHIFT                     12
#define UFS_SYS_CTRL_DWC_MPHY_STAT_ANA_PWR_STABLE_MASK                      0x00001000
#define UFS_SYS_CTRL_DWC_MPHY_STAT_DTB_OUT_SHIFT                            13
#define UFS_SYS_CTRL_DWC_MPHY_STAT_DTB_OUT_MASK                             0x00006000
#define UFS_SYS_CTRL_DWC_MPHY_FLOVR_CTRL                 0x0034
#define UFS_SYS_CTRL_DWC_MPHY_FLOVR_CTRL_RX1_FLYOVER_EN_SHIFT               0
#define UFS_SYS_CTRL_DWC_MPHY_FLOVR_CTRL_RX1_FLYOVER_EN_MASK                0x00000001
#define UFS_SYS_CTRL_DWC_MPHY_FLOVR_CTRL_RX0_FLYOVER_EN_SHIFT               1
#define UFS_SYS_CTRL_DWC_MPHY_FLOVR_CTRL_RX0_FLYOVER_EN_MASK                0x00000002
#define UFS_SYS_CTRL_DWC_MPHY_FLOVR_CTRL_TX1_FLYOVER_EN_SHIFT               2
#define UFS_SYS_CTRL_DWC_MPHY_FLOVR_CTRL_TX1_FLYOVER_EN_MASK                0x00000004
#define UFS_SYS_CTRL_DWC_MPHY_FLOVR_CTRL_TX0_FLYOVER_EN_SHIFT               3
#define UFS_SYS_CTRL_DWC_MPHY_FLOVR_CTRL_TX0_FLYOVER_EN_MASK                0x00000008
#define UFS_SYS_CTRL_DWC_MPHY_FLOVR_STAT                 0x0038
#define UFS_SYS_CTRL_DWC_MPHY_FLOVR_STAT_RX1_FLYOVER_DATA_P_SHIFT           0
#define UFS_SYS_CTRL_DWC_MPHY_FLOVR_STAT_RX1_FLYOVER_DATA_P_MASK            0x00000001
#define UFS_SYS_CTRL_DWC_MPHY_FLOVR_STAT_RX1_FLYOVER_DATA_M_SHIFT           1
#define UFS_SYS_CTRL_DWC_MPHY_FLOVR_STAT_RX1_FLYOVER_DATA_M_MASK            0x00000002
#define UFS_SYS_CTRL_DWC_MPHY_FLOVR_STAT_RX0_FLYOVER_DATA_P_SHIFT           2
#define UFS_SYS_CTRL_DWC_MPHY_FLOVR_STAT_RX0_FLYOVER_DATA_P_MASK            0x00000004
#define UFS_SYS_CTRL_DWC_MPHY_FLOVR_STAT_RX0_FLYOVER_DATA_M_SHIFT           3
#define UFS_SYS_CTRL_DWC_MPHY_FLOVR_STAT_RX0_FLYOVER_DATA_M_MASK            0x00000008
#define UFS_SYS_CTRL_DWC_MPHY_TEST_CTRL                  0x003c
#define UFS_SYS_CTRL_DWC_MPHY_TEST_CTRL_TEST_TX_REF_CLK_EN_SHIFT            0
#define UFS_SYS_CTRL_DWC_MPHY_TEST_CTRL_TEST_TX_REF_CLK_EN_MASK             0x00000001
#define UFS_SYS_CTRL_DWC_MPHY_TEST_CTRL_TEST_STOP_CLK_EN_SHIFT              1
#define UFS_SYS_CTRL_DWC_MPHY_TEST_CTRL_TEST_STOP_CLK_EN_MASK               0x00000002
#define UFS_SYS_CTRL_DWC_MPHY_TEST_CTRL_TEST_POWERDOWN_SHIFT                2
#define UFS_SYS_CTRL_DWC_MPHY_TEST_CTRL_TEST_POWERDOWN_MASK                 0x00000004
#define UFS_SYS_CTRL_DWC_MPHY_TEST_CTRL_TEST_BURNIN_SHIFT                   3
#define UFS_SYS_CTRL_DWC_MPHY_TEST_CTRL_TEST_BURNIN_MASK                    0x00000008
#define UFS_SYS_CTRL_DWC_MPHY_TEST_CTRL_TEST_FLYOVER_EN_SHIFT               4
#define UFS_SYS_CTRL_DWC_MPHY_TEST_CTRL_TEST_FLYOVER_EN_MASK                0x00000010
#define UFS_SYS_CTRL_DWC_MPHY_RMMI_OBSV_CTRL             0x0040
#define UFS_SYS_CTRL_DWC_MPHY_RMMI_OBSV_CTRL_TX_TST_RTCONTROL_0_SHIFT       0
#define UFS_SYS_CTRL_DWC_MPHY_RMMI_OBSV_CTRL_TX_TST_RTCONTROL_0_MASK        0x000000ff
#define UFS_SYS_CTRL_DWC_MPHY_RMMI_OBSV_CTRL_TX_TST_RTCONTROL_1_SHIFT       8
#define UFS_SYS_CTRL_DWC_MPHY_RMMI_OBSV_CTRL_TX_TST_RTCONTROL_1_MASK        0x0000ff00
#define UFS_SYS_CTRL_DWC_MPHY_RMMI_OBSV_CTRL_RX_TST_RTCONTROL_0_SHIFT       16
#define UFS_SYS_CTRL_DWC_MPHY_RMMI_OBSV_CTRL_RX_TST_RTCONTROL_0_MASK        0x00ff0000
#define UFS_SYS_CTRL_DWC_MPHY_RMMI_OBSV_CTRL_RX_TST_RTCONTROL_1_SHIFT       24
#define UFS_SYS_CTRL_DWC_MPHY_RMMI_OBSV_CTRL_RX_TST_RTCONTROL_1_MASK        0xff000000
#define UFS_SYS_CTRL_DWC_MPHY_RMMI_OBSV_STAT             0x0044
#define UFS_SYS_CTRL_DWC_MPHY_RMMI_OBSV_STAT_TX_TST_RTOBSERVE_0_SHIFT       0
#define UFS_SYS_CTRL_DWC_MPHY_RMMI_OBSV_STAT_TX_TST_RTOBSERVE_0_MASK        0x000000ff
#define UFS_SYS_CTRL_DWC_MPHY_RMMI_OBSV_STAT_TX_TST_RTOBSERVE_1_SHIFT       8
#define UFS_SYS_CTRL_DWC_MPHY_RMMI_OBSV_STAT_TX_TST_RTOBSERVE_1_MASK        0x0000ff00
#define UFS_SYS_CTRL_DWC_MPHY_RMMI_OBSV_STAT_RX_TST_RTOBSERVE_0_SHIFT       16
#define UFS_SYS_CTRL_DWC_MPHY_RMMI_OBSV_STAT_RX_TST_RTOBSERVE_0_MASK        0x00ff0000
#define UFS_SYS_CTRL_DWC_MPHY_RMMI_OBSV_STAT_RX_TST_RTOBSERVE_1_SHIFT       24
#define UFS_SYS_CTRL_DWC_MPHY_RMMI_OBSV_STAT_RX_TST_RTOBSERVE_1_MASK        0xff000000
#define UFS_SYS_CTRL_UFS_DEVC_RST_N                      0x0048
#define UFS_SYS_CTRL_UFS_DEVC_RST_N_UFS_RST_N_SHIFT                         0
#define UFS_SYS_CTRL_UFS_DEVC_RST_N_UFS_RST_N_MASK                          0x00000001
#define UFS_SYS_CTRL_UFS_MEM_CTRL_0                      0x004c
#define UFS_SYS_CTRL_UFS_MEM_CTRL_0_SC_UFS_MEM_DS_SHIFT                     0
#define UFS_SYS_CTRL_UFS_MEM_CTRL_0_SC_UFS_MEM_DS_MASK                      0x00000001
#define UFS_SYS_CTRL_UFS_MEM_CTRL_1                      0x0050
#define UFS_SYS_CTRL_UFS_MEM_CTRL_2                      0x0054
#define UFS_SYS_CTRL_UFS_MEM_CTRL_3                      0x0058
#define UFS_SYS_CTRL_UFS_SYS_CAP                         0x005c
#define UFS_SYS_CTRL_UFS_SYS_CAP_UFS_CTRL_AWQOS_SHIFT                       0
#define UFS_SYS_CTRL_UFS_SYS_CAP_UFS_CTRL_AWQOS_MASK                        0x0000000f
#define UFS_SYS_CTRL_UFS_SYS_CAP_UFS_CTRL_ARQOS_SHIFT                       4
#define UFS_SYS_CTRL_UFS_SYS_CAP_UFS_CTRL_ARQOS_MASK                        0x000000f0
#define UFS_SYS_CTRL_UFS_SYS_CAP_SC_UFS_MEM_DS_ACK_SHIFT                    16
#define UFS_SYS_CTRL_UFS_SYS_CAP_SC_UFS_MEM_DS_ACK_MASK                     0x00010000
#define UFS_SYS_CTRL_UFS_MISC_CTRL                       0x0060
#define UFS_SYS_CTRL_UFS_MISC_CTRL_CG_TICK1US_DIV_SHIFT                     0
#define UFS_SYS_CTRL_UFS_MISC_CTRL_CG_TICK1US_DIV_MASK                      0x0000ffff
#define UFS_SYS_CTRL_UFS_MISC_CTRL_UFS_MPHY_SRAM_EXT_SEL_SHIFT              16
#define UFS_SYS_CTRL_UFS_MISC_CTRL_UFS_MPHY_SRAM_EXT_SEL_MASK               0x00010000
#define UFS_SYS_CTRL_UFS_MISC_CTRL_UFS_APB_CLKR_BYPASS_SHIFT                17
#define UFS_SYS_CTRL_UFS_MISC_CTRL_UFS_APB_CLKR_BYPASS_MASK                 0x00020000
#define UFS_SYS_CTRL_UFS_ERR_INT_CLEAR                   0x0064
#define UFS_SYS_CTRL_UFS_ERR_INT_CLEAR_ESI_AXI_RESP_ERR_CLEAR_SHIFT         0
#define UFS_SYS_CTRL_UFS_ERR_INT_CLEAR_ESI_GIF_SACCEPT_TIMEOUT_CLEAR_SHIFT  1
#define UFS_SYS_CTRL_UFS_ERR_INT_CLEAR_HS2LS_ERR_INT_CLEAR_SHIFT            2
#define UFS_SYS_CTRL_UFS_ERR_INT_MASK                    0x0068
#define UFS_SYS_CTRL_UFS_ERR_INT_MASK_ESI_AXI_RESP_ERR_MASK_SHIFT           0
#define UFS_SYS_CTRL_UFS_ERR_INT_MASK_ESI_AXI_RESP_ERR_MASK_MASK            0x00000001
#define UFS_SYS_CTRL_UFS_ERR_INT_MASK_ESI_GIF_SACCEPT_TIMEOUT_MASK_SHIFT    1
#define UFS_SYS_CTRL_UFS_ERR_INT_MASK_ESI_GIF_SACCEPT_TIMEOUT_MASK_MASK     0x00000002
#define UFS_SYS_CTRL_UFS_ERR_INT_MASK_HS2LS_ERR_INT_MASK_SHIFT              2
#define UFS_SYS_CTRL_UFS_ERR_INT_MASK_HS2LS_ERR_INT_MASK_MASK               0x00000004
#define UFS_SYS_CTRL_UFS_ERR_INT_STATUS                  0x006c
#define UFS_SYS_CTRL_UFS_ERR_INT_STATUS_ESI_AXI_RESP_ERR_STATUS_SHIFT       0
#define UFS_SYS_CTRL_UFS_ERR_INT_STATUS_ESI_AXI_RESP_ERR_STATUS_MASK        0x00000001
#define UFS_SYS_CTRL_UFS_ERR_INT_STATUS_ESI_GIF_SACCEPT_TIMEOUT_STATUS_SHIFT 1
#define UFS_SYS_CTRL_UFS_ERR_INT_STATUS_ESI_GIF_SACCEPT_TIMEOUT_STATUS_MASK  0x00000002
#define UFS_SYS_CTRL_UFS_ERR_INT_STATUS_HS2LS_ERR_INT_STATUS_SHIFT          2
#define UFS_SYS_CTRL_UFS_ERR_INT_STATUS_HS2LS_ERR_INT_STATUS_MASK           0x00000004
#define UFS_SYS_CTRL_UFS_ESI_MASK_2                      0x0070
#define UFS_SYS_CTRL_UFS_ESI_MASK_1                      0x0074
#define UFS_SYS_CTRL_UFS_ESI_MASK_0                      0x0078
#define UFS_SYS_CTRL_UFS_ESI_PEND_STAT_2                 0x007c
#define UFS_SYS_CTRL_UFS_ESI_PEND_STAT_1                 0x0080
#define UFS_SYS_CTRL_UFS_ESI_PEND_STAT_0                 0x0084
#define UFS_SYS_CTRL_UFS_ESI_GITS_ADDR                   0x0088
#define UFS_SYS_CTRL_UFS_ESI_DEVICE_ID                   0x008c
#define UFS_SYS_CTRL_UFS_ESI_DEVICE_ID_ESI_DEVICEID_SHIFT                   0
#define UFS_SYS_CTRL_UFS_ESI_DEVICE_ID_ESI_DEVICEID_MASK                    0x000000ff
#define UFS_SYS_CTRL_UFS_ESI_DEVICE_ID_ESI_GIF_SACCEPT_TIMEOUT_VALUE_SHIFT  16
#define UFS_SYS_CTRL_UFS_ESI_DEVICE_ID_ESI_GIF_SACCEPT_TIMEOUT_VALUE_MASK   0xffff0000
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL                   0x0090
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_APB0_IF_SEL_SHIFT                0
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_APB0_IF_SEL_MASK                 0x00000001
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_APB0_IF_MODE_SHIFT               1
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_APB0_IF_MODE_MASK                0x00000006
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_RX1_RESET_SHIFT                  3
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_RX1_RESET_MASK                   0x00000008
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_TX1_RESET_SHIFT                  4
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_TX1_RESET_MASK                   0x00000010
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_TX0_RESET_SHIFT                  5
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_TX0_RESET_MASK                   0x00000020
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_RX0_RESET_SHIFT                  6
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_RX0_RESET_MASK                   0x00000040
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_FW_CLK_ACK_SHIFT                 7
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_FW_CLK_ACK_MASK                  0x00000080
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_REF_RANGE_SHIFT                  8
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_REF_RANGE_MASK                   0x00000f00
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_REF_ALT_CLK_LP_SEL_SHIFT         12
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_REF_ALT_CLK_LP_SEL_MASK          0x00001000
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_REF_CLK_EN_SHIFT                 13
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_REF_CLK_EN_MASK                  0x00002000
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_REF_USE_PAD_SHIFT                14
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_REF_USE_PAD_MASK                 0x00004000
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_PG_MODE_EN_SHIFT                 15
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_PG_MODE_EN_MASK                  0x00008000
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_ENABLE_SHIFT                     16
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_ENABLE_MASK                      0x00010000
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_FREQ_MON_EN_SHIFT                20
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_ATE_FREQ_MON_EN_MASK                 0x00100000
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_PCLK_FREQ_SHIFT                      24
#define UFS_SYS_CTRL_DWC_MPHY_ATE_CTRL_PCLK_FREQ_MASK                       0xff000000
#define UFS_SYS_CTRL_DWC_MPHY_ATE_STAT                   0x0094
#define UFS_SYS_CTRL_DWC_MPHY_ATE_STAT_ATE_FW_CLK_REQ_SHIFT                 0
#define UFS_SYS_CTRL_DWC_MPHY_ATE_STAT_ATE_FW_CLK_REQ_MASK                  0x00000001
#define UFS_SYS_CTRL_DWC_MPHY_ATE_STAT_ATE_DCO_CLKCAL_SHIFT                 1
#define UFS_SYS_CTRL_DWC_MPHY_ATE_STAT_ATE_DCO_CLKCAL_MASK                  0x00000002
#define UFS_SYS_CTRL_DWC_MPHY_ATE_STAT_REF_DCO_CLKCAL_FREQ_VALID_SHIFT      2
#define UFS_SYS_CTRL_DWC_MPHY_ATE_STAT_REF_DCO_CLKCAL_FREQ_VALID_MASK       0x00000004
#define UFS_SYS_CTRL_DWC_MPHY_ATE_STAT_TX_PWM_CLK_FREQ_VALID_SHIFT          3
#define UFS_SYS_CTRL_DWC_MPHY_ATE_STAT_TX_PWM_CLK_FREQ_VALID_MASK           0x00000008
#define UFS_SYS_CTRL_DWC_MPHY_ATE_STAT_REF_DCO_CLKCAL_FREQ_SHIFT            4
#define UFS_SYS_CTRL_DWC_MPHY_ATE_STAT_REF_DCO_CLKCAL_FREQ_MASK             0x00001ff0
#define UFS_SYS_CTRL_DWC_MPHY_ATE_STAT_TX_PWM_CLK_FREQ_SHIFT                16
#define UFS_SYS_CTRL_DWC_MPHY_ATE_STAT_TX_PWM_CLK_FREQ_MASK                 0x01ff0000
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD                   0x0098
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_TX_MAIN_RESET_0_SHIFT            0
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_TX_MAIN_RESET_0_MASK             0x00000001
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_TX_MAIN_RESET_1_SHIFT            1
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_TX_MAIN_RESET_1_MASK             0x00000002
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_TX_RESET_0_SHIFT                 2
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_TX_RESET_0_MASK                  0x00000004
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_TX_RESET_1_SHIFT                 3
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_TX_RESET_1_MASK                  0x00000008
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_RX_MAIN_RESET_0_SHIFT            4
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_RX_MAIN_RESET_0_MASK             0x00000010
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_RX_MAIN_RESET_1_SHIFT            5
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_RX_MAIN_RESET_1_MASK             0x00000020
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_RX_RESET_0_SHIFT                 6
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_RX_RESET_0_MASK                  0x00000040
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_RX_RESET_1_SHIFT                 7
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_RX_RESET_1_MASK                  0x00000080
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_TX0_FLYOVER_EN_SHIFT             8
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_TX0_FLYOVER_EN_MASK              0x00000100
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_TX1_FLYOVER_EN_SHIFT             9
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_TX1_FLYOVER_EN_MASK              0x00000200
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_RX0_FLYOVER_EN_SHIFT             10
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_RX0_FLYOVER_EN_MASK              0x00000400
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_RX1_FLYOVER_EN_SHIFT             11
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_RX1_FLYOVER_EN_MASK              0x00000800
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_PHY_RESET_SHIFT                  12
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_PHY_RESET_MASK                   0x00001000
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_SRAM_BYPASS_MODE_SHIFT           13
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_SRAM_BYPASS_MODE_MASK            0x00006000
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_SRAM_BOOTLOAD_BYPASS_MODE_SHIFT  15
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_SRAM_BOOTLOAD_BYPASS_MODE_MASK   0x00018000
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_SRAM_EXT_LD_DONE_SHIFT           17
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_SRAM_EXT_LD_DONE_MASK            0x00020000
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_PMA_PWR_STABLE_SHIFT             18
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_PMA_PWR_STABLE_MASK              0x00040000
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_ANA_PWR_EN_SHIFT                 19
#define UFS_SYS_CTRL_DWC_MPHY_ATE_OVRD_ATE_ANA_PWR_EN_MASK                  0x00080000
#define UFS_SYS_CTRL_UFS_FPGA                            0x009c
#define UFS_SYS_CTRL_UFS_FPGA_FPGA_SFR_SEL_SHIFT                            0
#define UFS_SYS_CTRL_UFS_FPGA_FPGA_SFR_SEL_MASK                             0x00000001
#define UFS_SYS_CTRL_UFS_FPGA_FPGA_UFS_VCC_2P5_EN_SHIFT                     2
#define UFS_SYS_CTRL_UFS_FPGA_FPGA_UFS_VCC_2P5_EN_MASK                      0x00000004
#define UFS_SYS_CTRL_UFS_FPGA_FPGA_UFS_VCCQ_1P2_EN_SHIFT                    3
#define UFS_SYS_CTRL_UFS_FPGA_FPGA_UFS_VCCQ_1P2_EN_MASK                     0x00000008
#define UFS_SYS_CTRL_UFS_FPGA_FPGA_BLOCK_SEL_OVRD_EN_SHIFT                  4
#define UFS_SYS_CTRL_UFS_FPGA_FPGA_BLOCK_SEL_OVRD_EN_MASK                   0x00000010
#define UFS_SYS_CTRL_UFS_FPGA_FPGA_BLOCK_SEL_SHIFT                          5
#define UFS_SYS_CTRL_UFS_FPGA_FPGA_BLOCK_SEL_MASK                           0x000000e0
#define UFS_SYS_CTRL_UFS_ELA_EN                          0x00a0
#define UFS_SYS_CTRL_UFS_TESTPIN                         0x00a4
#define UFS_SYS_CTRL_UFS_TESTPIN_UFS_TESTPIN_GRP_SEL_SHIFT                  0
#define UFS_SYS_CTRL_UFS_TESTPIN_UFS_TESTPIN_GRP_SEL_MASK                   0x000000ff
#define UFS_SYS_CTRL_UFS_STATE_SEQ_TRACE_EN              0x00a8
#define UFS_SYS_CTRL_UFS_STATE_SEQ_TRACE_EN_L15_STATE_FSM_SEQ_EN_SHIFT      0
#define UFS_SYS_CTRL_UFS_STATE_SEQ_TRACE_EN_L15_STATE_FSM_SEQ_EN_MASK       0x00000001
#define UFS_SYS_CTRL_UFS_STATE_SEQ_TRACE_EN_AH8_STATE_FSM_SEQ_EN_SHIFT      1
#define UFS_SYS_CTRL_UFS_STATE_SEQ_TRACE_EN_AH8_STATE_FSM_SEQ_EN_MASK       0x00000002
#define UFS_SYS_CTRL_UFS_STATE_SEQ_TRACE_EN_LPM_STATE_FSM_SEQ_EN_SHIFT      2
#define UFS_SYS_CTRL_UFS_STATE_SEQ_TRACE_EN_LPM_STATE_FSM_SEQ_EN_MASK       0x00000004
#define UFS_SYS_CTRL_UFS_STATE_SEQ_TRACE_EN_L2_STATE_FSM_SEQ_EN_SHIFT       3
#define UFS_SYS_CTRL_UFS_STATE_SEQ_TRACE_EN_L2_STATE_FSM_SEQ_EN_MASK        0x00000008
#define UFS_SYS_CTRL_UFS_STATE_SEQ_TRACE_EN_MRX0_STATE_FSM_SEQ_EN_SHIFT     4
#define UFS_SYS_CTRL_UFS_STATE_SEQ_TRACE_EN_MRX0_STATE_FSM_SEQ_EN_MASK      0x00000010
#define UFS_SYS_CTRL_UFS_STATE_SEQ_TRACE_EN_MTX0_STATE_FSM_SEQ_EN_SHIFT     5
#define UFS_SYS_CTRL_UFS_STATE_SEQ_TRACE_EN_MTX0_STATE_FSM_SEQ_EN_MASK      0x00000020
#define UFS_SYS_CTRL_UFS_STATE_SEQ_TRACE_EN_RXLSS_STATE_FSM_SEQ_EN_SHIFT    6
#define UFS_SYS_CTRL_UFS_STATE_SEQ_TRACE_EN_RXLSS_STATE_FSM_SEQ_EN_MASK     0x00000040
#define UFS_SYS_CTRL_UFS_STATE_SEQ_TRACE_EN_TXLSS_STATE_FSM_SEQ_EN_SHIFT    7
#define UFS_SYS_CTRL_UFS_STATE_SEQ_TRACE_EN_TXLSS_STATE_FSM_SEQ_EN_MASK     0x00000080
#define UFS_SYS_CTRL_L15_STATE_0                         0x00ac
#define UFS_SYS_CTRL_L15_STATE_0_L15_FSM_STATE_S0_SHIFT                     0
#define UFS_SYS_CTRL_L15_STATE_0_L15_FSM_STATE_S0_MASK                      0x0000007f
#define UFS_SYS_CTRL_L15_STATE_0_L15_FSM_STATE_S1_SHIFT                     8
#define UFS_SYS_CTRL_L15_STATE_0_L15_FSM_STATE_S1_MASK                      0x00007f00
#define UFS_SYS_CTRL_L15_STATE_0_L15_FSM_STATE_S2_SHIFT                     16
#define UFS_SYS_CTRL_L15_STATE_0_L15_FSM_STATE_S2_MASK                      0x007f0000
#define UFS_SYS_CTRL_L15_STATE_0_L15_FSM_STATE_S3_SHIFT                     24
#define UFS_SYS_CTRL_L15_STATE_0_L15_FSM_STATE_S3_MASK                      0x7f000000
#define UFS_SYS_CTRL_L15_STATE_1                         0x00b0
#define UFS_SYS_CTRL_L15_STATE_1_L15_FSM_STATE_S4_SHIFT                     0
#define UFS_SYS_CTRL_L15_STATE_1_L15_FSM_STATE_S4_MASK                      0x0000007f
#define UFS_SYS_CTRL_L15_STATE_1_L15_FSM_STATE_S5_SHIFT                     8
#define UFS_SYS_CTRL_L15_STATE_1_L15_FSM_STATE_S5_MASK                      0x00007f00
#define UFS_SYS_CTRL_L15_STATE_1_L15_FSM_STATE_S6_SHIFT                     16
#define UFS_SYS_CTRL_L15_STATE_1_L15_FSM_STATE_S6_MASK                      0x007f0000
#define UFS_SYS_CTRL_L15_STATE_1_L15_FSM_STATE_S7_SHIFT                     24
#define UFS_SYS_CTRL_L15_STATE_1_L15_FSM_STATE_S7_MASK                      0x7f000000
#define UFS_SYS_CTRL_AH8_STATE                           0x00b4
#define UFS_SYS_CTRL_AH8_STATE_AH8_FSM_STATE_S0_SHIFT                       0
#define UFS_SYS_CTRL_AH8_STATE_AH8_FSM_STATE_S0_MASK                        0x0000000f
#define UFS_SYS_CTRL_AH8_STATE_AH8_FSM_STATE_S1_SHIFT                       4
#define UFS_SYS_CTRL_AH8_STATE_AH8_FSM_STATE_S1_MASK                        0x000000f0
#define UFS_SYS_CTRL_AH8_STATE_AH8_FSM_STATE_S2_SHIFT                       8
#define UFS_SYS_CTRL_AH8_STATE_AH8_FSM_STATE_S2_MASK                        0x00000f00
#define UFS_SYS_CTRL_AH8_STATE_AH8_FSM_STATE_S3_SHIFT                       12
#define UFS_SYS_CTRL_AH8_STATE_AH8_FSM_STATE_S3_MASK                        0x0000f000
#define UFS_SYS_CTRL_AH8_STATE_AH8_FSM_STATE_S4_SHIFT                       16
#define UFS_SYS_CTRL_AH8_STATE_AH8_FSM_STATE_S4_MASK                        0x000f0000
#define UFS_SYS_CTRL_AH8_STATE_AH8_FSM_STATE_S5_SHIFT                       20
#define UFS_SYS_CTRL_AH8_STATE_AH8_FSM_STATE_S5_MASK                        0x00f00000
#define UFS_SYS_CTRL_AH8_STATE_AH8_FSM_STATE_S6_SHIFT                       24
#define UFS_SYS_CTRL_AH8_STATE_AH8_FSM_STATE_S6_MASK                        0x0f000000
#define UFS_SYS_CTRL_AH8_STATE_AH8_FSM_STATE_S7_SHIFT                       28
#define UFS_SYS_CTRL_AH8_STATE_AH8_FSM_STATE_S7_MASK                        0xf0000000
#define UFS_SYS_CTRL_LPM_STATE                           0x00b8
#define UFS_SYS_CTRL_LPM_STATE_LPM_FSM_STATE_S0_SHIFT                       0
#define UFS_SYS_CTRL_LPM_STATE_LPM_FSM_STATE_S0_MASK                        0x00000007
#define UFS_SYS_CTRL_LPM_STATE_LPM_FSM_STATE_S1_SHIFT                       4
#define UFS_SYS_CTRL_LPM_STATE_LPM_FSM_STATE_S1_MASK                        0x00000070
#define UFS_SYS_CTRL_LPM_STATE_LPM_FSM_STATE_S2_SHIFT                       8
#define UFS_SYS_CTRL_LPM_STATE_LPM_FSM_STATE_S2_MASK                        0x00000700
#define UFS_SYS_CTRL_LPM_STATE_LPM_FSM_STATE_S3_SHIFT                       12
#define UFS_SYS_CTRL_LPM_STATE_LPM_FSM_STATE_S3_MASK                        0x00007000
#define UFS_SYS_CTRL_LPM_STATE_LPM_FSM_STATE_S4_SHIFT                       16
#define UFS_SYS_CTRL_LPM_STATE_LPM_FSM_STATE_S4_MASK                        0x00070000
#define UFS_SYS_CTRL_LPM_STATE_LPM_FSM_STATE_S5_SHIFT                       20
#define UFS_SYS_CTRL_LPM_STATE_LPM_FSM_STATE_S5_MASK                        0x00700000
#define UFS_SYS_CTRL_LPM_STATE_LPM_FSM_STATE_S6_SHIFT                       24
#define UFS_SYS_CTRL_LPM_STATE_LPM_FSM_STATE_S6_MASK                        0x07000000
#define UFS_SYS_CTRL_LPM_STATE_LPM_FSM_STATE_S7_SHIFT                       28
#define UFS_SYS_CTRL_LPM_STATE_LPM_FSM_STATE_S7_MASK                        0x70000000
#define UFS_SYS_CTRL_L2_STATE                            0x00bc
#define UFS_SYS_CTRL_L2_STATE_L2_FSM_STATE_S0_SHIFT                         0
#define UFS_SYS_CTRL_L2_STATE_L2_FSM_STATE_S0_MASK                          0x00000007
#define UFS_SYS_CTRL_L2_STATE_L2_FSM_STATE_S1_SHIFT                         4
#define UFS_SYS_CTRL_L2_STATE_L2_FSM_STATE_S1_MASK                          0x00000070
#define UFS_SYS_CTRL_L2_STATE_L2_FSM_STATE_S2_SHIFT                         8
#define UFS_SYS_CTRL_L2_STATE_L2_FSM_STATE_S2_MASK                          0x00000700
#define UFS_SYS_CTRL_L2_STATE_L2_FSM_STATE_S3_SHIFT                         12
#define UFS_SYS_CTRL_L2_STATE_L2_FSM_STATE_S3_MASK                          0x00007000
#define UFS_SYS_CTRL_L2_STATE_L2_FSM_STATE_S4_SHIFT                         16
#define UFS_SYS_CTRL_L2_STATE_L2_FSM_STATE_S4_MASK                          0x00070000
#define UFS_SYS_CTRL_L2_STATE_L2_FSM_STATE_S5_SHIFT                         20
#define UFS_SYS_CTRL_L2_STATE_L2_FSM_STATE_S5_MASK                          0x00700000
#define UFS_SYS_CTRL_L2_STATE_L2_FSM_STATE_S6_SHIFT                         24
#define UFS_SYS_CTRL_L2_STATE_L2_FSM_STATE_S6_MASK                          0x07000000
#define UFS_SYS_CTRL_L2_STATE_L2_FSM_STATE_S7_SHIFT                         28
#define UFS_SYS_CTRL_L2_STATE_L2_FSM_STATE_S7_MASK                          0x70000000
#define UFS_SYS_CTRL_MRX0_STATE                          0x00c0
#define UFS_SYS_CTRL_MRX0_STATE_MRX0_FSM_STATE_S0_SHIFT                     0
#define UFS_SYS_CTRL_MRX0_STATE_MRX0_FSM_STATE_S0_MASK                      0x0000000f
#define UFS_SYS_CTRL_MRX0_STATE_MRX0_FSM_STATE_S1_SHIFT                     4
#define UFS_SYS_CTRL_MRX0_STATE_MRX0_FSM_STATE_S1_MASK                      0x000000f0
#define UFS_SYS_CTRL_MRX0_STATE_MRX0_FSM_STATE_S2_SHIFT                     8
#define UFS_SYS_CTRL_MRX0_STATE_MRX0_FSM_STATE_S2_MASK                      0x00000f00
#define UFS_SYS_CTRL_MRX0_STATE_MRX0_FSM_STATE_S3_SHIFT                     12
#define UFS_SYS_CTRL_MRX0_STATE_MRX0_FSM_STATE_S3_MASK                      0x0000f000
#define UFS_SYS_CTRL_MRX0_STATE_MRX0_FSM_STATE_S4_SHIFT                     16
#define UFS_SYS_CTRL_MRX0_STATE_MRX0_FSM_STATE_S4_MASK                      0x000f0000
#define UFS_SYS_CTRL_MRX0_STATE_MRX0_FSM_STATE_S5_SHIFT                     20
#define UFS_SYS_CTRL_MRX0_STATE_MRX0_FSM_STATE_S5_MASK                      0x00f00000
#define UFS_SYS_CTRL_MRX0_STATE_MRX0_FSM_STATE_S6_SHIFT                     24
#define UFS_SYS_CTRL_MRX0_STATE_MRX0_FSM_STATE_S6_MASK                      0x0f000000
#define UFS_SYS_CTRL_MRX0_STATE_MRX0_FSM_STATE_S7_SHIFT                     28
#define UFS_SYS_CTRL_MRX0_STATE_MRX0_FSM_STATE_S7_MASK                      0xf0000000
#define UFS_SYS_CTRL_MTX0_STATE                          0x00c4
#define UFS_SYS_CTRL_MTX0_STATE_MTX0_FSM_STATE_S0_SHIFT                     0
#define UFS_SYS_CTRL_MTX0_STATE_MTX0_FSM_STATE_S0_MASK                      0x0000000f
#define UFS_SYS_CTRL_MTX0_STATE_MTX0_FSM_STATE_S1_SHIFT                     4
#define UFS_SYS_CTRL_MTX0_STATE_MTX0_FSM_STATE_S1_MASK                      0x000000f0
#define UFS_SYS_CTRL_MTX0_STATE_MTX0_FSM_STATE_S2_SHIFT                     8
#define UFS_SYS_CTRL_MTX0_STATE_MTX0_FSM_STATE_S2_MASK                      0x00000f00
#define UFS_SYS_CTRL_MTX0_STATE_MTX0_FSM_STATE_S3_SHIFT                     12
#define UFS_SYS_CTRL_MTX0_STATE_MTX0_FSM_STATE_S3_MASK                      0x0000f000
#define UFS_SYS_CTRL_MTX0_STATE_MTX0_FSM_STATE_S4_SHIFT                     16
#define UFS_SYS_CTRL_MTX0_STATE_MTX0_FSM_STATE_S4_MASK                      0x000f0000
#define UFS_SYS_CTRL_MTX0_STATE_MTX0_FSM_STATE_S5_SHIFT                     20
#define UFS_SYS_CTRL_MTX0_STATE_MTX0_FSM_STATE_S5_MASK                      0x00f00000
#define UFS_SYS_CTRL_MTX0_STATE_MTX0_FSM_STATE_S6_SHIFT                     24
#define UFS_SYS_CTRL_MTX0_STATE_MTX0_FSM_STATE_S6_MASK                      0x0f000000
#define UFS_SYS_CTRL_MTX0_STATE_MTX0_FSM_STATE_S7_SHIFT                     28
#define UFS_SYS_CTRL_MTX0_STATE_MTX0_FSM_STATE_S7_MASK                      0xf0000000
#define UFS_SYS_CTRL_RXLSS_STATE_0                       0x00c8
#define UFS_SYS_CTRL_RXLSS_STATE_0_RXLSS_FSM_STATE_S0_SHIFT                 0
#define UFS_SYS_CTRL_RXLSS_STATE_0_RXLSS_FSM_STATE_S0_MASK                  0x000000ff
#define UFS_SYS_CTRL_RXLSS_STATE_0_RXLSS_FSM_STATE_S1_SHIFT                 8
#define UFS_SYS_CTRL_RXLSS_STATE_0_RXLSS_FSM_STATE_S1_MASK                  0x0000ff00
#define UFS_SYS_CTRL_RXLSS_STATE_0_RXLSS_FSM_STATE_S2_SHIFT                 16
#define UFS_SYS_CTRL_RXLSS_STATE_0_RXLSS_FSM_STATE_S2_MASK                  0x00ff0000
#define UFS_SYS_CTRL_RXLSS_STATE_0_RXLSS_FSM_STATE_S3_SHIFT                 24
#define UFS_SYS_CTRL_RXLSS_STATE_0_RXLSS_FSM_STATE_S3_MASK                  0xff000000
#define UFS_SYS_CTRL_RXLSS_STATE_1                       0x00cc
#define UFS_SYS_CTRL_RXLSS_STATE_1_RXLSS_FSM_STATE_S4_SHIFT                 0
#define UFS_SYS_CTRL_RXLSS_STATE_1_RXLSS_FSM_STATE_S4_MASK                  0x000000ff
#define UFS_SYS_CTRL_RXLSS_STATE_1_RXLSS_FSM_STATE_S5_SHIFT                 8
#define UFS_SYS_CTRL_RXLSS_STATE_1_RXLSS_FSM_STATE_S5_MASK                  0x0000ff00
#define UFS_SYS_CTRL_RXLSS_STATE_1_RXLSS_FSM_STATE_S6_SHIFT                 16
#define UFS_SYS_CTRL_RXLSS_STATE_1_RXLSS_FSM_STATE_S6_MASK                  0x00ff0000
#define UFS_SYS_CTRL_RXLSS_STATE_1_RXLSS_FSM_STATE_S7_SHIFT                 24
#define UFS_SYS_CTRL_RXLSS_STATE_1_RXLSS_FSM_STATE_S7_MASK                  0xff000000
#define UFS_SYS_CTRL_TXLSS_STATE_0                       0x00d0
#define UFS_SYS_CTRL_TXLSS_STATE_0_TXLSS_FSM_STATE_S0_SHIFT                 0
#define UFS_SYS_CTRL_TXLSS_STATE_0_TXLSS_FSM_STATE_S0_MASK                  0x000000ff
#define UFS_SYS_CTRL_TXLSS_STATE_0_TXLSS_FSM_STATE_S1_SHIFT                 8
#define UFS_SYS_CTRL_TXLSS_STATE_0_TXLSS_FSM_STATE_S1_MASK                  0x0000ff00
#define UFS_SYS_CTRL_TXLSS_STATE_0_TXLSS_FSM_STATE_S2_SHIFT                 16
#define UFS_SYS_CTRL_TXLSS_STATE_0_TXLSS_FSM_STATE_S2_MASK                  0x00ff0000
#define UFS_SYS_CTRL_TXLSS_STATE_0_TXLSS_FSM_STATE_S3_SHIFT                 24
#define UFS_SYS_CTRL_TXLSS_STATE_0_TXLSS_FSM_STATE_S3_MASK                  0xff000000
#define UFS_SYS_CTRL_TXLSS_STATE_1                       0x00d4
#define UFS_SYS_CTRL_TXLSS_STATE_1_TXLSS_FSM_STATE_S4_SHIFT                 0
#define UFS_SYS_CTRL_TXLSS_STATE_1_TXLSS_FSM_STATE_S4_MASK                  0x000000ff
#define UFS_SYS_CTRL_TXLSS_STATE_1_TXLSS_FSM_STATE_S5_SHIFT                 8
#define UFS_SYS_CTRL_TXLSS_STATE_1_TXLSS_FSM_STATE_S5_MASK                  0x0000ff00
#define UFS_SYS_CTRL_TXLSS_STATE_1_TXLSS_FSM_STATE_S6_SHIFT                 16
#define UFS_SYS_CTRL_TXLSS_STATE_1_TXLSS_FSM_STATE_S6_MASK                  0x00ff0000
#define UFS_SYS_CTRL_TXLSS_STATE_1_TXLSS_FSM_STATE_S7_SHIFT                 24
#define UFS_SYS_CTRL_TXLSS_STATE_1_TXLSS_FSM_STATE_S7_MASK                  0xff000000
#define UFS_SYS_CTRL_REGFILE_CGBYPASS                    0x00d8
#define UFS_SYS_CTRL_REGFILE_CGBYPASS_REGFILE_CGBYPASS_SHIFT                0
#define UFS_SYS_CTRL_REGFILE_CGBYPASS_REGFILE_CGBYPASS_MASK                 0x00000001


typedef union {
    unsigned int val;
    struct {
        unsigned int reset_n_sw        :  1;
        unsigned int aresetn_sw        :  1;
        unsigned int ufs_esi_rst_n_sw  :  1;
        unsigned int ufs_misc_rst_n_sw :  1;
        unsigned int mphy_apb_rst_n_sw :  1;
        unsigned int reserved_0        :  3;
        unsigned int sramc_clk_en_sw   :  1;
        unsigned int ref_alt_clk_en_sw :  1;
        unsigned int reserved_1        : 22;
    } reg;
}ufs_sys_ctrl_ufs_sys_rst_swgt_w1s_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int reset_n_sw        :  1;
        unsigned int aresetn_sw        :  1;
        unsigned int ufs_esi_rst_n_sw  :  1;
        unsigned int ufs_misc_rst_n_sw :  1;
        unsigned int mphy_apb_rst_n_sw :  1;
        unsigned int reserved_0        :  3;
        unsigned int sramc_clk_en_sw   :  1;
        unsigned int ref_alt_clk_en_sw :  1;
        unsigned int reserved_1        : 22;
    } reg;
}ufs_sys_ctrl_ufs_sys_rst_swgt_w1c_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int reset_n_sw        :  1;
        unsigned int aresetn_sw        :  1;
        unsigned int ufs_esi_rst_n_sw  :  1;
        unsigned int ufs_misc_rst_n_sw :  1;
        unsigned int mphy_apb_rst_n_sw :  1;
        unsigned int reserved_0        :  3;
        unsigned int sramc_clk_en_sw   :  1;
        unsigned int ref_alt_clk_en_sw :  1;
        unsigned int reserved_1        : 22;
    } reg;
}ufs_sys_ctrl_ufs_sys_rst_swgt_ro_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int reserved_0 : 32;
    } reg;
}ufs_sys_ctrl_rsvd_0_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int reserved_1 : 32;
    } reg;
}ufs_sys_ctrl_rsvd_1_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int ies_en_mask     :  1;
        unsigned int la_resetmodereq :  1;
        unsigned int reserved_0      : 30;
    } reg;
}ufs_sys_ctrl_dwc_ufshc_ctrl_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int ufs_idle_ind        :  1;
        unsigned int tx_pwrenbl          :  2;
        unsigned int rx_pwrenbl          :  2;
        unsigned int ufs_hibernate_state :  1;
        unsigned int lp_resetcomplete    :  1;
        unsigned int reserved_0          :  1;
        unsigned int cg_sysclkreq        :  1;
        unsigned int cg_clk_treq         :  1;
        unsigned int cg_lp_clk_treq      :  1;
        unsigned int cg_pclkreq          :  1;
        unsigned int dwc_mphy_cfgclk_en  :  1;
        unsigned int lp_rxclk_sel        :  1;
        unsigned int cg_pxrxusable       :  2;
        unsigned int reserved_1          : 16;
    } reg;
}ufs_sys_ctrl_dwc_ufshc_stat_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int reserved_0 : 32;
    } reg;
}ufs_sys_ctrl_rsvd_4_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int cfg_clock_sel             :  3;
        unsigned int ref_clock_sel             :  3;
        unsigned int mphy_cfg                  :  2;
        unsigned int res_ext_rcal              :  6;
        unsigned int res_ext_en                :  1;
        unsigned int ana_pwr_en_override       :  1;
        unsigned int sram_bypass_mode          :  2;
        unsigned int sram_bootload_bypass_mode :  2;
        unsigned int sram_ext_ld_done          :  1;
        unsigned int reserved_0                :  3;
        unsigned int ref_pre_vreg_bypass       :  1;
        unsigned int reserved_1                :  3;
        unsigned int dwc_mphy_ulph8_en         :  1;
        unsigned int dwc_mphy_cfgclk_cgen      :  1;
        unsigned int dwc_mphy_refclk_cgen      :  1;
        unsigned int reserved_2                :  1;
    } reg;
}ufs_sys_ctrl_dwc_mphy_ctrl_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int phy_reset               :  1;
        unsigned int mphy_disable_ovrd_v     :  1;
        unsigned int tx_reset_0_ovrd_v       :  1;
        unsigned int tx_reset_1_ovrd_v       :  1;
        unsigned int tx_main_reset_0_ovrd_v  :  1;
        unsigned int tx_main_reset_1_ovrd_v  :  1;
        unsigned int rx_reset_0_ovrd_v       :  1;
        unsigned int rx_reset_1_ovrd_v       :  1;
        unsigned int rx_main_reset_0_ovrd_v  :  1;
        unsigned int rx_main_reset_1_ovrd_v  :  1;
        unsigned int reserved_0              :  7;
        unsigned int mphy_disable_ovrd_en    :  1;
        unsigned int tx_reset_0_ovrd_en      :  1;
        unsigned int tx_reset_1_ovrd_en      :  1;
        unsigned int tx_main_reset_0_ovrd_en :  1;
        unsigned int tx_main_reset_1_ovrd_en :  1;
        unsigned int rx_reset_0_ovrd_en      :  1;
        unsigned int rx_reset_1_ovrd_en      :  1;
        unsigned int rx_main_reset_0_ovrd_en :  1;
        unsigned int rx_main_reset_1_ovrd_en :  1;
        unsigned int reserved_1              :  6;
    } reg;
}ufs_sys_ctrl_dwc_mphy_rst_ovrd_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sram_init_done :  1;
        unsigned int ref_clk_req    :  1;
        unsigned int tx_busy_0      :  1;
        unsigned int tx_busy_1      :  1;
        unsigned int rx_busy_0      :  1;
        unsigned int rx_busy_1      :  1;
        unsigned int tx_cfgrdyn_0   :  1;
        unsigned int tx_cfgrdyn_1   :  1;
        unsigned int rx_cfgrdyn_0   :  1;
        unsigned int rx_cfgrdyn_1   :  1;
        unsigned int rx_sq_rcvd_0   :  1;
        unsigned int rx_sq_rcvd_1   :  1;
        unsigned int ana_pwr_stable :  1;
        unsigned int dtb_out        :  2;
        unsigned int reserved_0     : 17;
    } reg;
}ufs_sys_ctrl_dwc_mphy_stat_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int rx1_flyover_en :  1;
        unsigned int rx0_flyover_en :  1;
        unsigned int tx1_flyover_en :  1;
        unsigned int tx0_flyover_en :  1;
        unsigned int reserved_0     : 28;
    } reg;
}ufs_sys_ctrl_dwc_mphy_flovr_ctrl_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int rx1_flyover_data_p :  1;
        unsigned int rx1_flyover_data_m :  1;
        unsigned int rx0_flyover_data_p :  1;
        unsigned int rx0_flyover_data_m :  1;
        unsigned int reserved_0         : 28;
    } reg;
}ufs_sys_ctrl_dwc_mphy_flovr_stat_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int test_tx_ref_clk_en :  1;
        unsigned int test_stop_clk_en   :  1;
        unsigned int test_powerdown     :  1;
        unsigned int test_burnin        :  1;
        unsigned int test_flyover_en    :  1;
        unsigned int reserved_0         : 27;
    } reg;
}ufs_sys_ctrl_dwc_mphy_test_ctrl_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tx_tst_rtcontrol_0 :  8;
        unsigned int tx_tst_rtcontrol_1 :  8;
        unsigned int rx_tst_rtcontrol_0 :  8;
        unsigned int rx_tst_rtcontrol_1 :  8;
    } reg;
}ufs_sys_ctrl_dwc_mphy_rmmi_obsv_ctrl_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int tx_tst_rtobserve_0 :  8;
        unsigned int tx_tst_rtobserve_1 :  8;
        unsigned int rx_tst_rtobserve_0 :  8;
        unsigned int rx_tst_rtobserve_1 :  8;
    } reg;
}ufs_sys_ctrl_dwc_mphy_rmmi_obsv_stat_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int ufs_rst_n  :  1;
        unsigned int reserved_0 : 31;
    } reg;
}ufs_sys_ctrl_ufs_devc_rst_n_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int sc_ufs_mem_ds :  1;
        unsigned int reserved_0    : 15;
        unsigned int _bm_          : 16;
    } reg;
}ufs_sys_ctrl_ufs_mem_ctrl_0_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int bus_ctrl_0 : 32;
    } reg;
}ufs_sys_ctrl_ufs_mem_ctrl_1_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int bus_ctrl_1 : 32;
    } reg;
}ufs_sys_ctrl_ufs_mem_ctrl_2_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int bus_ctrl_2 : 32;
    } reg;
}ufs_sys_ctrl_ufs_mem_ctrl_3_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int ufs_ctrl_awqos    :  4;
        unsigned int ufs_ctrl_arqos    :  4;
        unsigned int reserved_0        :  8;
        unsigned int sc_ufs_mem_ds_ack :  1;
        unsigned int reserved_1        : 15;
    } reg;
}ufs_sys_ctrl_ufs_sys_cap_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int cg_tick1us_div        : 16;
        unsigned int ufs_mphy_sram_ext_sel :  1;
        unsigned int ufs_apb_clkr_bypass   :  1;
        unsigned int reserved_0            : 14;
    } reg;
}ufs_sys_ctrl_ufs_misc_ctrl_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int esi_axi_resp_err_clear        :  1;
        unsigned int esi_gif_saccept_timeout_clear :  1;
        unsigned int hs2ls_err_int_clear           :  1;
        unsigned int reserved_0                    : 29;
    } reg;
}ufs_sys_ctrl_ufs_err_int_clear_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int esi_axi_resp_err_mask        :  1;
        unsigned int esi_gif_saccept_timeout_mask :  1;
        unsigned int hs2ls_err_int_mask           :  1;
        unsigned int reserved_0                   : 29;
    } reg;
}ufs_sys_ctrl_ufs_err_int_mask_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int esi_axi_resp_err_status        :  1;
        unsigned int esi_gif_saccept_timeout_status :  1;
        unsigned int hs2ls_err_int_status           :  1;
        unsigned int reserved_0                     : 29;
    } reg;
}ufs_sys_ctrl_ufs_err_int_status_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int esi_mask_2 : 32;
    } reg;
}ufs_sys_ctrl_ufs_esi_mask_2_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int esi_mask_1 : 32;
    } reg;
}ufs_sys_ctrl_ufs_esi_mask_1_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int esi_mask_0 : 32;
    } reg;
}ufs_sys_ctrl_ufs_esi_mask_0_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int esi_pending_state_2 : 32;
    } reg;
}ufs_sys_ctrl_ufs_esi_pend_stat_2_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int esi_pending_state_1 : 32;
    } reg;
}ufs_sys_ctrl_ufs_esi_pend_stat_1_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int esi_pending_state_0 : 32;
    } reg;
}ufs_sys_ctrl_ufs_esi_pend_stat_0_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int gits_addr  : 32;
    } reg;
}ufs_sys_ctrl_ufs_esi_gits_addr_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int esi_deviceid                  :  8;
        unsigned int reserved_0                    :  8;
        unsigned int esi_gif_saccept_timeout_value : 16;
    } reg;
}ufs_sys_ctrl_ufs_esi_device_id_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int ate_apb0_if_sel        :  1;
        unsigned int ate_apb0_if_mode       :  2;
        unsigned int ate_rx1_reset          :  1;
        unsigned int ate_tx1_reset          :  1;
        unsigned int ate_tx0_reset          :  1;
        unsigned int ate_rx0_reset          :  1;
        unsigned int ate_fw_clk_ack         :  1;
        unsigned int ate_ref_range          :  4;
        unsigned int ate_ref_alt_clk_lp_sel :  1;
        unsigned int ate_ref_clk_en         :  1;
        unsigned int ate_ref_use_pad        :  1;
        unsigned int ate_pg_mode_en         :  1;
        unsigned int ate_enable             :  1;
        unsigned int reserved_0             :  3;
        unsigned int ate_freq_mon_en        :  1;
        unsigned int reserved_1             :  3;
        unsigned int pclk_freq              :  8;
    } reg;
}ufs_sys_ctrl_dwc_mphy_ate_ctrl_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int ate_fw_clk_req            :  1;
        unsigned int ate_dco_clkcal            :  1;
        unsigned int ref_dco_clkcal_freq_valid :  1;
        unsigned int tx_pwm_clk_freq_valid     :  1;
        unsigned int ref_dco_clkcal_freq       :  9;
        unsigned int reserved_0                :  3;
        unsigned int tx_pwm_clk_freq           :  9;
        unsigned int reserved_1                :  7;
    } reg;
}ufs_sys_ctrl_dwc_mphy_ate_stat_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int ate_tx_main_reset_0           :  1;
        unsigned int ate_tx_main_reset_1           :  1;
        unsigned int ate_tx_reset_0                :  1;
        unsigned int ate_tx_reset_1                :  1;
        unsigned int ate_rx_main_reset_0           :  1;
        unsigned int ate_rx_main_reset_1           :  1;
        unsigned int ate_rx_reset_0                :  1;
        unsigned int ate_rx_reset_1                :  1;
        unsigned int ate_tx0_flyover_en            :  1;
        unsigned int ate_tx1_flyover_en            :  1;
        unsigned int ate_rx0_flyover_en            :  1;
        unsigned int ate_rx1_flyover_en            :  1;
        unsigned int ate_phy_reset                 :  1;
        unsigned int ate_sram_bypass_mode          :  2;
        unsigned int ate_sram_bootload_bypass_mode :  2;
        unsigned int ate_sram_ext_ld_done          :  1;
        unsigned int ate_pma_pwr_stable            :  1;
        unsigned int ate_ana_pwr_en                :  1;
        unsigned int reserved_0                    : 12;
    } reg;
}ufs_sys_ctrl_dwc_mphy_ate_ovrd_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int fpga_sfr_sel           :  1;
        unsigned int reserved_0             :  1;
        unsigned int fpga_ufs_vcc_2p5_en    :  1;
        unsigned int fpga_ufs_vccq_1p2_en   :  1;
        unsigned int fpga_block_sel_ovrd_en :  1;
        unsigned int fpga_block_sel         :  3;
        unsigned int reserved_1             : 24;
    } reg;
}ufs_sys_ctrl_ufs_fpga_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int reserved_0 : 32;
    } reg;
}ufs_sys_ctrl_ufs_ela_en_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int ufs_testpin_grp_sel :  8;
        unsigned int reserved_0          : 24;
    } reg;
}ufs_sys_ctrl_ufs_testpin_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int l15_state_fsm_seq_en   :  1;
        unsigned int ah8_state_fsm_seq_en   :  1;
        unsigned int lpm_state_fsm_seq_en   :  1;
        unsigned int l2_state_fsm_seq_en    :  1;
        unsigned int mrx0_state_fsm_seq_en  :  1;
        unsigned int mtx0_state_fsm_seq_en  :  1;
        unsigned int rxlss_state_fsm_seq_en :  1;
        unsigned int txlss_state_fsm_seq_en :  1;
        unsigned int reserved_0             : 24;
    } reg;
}ufs_sys_ctrl_ufs_state_seq_trace_en_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int l15_fsm_state_s0 :  7;
        unsigned int reserved_0       :  1;
        unsigned int l15_fsm_state_s1 :  7;
        unsigned int reserved_1       :  1;
        unsigned int l15_fsm_state_s2 :  7;
        unsigned int reserved_2       :  1;
        unsigned int l15_fsm_state_s3 :  7;
        unsigned int reserved_3       :  1;
    } reg;
}ufs_sys_ctrl_l15_state_0_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int l15_fsm_state_s4 :  7;
        unsigned int reserved_0       :  1;
        unsigned int l15_fsm_state_s5 :  7;
        unsigned int reserved_1       :  1;
        unsigned int l15_fsm_state_s6 :  7;
        unsigned int reserved_2       :  1;
        unsigned int l15_fsm_state_s7 :  7;
        unsigned int reserved_3       :  1;
    } reg;
}ufs_sys_ctrl_l15_state_1_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int ah8_fsm_state_s0 :  4;
        unsigned int ah8_fsm_state_s1 :  4;
        unsigned int ah8_fsm_state_s2 :  4;
        unsigned int ah8_fsm_state_s3 :  4;
        unsigned int ah8_fsm_state_s4 :  4;
        unsigned int ah8_fsm_state_s5 :  4;
        unsigned int ah8_fsm_state_s6 :  4;
        unsigned int ah8_fsm_state_s7 :  4;
    } reg;
}ufs_sys_ctrl_ah8_state_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int lpm_fsm_state_s0 :  3;
        unsigned int reserved_0       :  1;
        unsigned int lpm_fsm_state_s1 :  3;
        unsigned int reserved_1       :  1;
        unsigned int lpm_fsm_state_s2 :  3;
        unsigned int reserved_2       :  1;
        unsigned int lpm_fsm_state_s3 :  3;
        unsigned int reserved_3       :  1;
        unsigned int lpm_fsm_state_s4 :  3;
        unsigned int reserved_4       :  1;
        unsigned int lpm_fsm_state_s5 :  3;
        unsigned int reserved_5       :  1;
        unsigned int lpm_fsm_state_s6 :  3;
        unsigned int reserved_6       :  1;
        unsigned int lpm_fsm_state_s7 :  3;
        unsigned int reserved_7       :  1;
    } reg;
}ufs_sys_ctrl_lpm_state_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int l2_fsm_state_s0 :  3;
        unsigned int reserved_0      :  1;
        unsigned int l2_fsm_state_s1 :  3;
        unsigned int reserved_1      :  1;
        unsigned int l2_fsm_state_s2 :  3;
        unsigned int reserved_2      :  1;
        unsigned int l2_fsm_state_s3 :  3;
        unsigned int reserved_3      :  1;
        unsigned int l2_fsm_state_s4 :  3;
        unsigned int reserved_4      :  1;
        unsigned int l2_fsm_state_s5 :  3;
        unsigned int reserved_5      :  1;
        unsigned int l2_fsm_state_s6 :  3;
        unsigned int reserved_6      :  1;
        unsigned int l2_fsm_state_s7 :  3;
        unsigned int reserved_7      :  1;
    } reg;
}ufs_sys_ctrl_l2_state_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int mrx0_fsm_state_s0 :  4;
        unsigned int mrx0_fsm_state_s1 :  4;
        unsigned int mrx0_fsm_state_s2 :  4;
        unsigned int mrx0_fsm_state_s3 :  4;
        unsigned int mrx0_fsm_state_s4 :  4;
        unsigned int mrx0_fsm_state_s5 :  4;
        unsigned int mrx0_fsm_state_s6 :  4;
        unsigned int mrx0_fsm_state_s7 :  4;
    } reg;
}ufs_sys_ctrl_mrx0_state_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int mtx0_fsm_state_s0 :  4;
        unsigned int mtx0_fsm_state_s1 :  4;
        unsigned int mtx0_fsm_state_s2 :  4;
        unsigned int mtx0_fsm_state_s3 :  4;
        unsigned int mtx0_fsm_state_s4 :  4;
        unsigned int mtx0_fsm_state_s5 :  4;
        unsigned int mtx0_fsm_state_s6 :  4;
        unsigned int mtx0_fsm_state_s7 :  4;
    } reg;
}ufs_sys_ctrl_mtx0_state_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int rxlss_fsm_state_s0 :  8;
        unsigned int rxlss_fsm_state_s1 :  8;
        unsigned int rxlss_fsm_state_s2 :  8;
        unsigned int rxlss_fsm_state_s3 :  8;
    } reg;
}ufs_sys_ctrl_rxlss_state_0_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int rxlss_fsm_state_s4 :  8;
        unsigned int rxlss_fsm_state_s5 :  8;
        unsigned int rxlss_fsm_state_s6 :  8;
        unsigned int rxlss_fsm_state_s7 :  8;
    } reg;
}ufs_sys_ctrl_rxlss_state_1_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int txlss_fsm_state_s0 :  8;
        unsigned int txlss_fsm_state_s1 :  8;
        unsigned int txlss_fsm_state_s2 :  8;
        unsigned int txlss_fsm_state_s3 :  8;
    } reg;
}ufs_sys_ctrl_txlss_state_0_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int txlss_fsm_state_s4 :  8;
        unsigned int txlss_fsm_state_s5 :  8;
        unsigned int txlss_fsm_state_s6 :  8;
        unsigned int txlss_fsm_state_s7 :  8;
    } reg;
}ufs_sys_ctrl_txlss_state_1_t;


typedef union {
    unsigned int val;
    struct {
        unsigned int regfile_cgbypass :  1;
        unsigned int reserved_0       : 31;
    } reg;
}ufs_sys_ctrl_regfile_cgbypass_t;

#endif
