/*
 * bootinfo.h
 *
 * Copyright (C) 2011 Xiaomi Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef __ASMARM_BOOTINFO_H
#define __ASMARM_BOOTINFO_H

#define PD_REASON_MAX              66
#define PU_REASON_MAX              6

#define NORMAL_REASON              5
#define HRADWARE_REASON            21
#define AP_REASON                  14
#define SUBSYS_REASON              11
#define BOOTFAIL_REASON            15

typedef enum {
	AP_S_COLDBOOT = 0x0,
	bootloader,
	recovery,
	FASTBOOT_REBOOT,
	ADB_REBOOT,
	REBOOT_REASON_LABEL1 = 0x40,  /* hardware exception */
	AP_S_TSENSOR = REBOOT_REASON_LABEL1,
	AP_S_AWDT,
	LPIS_DS_DIS_TO,
	LPPLL_EN_TO,
	PWR_SQC_TO_UL2L,
	NPU_DSP_WD,
	NPU_M85_WD,
	ISP_WD,
	AUDIO_WD,
	PERI_WD3,
	PERI_WD2,
	PERI_WD1,
	LMS_WD,
	XRSE_WD,
	XCTRL_DDR_WD,
	XCTRL_CPU_WD,
	SENSORHUB_WD,
	LPCORE_WDT_RESET,
	XR_AP_PMU,
	AP_HW_WDT,
	XR_MULTI_HARDFAULT,
	REBOOT_REASON_LABEL2 = 0x60,  /* ap exception */
	XR_AP_PANIC = REBOOT_REASON_LABEL2,
	XR_AP_NOC,
	XR_AP_BL31_PANIC,
	XR_AP_RAS,
	XR_AP_COMBINATIONKEY,
	BORINGSSL_FAILED,
	APEXD_FAILED,
	BOOTSTRAP_APEXD_FAILED,
	VOLD_FAILED,
	LPCTRL_EXCEPTION,
	XCTRL_DDR_EXCEPTION,
	XCTRL_CPU_EXCEPTION,
	TEEOS_EXCEPTION,
	DM_VERITY_FAILED,
	REBOOT_REASON_LABEL3 = 0x80,  /* subsys exception */
	CP_S_MODEM = REBOOT_REASON_LABEL3,
	AUDIO_S_EXCEPTION,
	ISP_S_EXCEPTION,
	NPU_S_EXCEPTION,
	GPU_S_EXCEPTION,
	DPU_S_EXCEPTION,
	VPU_S_EXCEPTION,
	VDSP_S_EXCEPTION,
	SHUB_S_EXCEPTION,
	XRSE_EXCEPTION,
	WCN_S_EXCEPTION,
	REBOOT_REASON_LABEL4 = 0xa0,  /* bootup failed exception */
	XLOADER_S_WATCHDOG = REBOOT_REASON_LABEL4,
	XLOADER_S_PANIC,
	UEFI_S_WATCHDOG,
	UEFI_VERIFY_FAIL,
	UEFI_FLASHIMG_FAIL,
	UEFI_S_PANIC,
	UEFI_AVS_PANIC,
	XRSE_BOOT_EXCEPTION,
	XCTRL_CPU_BOOT_EXCEPTION,
	XCTRL_DDR_BOOT_EXCEPTION,
	ATF_BL2_BOOT_EXCEPTION,
	ATF_BL2_RUNTIME_EXCEPTION,
	ATF_BL31_BOOT_EXCEPTION,
	ATF_BL31_RUNTIME_EXCEPTION,
	MITEE_BOOT_EXCEPTION,
	REBOOT_REASON_LABEL5 = 0xd0,
} powerdown_reason_t;

typedef enum {
    MPMIC_POWERON_EVENT_NONE         = 0x0,   /* 无开机原因 */
    MPMIC_POWERON_EVENT_RTC          = 0x1,   /* RTC闹钟开机 */
    MPMIC_POWERON_EVENT_CHGDET       = 0x2,   /* USB插入开机 */
    MPMIC_POWERON_EVENT_PWR_KEY      = 0x4,   /* 按键开机 */
    MPMIC_POWERON_EVENT_PWR_KEY_FAST = 0x8,   /* 按键快速开机 */
    MPMIC_POWERON_EVENT_SMPL         = 0x10,  /* 低电后开机 */
} powerup_reason_t;

enum {
	PD_REASON_EVENT_COLDBOOT,            //normal
	PD_REASON_EVENT_BOOTLOADER,
	PD_REASON_EVENT_RECOVRTY,
	PD_REASON_EVENT_FASTBOOT,
	PD_REASON_EVENT_ADB,
	PD_REASON_EVENT_TSENSOR,             //hardware exception
	PD_REASON_EVENT_AWDT,
	PD_REASON_EVENT_LPIS_DIS,
	PD_REASON_EVENT_LPPLL,
	PD_REASON_EVENT_PWR_SQC,
	PD_REASON_EVENT_NPU_DSP_WD,
	PD_REASON_EVENT_NPU_M85_WD,
	PD_REASON_EVENT_ISP_WD,
	PD_REASON_EVENT_AUDIO_WD,
	PD_REASON_EVENT_PERI_WD3,
	PD_REASON_EVENT_PERI_WD2,
	PD_REASON_EVENT_PERI_WD1,
	PD_REASON_EVENT_LMS_WD,
	PD_REASON_EVENT_XRSE_WD,
	PD_REASON_EVENT_XCTRL_DDR_WD,
	PD_REASON_EVENT_XCTRL_CPU_WD,
	PD_REASON_EVENT_SENSORHUB_WD,
	PD_REASON_EVENT_LPCORE_WDT,
	PD_REASON_EVENT_XR_AP_PMU,
	PD_REASON_EVENT_AP_HW_WDT,
	PD_REASON_EVEN_XR_MULTI_HARDFAULT,
	PD_REASON_EVENT_XR_AP_PANIC,          //ap exception
	PD_REASON_EVENT_XR_AP_NOC,
	PD_REASON_EVENT_XR_AP_BL31_PANIC,
	PD_REASON_EVENT_XR_AP_RAS,
	PD_REASON_EVENT_XR_AP_COMB,
	PD_REASON_EVENT_BORINGSSL,
	PD_REASON_EVENT_APEXD,
	PD_REASON_EVENT_BOOTSTRAP_APEXD,
	PD_REASON_EVENT_VOLD,
	PD_REASON_EVENT_LPCTRL,
	PD_REASON_EVENT_XCTRL_DDR,
	PD_REASON_EVENT_XCTRL_CPU,
	PD_REASON_EVENT_TEEOS,
	PD_REASON_EVENT_DM_VERITY_FAILED,
	PD_REASON_EVENT_CP_S_MODEM,           //subsys exception
	PD_REASON_EVENT_AUDIO_EXCEPT,
	PD_REASON_EVENT_ISP_EXCEPT,
	PD_REASON_EVENT_NPU_EXCEPT,
	PD_REASON_EVENT_GPU_EXCEPT,
	PD_REASON_EVENT_DPU_EXCEPT,
	PD_REASON_EVENT_VPU_EXCEPT,
	PD_REASON_EVENT_VDSP_EXCEPT,
	PD_REASON_EVENT_SHUB_EXCEPT,
	PD_REASON_EVENT_XRSE_EXCEPT,
	PD_REASON_EVENT_WCN_S_EXCEPT,
	PD_REASON_EVENT_XLOADER_WDT,               //bootup failed exception
	PD_REASON_EVENT_XLOADER_PANIC,
	PD_REASON_EVENT_UEFI_WDT,
	PD_REASON_EVENT_UEFI_VERIFY_FAIL,
	PD_REASON_EVENT_UEFI_FLASHIMG_FAIL,
	PD_REASON_EVENT_UEFI_PANIC,
	PD_REASON_EVENT_UEFI_AVS_PANIC,
	PD_REASON_EVENT_XRSE_BOOT_EXCEPT,
	PD_REASON_EVENT_XCTRL_CPU_BOOT,
	PD_REASON_EVENT_XCTRL_DDR_BOOT,
	PD_REASON_EVENT_ATF_BL2_EXCEPT,
	PD_REASON_EVENT_ATF_BL2_RUNTIME,
	PD_REASON_EVENT_ATF_BL31_EXCEPT,
	PD_REASON_EVENT_ATF_BL31_RUNTIME,
	PD_REASON_EVENT_MITEE_EXCEPT
};

enum {
	PU_REASON_EVENT_NONE,
	PU_REASON_EVENT_RTC,
	PU_REASON_EVENT_CHGDET,
	PU_REASON_EVENT_PWR_KEY,
	PU_REASON_EVENT_PWR_KEY_FAST,
	PU_REASON_EVENT_SMPL
};

#endif