###############################################################################
# Support GKI mixed build
ifeq ($(DEVICE_MODULES_PATH),)
DEVICE_MODULES_PATH = $(srctree)
else
LINUXINCLUDE := $(DEVCIE_MODULES_INCLUDE) $(LINUXINCLUDE)
endif

# Necessary Check

ifneq ($(KERNEL_OUT),)
    ccflags-y += -imacros $(KERNEL_OUT)/include/generated/autoconf.h
endif

ifndef TOP
    TOP := $(srctree)/..
endif

ccflags-y += -I$(KERNEL_SRC)/../xring-modules/include/

# Force build fail on modpost warning
KBUILD_MODPOST_FAIL_ON_WARNINGS := y

###############################################################################
ccflags-y += -Werror
ccflags-y += -Wno-error=format
ccflags-y += -Wno-error=format-extra-args


###############################################################################
# Sources path
###############################################################################
ccflags-y += -I$(KERNEL_SRC)/drivers/connectivity/connadp/


###############################################################################
# Include Paths
###############################################################################
KO_CODE_PATH := $(if $(filter /%,$(src)),,$(srctree)/)$(src)
ccflags-y += -I$(KO_CODE_PATH)/include


###############################################################################
# Connadp Module
###############################################################################
MODULE_NAME := connadp
obj-m += $(MODULE_NAME).o

$(MODULE_NAME)-objs += adapter.o
$(MODULE_NAME)-objs += core.o
ifeq ($(CONFIG_CONN_PWR_DEBUG),y)
	$(MODULE_NAME)-objs += test.o
endif
