// SPDX-License-Identifier: GPL-2.0-only
/*
 * Copyright (c) 2023-2023 XRing Technologies Co., Ltd.
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

#include "dpu_hw_intr_ops.h"

#define GET_INTR_REG_OFFSET(id)    intr_map[id].reg_offset
#define GET_INTR_BIT_SHIFT(id)     intr_map[id].bit_shift

/* each intr pipe's status/enable/raw reg num */
#define INTR_PIPE_REG_NUM                   3

/* The address offset between status reg and mask reg */
#define INTR_STATUS_REG_OFFSET              0x24

#define ONL0_INTR_ENABLE_REG_OFFSET         0x0
#define ONL0_INTR_STATUS_REG_OFFSET         0x24
#define ONL0_INTR_INT_RAW_REG_OFFSET        0x48

#define CMB_INTR_ENABLE_REG_OFFSET          0xC
#define CMB_INTR_STATUS_REG_OFFSET          0x30
#define CMB_INTR_INTR_INT_RAW_REG_OFFSET    0x58

#define OFFL0_INTR_ENABLE_REG_OFFSET        0x18
#define OFFL0_INTR_STATUS_REG_OFFSET        0x3C
#define OFFL0_INTR_INTR_INT_RAW_REG_OFFSET  0x68

#define INTR_BIT_LENGTH            1
#define INTR_BIT_ENABLE            1

struct intr_offset_info {
	u32 status_off;
	u32 enable_off;
	u32 raw_intr_off;
	u32 reg_num;
};

struct dpu_intr_map intr_map[] = {
	{INTR_ONLINE0_FRM_TIMING_VSYNC,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_SHIFT,
		"onl0_vsync"},
	{INTR_ONLINE0_FRM_TIMING_EOF,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		ONL0_FRM_TIMING_EOF_INT_MSK_SHIFT,
		"onl0_eof"},
	{INTR_ONLINE0_FRM_TIMING_EOF_START,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		ONL0_FRM_TIMING_CFG_EOF_INT_MSK_SHIFT,
		"onl0_cfg_win_start"},
	{INTR_ONLINE0_FRM_TIMING_EOF_END,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(ONL0_FRM_TIMING_CFG_EOF_INT_MSK_SHIFT + 1),
		"onl0_cfg_win_end"},
	{INTR_ONLINE0_FRM_TIMING_LINE,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		ONL0_FRM_TIMING_CFG_LINE_INT_MSK_SHIFT,
		"onl0_frm_timing_line"},
	{INTR_ONLINE0_CFG_RDY,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		ONL0_CFG_RDY_CLR_INT_MSK_SHIFT,
		"onl0_cfg_rdy_clr"},
	{INTR_ONLINE0_WB0_DONE,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		ONL0_WB_DONE_INT_MSK_SHIFT,
		"onl0_wb0_done"},
	{INTR_ONLINE0_WB1_DONE,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(ONL0_WB_DONE_INT_MSK_SHIFT + 1),
		"onl0_wb1_done"},
	{INTR_ONLINE0_FRM_TIMING_UNDERFLOW,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		ONL0_FRM_TIMING_UNFLOW_INT_MSK_SHIFT,
		"onl0_underflow"},
	{INTR_ONLINE0_WB0_OVERFLOW,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		ONL0_WB_OVFLOW_INT_MSK_SHIFT,
		"onl0_wb0_overflow"},
	{INTR_ONLINE0_WB1_OVERFLOW,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(ONL0_WB_OVFLOW_INT_MSK_SHIFT + 1),
		"onl0_wb1_overflow"},
	{INTR_ONLINE0_CMDLIST_RCH0_CFG_DONE,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		ONL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT,
		"onl0_cmdlist_rch0_cfg_done"},
	{INTR_ONLINE0_CMDLIST_RCH1_CFG_DONE,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 1),
		"onl0_cmdlist_rch1_cfg_done"},
	{INTR_ONLINE0_CMDLIST_RCH2_CFG_DONE,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 2),
		"onl0_cmdlist_rch2_cfg_done"},
	{INTR_ONLINE0_CMDLIST_RCH3_CFG_DONE,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 3),
		"onl0_cmdlist_rch3_cfg_done"},
	{INTR_ONLINE0_CMDLIST_RCH4_CFG_DONE,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 4),
		"onl0_cmdlist_rch4_cfg_done"},
	{INTR_ONLINE0_CMDLIST_RCH5_CFG_DONE,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 5),
		"onl0_cmdlist_rch5_cfg_done"},
	{INTR_ONLINE0_CMDLIST_RCH6_CFG_DONE,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 6),
		"onl0_cmdlist_rch6_cfg_done"},
	{INTR_ONLINE0_CMDLIST_RCH7_CFG_DONE,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 7),
		"onl0_cmdlist_rch7_cfg_done"},
	{INTR_ONLINE0_CMDLIST_RCH8_CFG_DONE,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 8),
		"onl0_cmdlist_rch8_cfg_done"},
	{INTR_ONLINE0_CMDLIST_RCH9_CFG_DONE,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 9),
		"onl0_cmdlist_rch9_cfg_done"},
	{INTR_ONLINE0_CMDLIST_COMPOSER0_CFG_DONE,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 10),
		"onl0_cmdlist_cmps0_cfg_done"},
	{INTR_ONLINE0_CMDLIST_COMPOSER1_CFG_DONE,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 11),
		"onl0_cmdlist_cmps1_cfg_done"},
	{INTR_ONLINE0_CMDLIST_COMPOSER2_CFG_DONE,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 12),
		"onl0_cmdlist_cmps2_cfg_done"},
	{INTR_ONLINE0_ACAD_FRM_DONE,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		ONL0_ACAD_FRM_DONE_INT_MSK_SHIFT,
		"onl0_acad_frm_done"},
	{INTR_ONLINE0_DSC_WDMA0_FRM_DONE,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		ONL0_DSCW_FRM_DONE_INT_MSK_SHIFT,
		"onl0_dsc_wdma0_frm_done"},
	{INTR_ONLINE0_DSC_WDMA1_FRM_DONE,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(ONL0_DSCW_FRM_DONE_INT_MSK_SHIFT + 1),
		"onl0_dsc_wdma1_frm_done"},
	{INTR_ONLINE0_DSC_WDMA0_OVERFLOW,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		ONL0_DSCW_OVFLOW_INT_MSK_SHIFT,
		"onl0_dsc_wdma0_overflow"},
	{INTR_ONLINE0_DSC_WDMA1_OVERFLOW,
		ONL0_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(ONL0_DSCW_OVFLOW_INT_MSK_SHIFT + 1),
		"onl0_dsc_wdma1_overflow"},
	{INTR_ONLINE0_CMDLIST_RCH0_ENTER_PENDING,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT),
		"onl0_cmdlist_rch0_enter_pending"},
	{INTR_ONLINE0_CMDLIST_RCH1_ENTER_PENDING,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 1),
		"onl0_cmdlist_rch1_enter_pending"},
	{INTR_ONLINE0_CMDLIST_RCH2_ENTER_PENDING,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 2),
		"onl0_cmdlist_rch2_enter_pending"},
	{INTR_ONLINE0_CMDLIST_RCH3_ENTER_PENDING,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 3),
		"onl0_cmdlist_rch3_enter_pending"},
	{INTR_ONLINE0_CMDLIST_RCH4_ENTER_PENDING,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 4),
		"onl0_cmdlist_rch4_enter_pending"},
	{INTR_ONLINE0_CMDLIST_RCH5_ENTER_PENDING,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 5),
		"onl0_cmdlist_rch5_enter_pending"},
	{INTR_ONLINE0_CMDLIST_RCH6_ENTER_PENDING,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 6),
		"onl0_cmdlist_rch6_enter_pending"},
	{INTR_ONLINE0_CMDLIST_RCH7_ENTER_PENDING,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 7),
		"onl0_cmdlist_rch7_enter_pending"},
	{INTR_ONLINE0_CMDLIST_RCH8_ENTER_PENDING,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 8),
		"onl0_cmdlist_rch8_enter_pending"},
	{INTR_ONLINE0_CMDLIST_RCH9_ENTER_PENDING,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 9),
		"onl0_cmdlist_rch9_enter_pending"},
	{INTR_ONLINE0_CMDLIST_COMPOSER0_ENTER_PENDING,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 10),
		"onl0_cmdlist_cmps0_enter_pending"},
	{INTR_ONLINE0_CMDLIST_COMPOSER1_ENTER_PENDING,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 11),
		"onl0_cmdlist_cmps1_enter_pending"},
	{INTR_ONLINE0_CMDLIST_COMPOSER2_ENTER_PENDING,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 12),
		"onl0_cmdlist_cmps2_enter_pending"},
	{INTR_ONLINE0_PSLVERR,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		ONL0_ARB_DEC_PSLVERR_INT_MSK_SHIFT,
		"onl0_pslverr"},
	{INTR_ONLINE0_TMG_VIDEO_TE,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		ONL0_TMG_SKIP_VIDEO_TE_INIT_MSK_SHIFT,
		"onl0_tmg_video_te"},
	{INTR_ONLINE0_TMG_ACTIVE_POWER_DOWN,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		ONL0_TMG_PWDN_TRIG_INT_MSK_SHIFT,
		"onl0_tmg_power_down"},
	{INTR_ONLINE0_TMG_ULPS_EXIT,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		ONL0_TMG_ULPS_EXIT_REQ_INT_MSK_SHIFT,
		"onl0_tmg_ulps_exit"},
	{INTR_ONLINE0_TMG_ULPS_ENTRY,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		ONL0_TMG_ULPS_ENTRY_REQ_INT_MSK_SHIFT,
		"onl0_tmg_ulps_entry"},
	{INTR_ONLINE0_TMG_OTHER_PART_POWER_ON,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		ONL0_TMG_PARTITION_PWUP_TRIG_INT_MSK_SHIFT,
		"onl0_tmg_power_on"},
	{INTR_ONLINE0_TMG_HOF,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		ONL0_TMG_HOF_INT_MSK_SHIFT,
		"onl0_tmg_hof"},
	{INTR_ONLINE0_TMG_VACTIVE_START,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		ONL0_TMG_VACT_START_INT_MSK_SHIFT,
		"onl0_tmg_vstart"},
	{INTR_ONLINE0_DDR_DVFS_REQUEST,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		DFXCORE_INT_MSK_SHIFT,
		"onl0_ddr_dvfs_request"},
	{INTR_ONLINE0_DVFS_FAIL,
		ONL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		ONL0_DVFS_FAIL_INT_MSK_SHIFT,
		"onl0_dvfs_fail"},
	{INTR_ONLINE0_DMA_DBG_PART1_RDMA,
		ONL0_DMA_DBG_INT_MSK_OFFSET,
		ONL0_DMA_DBG_INT_MSK_SHIFT,
		"onl0_rdma_dbg_part1"},
	{INTR_ONLINE0_DMA_DBG_PART2_RDMA,
		ONL0_DMA_DBG_INT_MSK_OFFSET,
		(ONL0_DMA_DBG_INT_MSK_SHIFT + 1),
		"onl0_rdma_dbg_part2"},
	{INTR_ONLINE0_DMA_DBG_WDMA,
		ONL0_DMA_DBG_INT_MSK_OFFSET,
		(ONL0_DMA_DBG_INT_MSK_SHIFT + 2),
		"onl0_wdma_dbg"},
	{INTR_ONLINE0_CMDLIST_DBG,
		ONL0_DMA_DBG_INT_MSK_OFFSET,
		ONL0_CMDLIST_DBG_INT_MSK_SHIFT,
		"onl0_cmdlist_dbg"},
	{INTR_ONLINE0_MAX, 0, 0, " "},

	{INTR_COMBO_FRM_TIMING_VSYNC,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		CMB_FRM_TIMING_VSYNC_INT_MSK_SHIFT,
		"comb0 frm timing vsync"},
	{INTR_COMBO_FRM_TIMING_EOF,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		CMB_FRM_TIMING_EOF_INT_MSK_SHIFT,
		"comb0 frm timing eof"},
	{INTR_COMBO_FRM_TIMING_EOF_START,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		CMB_FRM_TIMING_CFG_EOF_INT_MSK_SHIFT,
		"comb0_cfg_win_start"},
	{INTR_COMBO_FRM_TIMING_EOF_END,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(CMB_FRM_TIMING_CFG_EOF_INT_MSK_SHIFT + 1),
		"comb0_cfg_win_end"},
	{INTR_COMBO_FRM_TIMING_LINE,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		CMB_FRM_TIMING_CFG_LINE_INT_MSK_SHIFT,
		"comb0_frm_timing_line"},
	{INTR_COMBO_CFG_RDY,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		CMB_CFG_RDY_CLR_INT_MSK_SHIFT,
		"comb0_cfg_rdy"},
	{INTR_COMBO_WB0_DONE,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		CMB_WB_FRM_DONE_INT_MSK_SHIFT,
		"comb0_wb0_done"},
	{INTR_COMBO_WB1_DONE,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(CMB_WB_FRM_DONE_INT_MSK_SHIFT + 1),
		"comb0_wb1_done"},
	{INTR_COMBO_FRM_TIMING_UNDERFLOW,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		CMB_FRM_TIMING_UNFLOW_INT_MSK_SHIFT,
		"comb0_underflow"},
	{INTR_COMBO_WB0_OVERFLOW,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		CMB_WB_OVFLOW_INT_MSK_SHIFT,
		"comb0_wb0_overflow"},
	{INTR_COMBO_WB1_OVERFLOW,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(CMB_WB_OVFLOW_INT_MSK_SHIFT + 1),
		"comb0_wb1_overflow"},
	{INTR_COMBO_CMDLIST_RCH0_CFG_DONE,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		CMB_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT,
		"comb0_cmdlist_rch0_cfg_done"},
	{INTR_COMBO_CMDLIST_RCH1_CFG_DONE,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 1),
		"comb0_cmdlist_rch1_cfg_done"},
	{INTR_COMBO_CMDLIST_RCH2_CFG_DONE,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 2),
		"comb0_cmdlist_rch2_cfg_done"},
	{INTR_COMBO_CMDLIST_RCH3_CFG_DONE,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 3),
		"comb0_cmdlist_rch3_cfg_done"},
	{INTR_COMBO_CMDLIST_RCH4_CFG_DONE,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 4),
		"comb0_cmdlist_rch4_cfg_done"},
	{INTR_COMBO_CMDLIST_RCH5_CFG_DONE,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 5),
		"comb0_cmdlist_rch5_cfg_done"},
	{INTR_COMBO_CMDLIST_RCH6_CFG_DONE,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 6),
		"comb0_cmdlist_rch6_cfg_done"},
	{INTR_COMBO_CMDLIST_RCH7_CFG_DONE,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 7),
		"comb0_cmdlist_rch7_cfg_done"},
	{INTR_COMBO_CMDLIST_RCH8_CFG_DONE,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 8),
		"comb0_cmdlist_rch8_cfg_done"},
	{INTR_COMBO_CMDLIST_RCH9_CFG_DONE,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 9),
		"comb0_cmdlist_rch9_cfg_done"},
	{INTR_COMBO_CMDLIST_COMPOSER0_CFG_DONE,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 10),
		"comb0_cmdlist_cmps0_cfg_done"},
	{INTR_COMBO_CMDLIST_COMPOSER1_CFG_DONE,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 11),
		"comb0_cmdlist_cmps1_cfg_done"},
	{INTR_COMBO_CMDLIST_COMPOSER2_CFG_DONE,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 12),
		"comb0_cmdlist_cmps2_cfg_done"},
	{INTR_COMBO_WB0_SLICE_DONE,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		CMB_WB_SLICE_DONE_INT_MSK_SHIFT,
		"comb0_wb0_slice_done"},
	{INTR_COMBO_WB1_SLICE_DONE,
		CMB_FRM_TIMING_VSYNC_INT_MSK_OFFSET,
		(CMB_WB_SLICE_DONE_INT_MSK_SHIFT + 1),
		"comb0_wb1_slice_done"},
	{INTR_COMBO_CMDLIST_RCH0_ENTER_PENDING,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT,
		"comb0_cmdlist_rch0_enter_pending"},
	{INTR_COMBO_CMDLIST_RCH1_ENTER_PENDING,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 1),
		"comb0_cmdlist_rch1_enter_pending"},
	{INTR_COMBO_CMDLIST_RCH2_ENTER_PENDING,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 2),
		"comb0_cmdlist_rch2_enter_pending"},
	{INTR_COMBO_CMDLIST_RCH3_ENTER_PENDING,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 3),
		"comb0_cmdlist_rch3_enter_pending"},
	{INTR_COMBO_CMDLIST_RCH4_ENTER_PENDING,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 4),
		"comb0_cmdlist_rch4_enter_pending"},
	{INTR_COMBO_CMDLIST_RCH5_ENTER_PENDING,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 5),
		"comb0_cmdlist_rch5_enter_pending"},
	{INTR_COMBO_CMDLIST_RCH6_ENTER_PENDING,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 6),
		"comb0_cmdlist_rch6_enter_pending"},
	{INTR_COMBO_CMDLIST_RCH7_ENTER_PENDING,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 7),
		"comb0_cmdlist_rch7_enter_pending"},
	{INTR_COMBO_CMDLIST_RCH8_ENTER_PENDING,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 8),
		"comb0_cmdlist_rch8_enter_pending"},
	{INTR_COMBO_CMDLIST_RCH9_ENTER_PENDING,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 9),
		"comb0_cmdlist_rch9_enter_pending"},
	{INTR_COMBO_CMDLIST_COMPOSER0_ENTER_PENDING,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 10),
		"comb0_cmdlist_cmps0_enter_pending"},
	{INTR_COMBO_CMDLIST_COMPOSER1_ENTER_PENDING,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 11),
		"comb0_cmdlist_cmps1_enter_pending"},
	{INTR_COMBO_CMDLIST_COMPOSER2_ENTER_PENDING,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 12),
		"comb0_cmdlist_cmps2_enter_pending"},
	{INTR_COMBO_PSLVERR,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		CMB_ARB_DEC_PSLVERR_INT_MSK_SHIFT,
		"comb0_pslverr"},
	{INTR_COMBO_TMG_VIDEO_TE,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		CMB_TMG_SKIP_VIDEO_TE_INT_MSK_SHIFT,
		"comb0_timing_video_te"},
	{INTR_COMBO_TMG_ACTIVE_POWER_DOWN,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		CMB_TMG_PWDN_TRIG_INT_MSK_SHIFT,
		"comb0_tmg_active_power_down"},
	{INTR_COMBO_TMG_ULPS_EXIT,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		CMB_TMG_ULPS_EXIT_REQ_INT_MSK_SHIFT,
		"comb0_tmg_ulps_exit"},
	{INTR_COMBO_TMG_ULPS_ENTRY,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		CMB_TMG_ULPS_ENTRY_REQ_INT_MSK_SHIFT,
		"comb0_tmg_ulps_exit"},
	{INTR_COMBO_TMG_OTHER_PART_POWER_ON,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		CMB_TMG_PARTITION_PWUP_TRIG_INT_MSK_SHIFT,
		"comb0_tmg_other_part_power_on"},
	{INTR_COMBO_TMG_HOF,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		CMB_TMG_HOF_INT_MSK_SHIFT,
		"comb0_tmg_hof"},
	{INTR_COMBO_TMG_VACTIVE_START,
		CMB_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		CMB_TMG_VACT_START_INT_MSK_SHIFT,
		"comb0_tmg_vstart"},
	{INTR_COMBO_DMA_DBG_PART1_RDMA,
		CMB_DMA_DBG_INT_MSK_OFFSET,
		CMB_DMA_DBG_INT_MSK_SHIFT,
		"comb0_rdma_dbg_part1"},
	{INTR_COMBO_DMA_DBG_PART2_RDMA,
		CMB_DMA_DBG_INT_MSK_OFFSET,
		(CMB_DMA_DBG_INT_MSK_SHIFT + 1),
		"comb0_rdma_dbg_part2"},
	{INTR_COMBO_DMA_DBG_WDMA,
		CMB_DMA_DBG_INT_MSK_OFFSET,
		(CMB_DMA_DBG_INT_MSK_SHIFT + 2),
		"comb0_wdma_dbg"},
	{INTR_COMBO_CMDLIST_DBG,
		CMB_DMA_DBG_INT_MSK_OFFSET,
		CMB_CMDLIST_DBG_INT_RAW_SHIFT,
		"comb0_cmdlist_dbg"},
	{INTR_COMBO_MAX, 0, 0, " "},

	{INTR_OFFLINE0_CFG_RDY,
		OFFL0_CFG_RDY_CLR_INT_MSK_OFFSET,
		OFFL0_CFG_RDY_CLR_INT_MSK_SHIFT,
		"offl0_cfg_rdy"},
	{INTR_OFFLINE0_WB0_DONE,
		OFFL0_CFG_RDY_CLR_INT_MSK_OFFSET,
		OFFL0_WB_FRM_DONE_INT_MSK_SHIFT,
		"offl0_wb0_done"},
	{INTR_OFFLINE0_WB1_DONE,
		OFFL0_CFG_RDY_CLR_INT_MSK_OFFSET,
		(OFFL0_WB_FRM_DONE_INT_MSK_SHIFT + 1),
		"off0_wb1_done"},
	{INTR_OFFLINE0_WB0_SLICE_DONE,
		OFFL0_CFG_RDY_CLR_INT_MSK_OFFSET,
		OFFL0_WB_SLICE_DONE_INT_MSK_SHIFT,
		"off0_wb0_slice_done"},
	{INTR_OFFLINE0_WB1_SLICE_DONE,
		OFFL0_CFG_RDY_CLR_INT_MSK_OFFSET,
		(OFFL0_WB_SLICE_DONE_INT_MSK_SHIFT),
		"off0_wb1_slice_done"},
	{INTR_OFFLINE0_CMDLIST_RCH0_CFG_DONE,
		OFFL0_CFG_RDY_CLR_INT_MSK_OFFSET,
		OFFL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT,
		"offl0_cmdlist_rch0_cfg_done"},
	{INTR_OFFLINE0_CMDLIST_RCH1_CFG_DONE,
		OFFL0_CFG_RDY_CLR_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 1),
		"offl0_cmdlist_rch1_cfg_done"},
	{INTR_OFFLINE0_CMDLIST_RCH2_CFG_DONE,
		OFFL0_CFG_RDY_CLR_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 2),
		"offl0_cmdlist_rch2_cfg_done"},
	{INTR_OFFLINE0_CMDLIST_RCH3_CFG_DONE,
		OFFL0_CFG_RDY_CLR_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 3),
		"offl0_cmdlist_rch3_cfg_done"},
	{INTR_OFFLINE0_CMDLIST_RCH4_CFG_DONE,
		OFFL0_CFG_RDY_CLR_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 4),
		"offl0_cmdlist_rch4_cfg_done"},
	{INTR_OFFLINE0_CMDLIST_RCH5_CFG_DONE,
		OFFL0_CFG_RDY_CLR_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 5),
		"offl0_cmdlist_rch5_cfg_done"},
	{INTR_OFFLINE0_CMDLIST_RCH6_CFG_DONE,
		OFFL0_CFG_RDY_CLR_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 6),
		"offl0_cmdlist_rch6_cfg_done"},
	{INTR_OFFLINE0_CMDLIST_RCH7_CFG_DONE,
		OFFL0_CFG_RDY_CLR_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 7),
		"offl0_cmdlist_rch7_cfg_done"},
	{INTR_OFFLINE0_CMDLIST_RCH8_CFG_DONE,
		OFFL0_CFG_RDY_CLR_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 8),
		"offl0_cmdlist_rch8_cfg_done"},
	{INTR_OFFLINE0_CMDLIST_RCH9_CFG_DONE,
		OFFL0_CFG_RDY_CLR_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 9),
		"offl0_cmdlist_rch9_cfg_done"},
	{INTR_OFFLINE0_CMDLIST_COMPOSER0_CFG_DONE,
		OFFL0_CFG_RDY_CLR_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 10),
		"offl0_cmdlist_cmps0_cfg_done"},
	{INTR_OFFLINE0_CMDLIST_COMPOSER1_CFG_DONE,
		OFFL0_CFG_RDY_CLR_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 11),
		"offl0_cmdlist_cmps1_cfg_done"},
	{INTR_OFFLINE0_CMDLIST_COMPOSER2_CFG_DONE,
		OFFL0_CFG_RDY_CLR_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_FRM_CFG_DONE_INT_MSK_SHIFT + 12),
		"offl0_cmdlist_cmps2_cfg_done"},
	{INTR_OFFLINE0_CMDLIST_RCH0_ENTER_PENDING,
		OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT,
		"offl0_cmdlist_rch0_enter_pending"},
	{INTR_OFFLINE0_CMDLIST_RCH1_ENTER_PENDING,
		OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 1),
		"offl0_cmdlist_rch1_enter_pending"},
	{INTR_OFFLINE0_CMDLIST_RCH2_ENTER_PENDING,
		OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 2),
		"offl0_cmdlist_rch2_enter_pending"},
	{INTR_OFFLINE0_CMDLIST_RCH3_ENTER_PENDING,
		OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 3),
		"offl0_cmdlist_rch3_enter_pending"},
	{INTR_OFFLINE0_CMDLIST_RCH4_ENTER_PENDING,
		OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 4),
		"offl0_cmdlist_rch4_enter_pending"},
	{INTR_OFFLINE0_CMDLIST_RCH5_ENTER_PENDING,
		OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 5),
		"offl0_cmdlist_rch5_enter_pending"},
	{INTR_OFFLINE0_CMDLIST_RCH6_ENTER_PENDING,
		OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 6),
		"offl0_cmdlist_rch6_enter_pending"},
	{INTR_OFFLINE0_CMDLIST_RCH7_ENTER_PENDING,
		OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 7),
		"offl0_cmdlist_rch7_enter_pending"},
	{INTR_OFFLINE0_CMDLIST_RCH8_ENTER_PENDING,
		OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 8),
		"offl0_cmdlist_rch8_enter_pending"},
	{INTR_OFFLINE0_CMDLIST_RCH9_ENTER_PENDING,
		OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 9),
		"offl0_cmdlist_rch9_enter_pending"},
	{INTR_OFFLINE0_CMDLIST_COMPOSER0_ENTER_PENDING,
		OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 10),
		"offl0_cmdlist_cmps0_enter_pending"},
	{INTR_OFFLINE0_CMDLIST_COMPOSER1_ENTER_PENDING,
		OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 11),
		"offl0_cmdlist_cmps1_enter_pending"},
	{INTR_OFFLINE0_CMDLIST_COMPOSER2_ENTER_PENDING,
		OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		(OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_SHIFT + 12),
		"offl0_cmdlist_cmps2_enter_pending"},
	{INTR_OFFLINE0_PSLVERR,
		OFFL0_CMDLIST_CH_ENTER_PEND_INT_MSK_OFFSET,
		OFFL0_ARB_DEC_PSLVERR_INT_MSK_SHIFT,
		"offl0_pslverr"},
	{INTR_OFFLINE0_DMA_DBG_PART1_RDMA,
		OFFL0_NML_DMA_DBG_INT_MSK_OFFSET,
		OFFL0_NML_DMA_DBG_INT_MSK_SHIFT,
		"offl0_rdma_dbg_part1"},
	{INTR_OFFLINE0_DMA_DBG_PART2_RDMA,
		OFFL0_NML_DMA_DBG_INT_MSK_OFFSET,
		(OFFL0_NML_DMA_DBG_INT_MSK_SHIFT + 1),
		"offl0_rdma_dbg_part2"},
	{INTR_OFFLINE0_DMA_DBG_WDMA,
		OFFL0_NML_DMA_DBG_INT_MSK_OFFSET,
		(OFFL0_NML_DMA_DBG_INT_MSK_SHIFT + 2),
		"offl0_wdma_dbg"},
	{INTR_OFFLINE0_CMDLIST_DBG,
		OFFL0_NML_DMA_DBG_INT_MSK_OFFSET,
		OFFL0_NML_CMDLIST_DBG_INT_MSK_SHIFT,
		"offl0_cmdlist_dbg"},
	{INTR_OFFLINE0_MAX, 0, 0, " "},
};

void dpu_hw_intr_enable(struct dpu_hw_blk *hw,
		enum dpu_intr_id intr_id, bool enable)
{

	if (!hw) {
		DPU_ERROR("invalid parameter\n");
		return;
	}

	DPU_BIT_WRITE(hw, GET_INTR_REG_OFFSET(intr_id), enable,
		GET_INTR_BIT_SHIFT(intr_id), INTR_BIT_LENGTH, DIRECT_WRITE);
}

bool dpu_hw_intr_status_get(struct dpu_hw_blk *hw,
		enum dpu_intr_id intr_id)
{
	u32 offset;

	if (!hw) {
		DPU_ERROR("invalid parameter\n");
		return 0;
	}

	offset = GET_INTR_REG_OFFSET(intr_id) + INTR_STATUS_REG_OFFSET;

	return !!DPU_BIT_READ(hw, offset, GET_INTR_BIT_SHIFT(intr_id),
		INTR_BIT_LENGTH);
}

void dpu_hw_intr_status_clear(struct dpu_hw_blk *hw,
		enum dpu_intr_id intr_id)
{
	u32 offset;
	u32 value;

	if (!hw) {
		DPU_ERROR("invalid parameter\n");
		return;
	}

	offset = GET_INTR_REG_OFFSET(intr_id) + INTR_STATUS_REG_OFFSET;
	value = BIT(GET_INTR_BIT_SHIFT(intr_id));
	DPU_REG_WRITE_NO_LOG(hw, offset, value);
}

static void get_intr_pipe_offset(struct intr_offset_info *off_info,
		enum dpu_intr_type intr_type)
{
	switch(intr_type) {
	case DPU_INTR_ONLINE0:
		off_info->status_off = ONL0_INTR_STATUS_REG_OFFSET;
		off_info->enable_off = ONL0_INTR_ENABLE_REG_OFFSET;
		off_info->raw_intr_off = ONL0_INTR_INT_RAW_REG_OFFSET;
		off_info->reg_num = INTR_PIPE_REG_NUM;

		break;
	case DPU_INTR_ONLINE1:
		off_info->status_off = CMB_INTR_STATUS_REG_OFFSET;
		off_info->enable_off = CMB_INTR_ENABLE_REG_OFFSET;
		off_info->raw_intr_off = CMB_INTR_INTR_INT_RAW_REG_OFFSET;
		off_info->reg_num = INTR_PIPE_REG_NUM;

		break;
	case DPU_INTR_OFFLINE0:
		off_info->status_off = OFFL0_INTR_STATUS_REG_OFFSET;
		off_info->enable_off = OFFL0_INTR_ENABLE_REG_OFFSET;
		off_info->raw_intr_off = OFFL0_INTR_INTR_INT_RAW_REG_OFFSET;
		off_info->reg_num = INTR_PIPE_REG_NUM;

		break;
	default:
		DPU_ERROR("unknow intr_type %d\n", intr_type);
		break;
	}
}

void dpu_hw_intr_irq_status_get_all(struct dpu_hw_blk *hw, u32 intr_type,
		u32 *intr_reg_val, u32 intr_reg_num)
{
	struct intr_offset_info off_info = {0};
	u32 index;
	u32 reg_offset;
	int i;

	if (!hw || intr_type >= DPU_INTR_TYPE_MAX || !intr_reg_val || !intr_reg_num)
		return;

	get_intr_pipe_offset(&off_info, intr_type);

	if (off_info.status_off / 4 + off_info.reg_num >= intr_reg_num)
		return;

	for (i = 0; i < off_info.reg_num; i++) {
		index = off_info.status_off / 4 + i;
		reg_offset = off_info.status_off + i * 4;
		intr_reg_val[index] = DPU_REG_READ_NO_LOG(hw, reg_offset);

		/* clear the interrupt */
		DPU_REG_WRITE_NO_LOG(hw, reg_offset, intr_reg_val[index]);
	}
}

bool dpu_hw_intr_irq_status_get_from_cache(struct dpu_hw_blk *hw, u32 intr_id,
		u32 *intr_reg_val, u32 intr_reg_num)
{
	u32 index;
	u32 reg_offset;

	if (!hw || intr_id >= INTR_OFFLINE0_MAX || !intr_reg_val || !intr_reg_num)
		return false;

	reg_offset = GET_INTR_REG_OFFSET(intr_id) + INTR_STATUS_REG_OFFSET;
	index = reg_offset / 4;

	if (index >= intr_reg_num)
		return false;

	return !!(intr_reg_val[index] & BIT(GET_INTR_BIT_SHIFT(intr_id)));
}

void dpu_hw_intr_irq_status_dump(struct dpu_hw_blk *hw)
{
	if (!hw) {
		DPU_ERROR("invalid parameter\n");
		return;
	}

	DPU_INFO("0x48: %#x, 0x4c: %#x, 0x50: %#x\n",
			DPU_REG_READ(hw, ONL0_FRM_TIMING_VSYNC_INT_RAW_OFFSET),
			DPU_REG_READ(hw, ONL0_CMDLIST_CH_ENTER_PEND_INT_RAW_OFFSET),
			DPU_REG_READ(hw, ONL0_DMA_DBG_INT_RAW_OFFSET));
}

u32 dpu_hw_intr_pslverr_dump(struct dpu_hw_blk *hw, u32 intr_type)
{
	u32 offset = ONL0_ARB_DEC_PADDR_OFFSET;

	if (!hw) {
		DPU_ERROR("invalid parameter\n");
		return 0;
	}

	if (intr_type == DPU_INTR_ONLINE0)
		offset = ONL0_ARB_DEC_PADDR_OFFSET;
	else if (intr_type == DPU_INTR_ONLINE1)
		offset = CMB_ARB_DEC_PADDR_OFFSET;
	else if (intr_type == DPU_INTR_OFFLINE0)
		offset =  OFFL0_ARB_DEC_PADDR_OFFSET;

	return DPU_REG_READ(hw, offset);
}

