###############################################################################
# Necessary Check
export AUTOCONF_H=$(O)/include/generated/autoconf.h

ifeq ($(AUTOCONF_H),)
    $(error AUTOCONF_H is not defined)
endif

ccflags-y += -imacros $(AUTOCONF_H)

ifeq ($(TARGET_BUILD_VARIANT),$(filter $(TARGET_BUILD_VARIANT),userdebug user))
    ldflags-y += -s
endif

# Force build fail on modpost warning
KBUILD_MODPOST_FAIL_ON_WARNINGS := y
###############################################################################
ccflags-y += -I$(srctree)/include/
###############################################################################

ccflags-y += -Werror
ccflags-y += -Wno-error=format
ccflags-y += -Wno-error=format-extra-args
ccflags-y += -DCONFIG_TIMESYNC_EAP

###############################################################################

MODULE_NAME := timesync_eap
obj-m += $(MODULE_NAME).o

# Transfer local kernel config to compile option
EXTRA_CFLAGS:= \
    $(patsubst CONFIG_%, -DCONFIG_%=1, $(patsubst %=m,%,$(filter %=m,$(EXTRA_KCONFIG)))) \
    $(patsubst CONFIG_%, -DCONFIG_%=1, $(patsubst %=y,%,$(filter %=y,$(EXTRA_KCONFIG)))) \
    $(patsubst CONFIG_%, -DCONFIG_%=0, $(patsubst %=n,%,$(filter %=n,$(EXTRA_KCONFIG)))) \

$(info $$EXTRA_CFLAGS is [${EXTRA_CFLAGS}])

$(MODULE_NAME)-objs += timesync.o
$(MODULE_NAME)-objs += libtimesync/timesync_lib.o
