/*
 * Copyright (C) 2023-2023, X-Ring technologies Inc., All rights reserved.
 */
#ifndef __DDR_DVFS_VOTE_H__
#define __DDR_DVFS_VOTE_H__

#define VOTE_MAX_VALUE		0xFFFF

enum ddr_dvfs_hw_vote_ch {
	DDR_DVFS_HW_VOTE_TEMPERATURE = 0,
	DDR_DVFS_HW_VOTE_KERNEL = 1,
	DDR_DVFS_HW_VOTE_XCTRL_CPU = 2,
	DDR_DVFS_HW_VOTE_SCHEDGENIUS = 3,
	DDR_DVFS_HW_VOTE_PERFFLINGER = 4,
	DDR_DVFS_HW_VOTE_DPU = 5,
	DDR_DVFS_HW_VOTE_ISP = 6,
	DDR_DVFS_HW_VOTE_AUDIO = 7,
	DDR_DVFS_HW_VOTE_NPU_CORE = 8,
	DDR_DVFS_HW_VOTE_NPU_VDSP = 9,
	DDR_DVFS_HW_VOTE_MODEM = 10,
	DDR_DVFS_HW_VOTE_SENSORHUB = 11,
	DDR_DVFS_HW_VOTE_MAX = 12,
};

#endif
