obj-m := vsiv4l2.o
vsiv4l2-objs = vsi-v4l2.o vsi-v4l2daemon.o vsi-v4l2-config.o vsi-v4l2-dec.o vsi-v4l2-enc.o vsi-v4l2-params.o vsi-dma-contig.o vsi-v4l2-msgbuf.o
KDIR := /lib/modules/$(shell uname -r)/build
EXTRA_CFLAGS += -I$(PWD)/../include/ -DV4L2_DRIVER
default:
	$(MAKE) -C $(KDIR) M=$(PWD) modules CFLAGS_vsi-v4l2.o="-DUSE_X86_SYS"

clean::
	$(MAKE) -C $(KDIR) M=$(PWD) clean
	-rm -f .version





