xr_bootup_track_stage1-objs := bootup_track_stage1.o
xr_bootup_track_stage2-objs := bootup_track_stage2.o
obj-$(CONFIG_XRING_BOOTUP_TRACK_STAGE1) += xr_bootup_track_stage1.o
obj-$(CONFIG_XRING_BOOTUP_TRACK_STAGE2) += xr_bootup_track_stage2.o