/*
 * Copyright (C) 2024-2024, X-Ring technologies Inc., All rights reserved.
 */
#ifndef __TSENS_ID_H__
#define __TSENS_ID_H__


#define TBIT(n)	(1UL << (n))

#ifndef BIT
#define BIT(n) TBIT(n)
#endif

enum tsens_id {
	TSENS_ID_MIN			= -1,
	TSENS_ID_CPU_SUBCHIP		= 0,
	TSENS_ID_CPU_B_CORE8		= 1,
	TSENS_ID_CPU_B_CORE9		= 2,
	TSENS_ID_CPU_M_CORE5		= 3,
	TSENS_ID_CPU_LP_CORE3		= 4,
	TSENS_ID_L3_BUS4		= 5,
	TSENS_ID_TOP_BUS5		= 6,
	TSENS_ID_M2_BUS6		= 7,
	TSENS_ID_M1_BUS7		= 8,
	TSENS_ID_M1_BUS8		= 9,
	TSENS_ID_NPU			= 10,
	TSENS_ID_L3_BUS0		= 11,
	TSENS_ID_CPU_M_CORE6		= 12,
	TSENS_ID_NPU_BUS2		= 13,
	TSENS_ID_NPU_BUS3		= 14,
	TSENS_ID_NPU_BUS4		= 15,
	TSENS_ID_GPU_HUB2		= 16,
	TSENS_ID_PERI_SUBSYS		= 17,
	TSENS_ID_GPU_BUS1		= 18,
	TSENS_ID_GPU_BUS2		= 19,
	TSENS_ID_GPU_BUS3		= 20,
	TSENS_ID_GPU_BUS4		= 21,
	TSENS_ID_MAX
};

#define TSENS_SUBSYS_MIN		(0UL)
#define TSENS_SUBSYS_MAX		(TBIT(TSENS_ID_MAX))
#define TSENS_SUBSYS_DDR		(TBIT(TSENS_ID_MAX))
#define TSENS_SUBSYS_CPUB		(TBIT(TSENS_ID_CPU_B_CORE8) | TBIT(TSENS_ID_CPU_B_CORE9))
#define TSENS_SUBSYS_CPUM		(TBIT(TSENS_ID_CPU_M_CORE5) | TBIT(TSENS_ID_CPU_M_CORE6))
#define TSENS_SUBSYS_CPUMLP		(TBIT(TSENS_ID_CPU_LP_CORE3))
#define TSENS_SUBSYS_CPUL		(TBIT(TSENS_ID_CPU_SUBCHIP))
#define TSENS_SUBSYS_L3			(TBIT(TSENS_ID_L3_BUS4) | TBIT(TSENS_ID_L3_BUS0))
#define TSENS_SUBSYS_MEDIA		(TBIT(TSENS_ID_M2_BUS6) | TBIT(TSENS_ID_M1_BUS7) | TBIT(TSENS_ID_M1_BUS8))
#define TSENS_SUBSYS_MEDIA1		(TBIT(TSENS_ID_M1_BUS7) | TBIT(TSENS_ID_M1_BUS8))
#define TSENS_SUBSYS_MEDIA2		(TBIT(TSENS_ID_M2_BUS6))
#define TSENS_SUBSYS_NPU_CORE		(TBIT(TSENS_ID_NPU) | TBIT(TSENS_ID_NPU_BUS3) | TBIT(TSENS_ID_NPU_BUS4) | TBIT(TSENS_ID_NPU_BUS2))
#define TSENS_SUBSYS_GPU		(TBIT(TSENS_ID_GPU_HUB2) | TBIT(TSENS_ID_GPU_BUS1) 	\
					| TBIT(TSENS_ID_GPU_BUS2) | TBIT(TSENS_ID_GPU_BUS3) 	\
					| TBIT(TSENS_ID_GPU_BUS4))
#define TSENS_SUBSYS_PERI		(TBIT(TSENS_ID_PERI_SUBSYS))
#define TSENS_SUBSYS_LPIS		(TBIT(TSENS_ID_GPU_BUS4))
#endif
