##Common catapult directives from Document Version v1.5.3 
directive set /$block/SwRegister.sw_HW_ID:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_HW_Version:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_HW_BuildDate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_ext_abn_intr_src:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_ext_norm_intr_src:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_exe_cmdbuf_count:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_cmd_exe:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_cmd_exe_msb:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_TotalARLen:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_TotalR:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_TotalAR:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_TotalRLast:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_TotalAWLen:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_TotalW:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_TotalAW:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_TotalWLast:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_TotalB:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_ARVALID:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_ARREADY:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_RVALID:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_RREADY:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_AWVALID:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_AWREADY:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_WVALID:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_WREADY:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_BVALID:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_BREADY:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_HW_ApbArbiter:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_HW_InitMode:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_core_state:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_init_mode:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_work_state:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_arb_check_en:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_init_enable:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_clk_gate_disable:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_master_out_clk_gate_disable:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_core_clk_gate_disable:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_abort_mode:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_reset_core:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_reset_all:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_start_trigger:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_irq_arbrst:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_irq_jmp:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_irq_arberr:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_irq_abort:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_irq_cmderr:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_irq_timeout:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_irq_buserr:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_irq_endcmd:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_irq_arbrst_en:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_irq_jmp_en:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_irq_arberr_en:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_irq_abort_en:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_irq_cmderr_en:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_irq_timeout_en:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_irq_buserr_en:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_irq_endcmd_en:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_timeout_enable:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_timeout_cycles:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_cmdbuf_exe_addr:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_cmdbuf_exe_addr_msb:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_cmdbuf_exe_length:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_cmd_swap:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_data_swap:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_max_burst_len:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_id_rd:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_axi_id_wr:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_rdy_cmdbuf_count:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_ext_abn_intr_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_ext_norm_intr_gate:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_cmdbuf_exe_id:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_sram_timing_ctrl:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_arb_weight:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_arb_bw_overflow:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_arb_urgent:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_arb_enable:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_arb_time_window_exp:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_arb_winer_id:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_arb_cur_id:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_arb_grp_info:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_arb_state:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_arb_rst:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_arb_ack:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_arb_fe:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_arb_req:rsc -MAP_TO_MODULE {[DirectInput]}
directive set /$block/SwRegister.sw_arb_satisfaction:rsc -MAP_TO_MODULE {[DirectInput]}
