# SPDX-License-Identifier: GPL-2.0
LINUXINCLUDE += -I$(KERNEL_SRC)/../xring-modules/include/inc
LINUXINCLUDE += -I$(KERNEL_SRC)/../xring-modules/hwid/

obj-$(CONFIG_XM_POWER_SUPPLY)   += mca_business/
obj-$(or $(CONFIG_XM_POWER_SUPPLY), $(CONFIG_XM_POWER_SUPPLY_KUNIT))    += mca_common/
obj-$(or $(CONFIG_XM_POWER_SUPPLY), $(CONFIG_XM_POWER_SUPPLY_KUNIT)) += mca_platform/
obj-$(CONFIG_XM_POWER_SUPPLY)   += mca_protocol/
obj-$(or $(CONFIG_XM_POWER_SUPPLY), $(CONFIG_XM_POWER_SUPPLY_KUNIT))    += mca_strategy/
obj-$(CONFIG_XM_POWER_SUPPLY)   += mca_hardware_ic/
obj-$(CONFIG_XM_POWER_SUPPLY)   += mca_platform_sysfs/
obj-$(CONFIG_XM_POWER_SUPPLY)   += mca_hardware_monitor/
obj-$(CONFIG_XM_POWER_SUPPLY)   += mca_smart_charge/
obj-$(CONFIG_XM_POWER_SUPPLY)   += mca_shared_memory/
