# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_XM_POWER_SUPPLY)	+= mca_common.o
mca_common-objs := mca_voter.o
obj-$(or $(CONFIG_XM_POWER_SUPPLY), $(CONFIG_XM_POWER_SUPPLY_KUNIT))  += mca_sysfs.o
obj-$(or $(CONFIG_XM_POWER_SUPPLY), $(CONFIG_XM_POWER_SUPPLY_KUNIT))   += mca_event.o
obj-$(or $(CONFIG_XM_POWER_SUPPLY), $(CONFIG_XM_POWER_SUPPLY_KUNIT))   += mca_parse_dts.o
obj-$(CONFIG_XM_POWER_SUPPLY)     += mca_charge_interface.o
obj-$(CONFIG_XM_POWER_SUPPLY)     += mca_log.o
obj-$(CONFIG_XM_POWER_SUPPLY)     += mca_hwid.o
obj-$(CONFIG_MCA_SUPPORT_HBM_MODE)     += mca_xring_panel.o
obj-$(CONFIG_XM_POWER_SUPPLY)          += mca_charge_mievent.o
obj-$(CONFIG_XM_POWER_SUPPLY)          += mca_workqueue.o
