# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(srctree)/drivers/misc/hwid

obj-$(or $(CONFIG_XM_POWER_SUPPLY), $(CONFIG_XM_POWER_SUPPLY_KUNIT)) 	+= mca_strategy_fg_comp.o
mca_strategy_fg_comp-objs += mca_strategy_fg.o mca_soc_smooth.o mca_battery_shutdown.o mca_battery_full.o
obj-$(or $(CONFIG_XM_POWER_SUPPLY), $(CONFIG_XM_POWER_SUPPLY_KUNIT)) += mca_strategy_fg_class.o
obj-$(CONFIG_XM_POWER_SUPPLY) += mca_soc_limit.o

obj-$(CONFIG_XM_POWER_SUPPLY_KUNIT) += mca_strategy_fg_kunit.o
