/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2024, X-Ring technologies Inc., All rights reserved.
 */

#ifndef __XRING_EDR_MDR_H__
#define __XRING_EDR_MDR_H__

#include <dt-bindings/xring/platform-specific/common/mdr/include/mdr_pub.h>
#include <linux/wait.h>

#define MDR_ISP_EXP_TYPE_MAX                     63

#define MODID_ISP_FW_PANIC                       0x81fffd01
#define MODID_ISP_FW_WDT_HANG                    0x81fffd02
#define MODID_ISP_FW_TIMER_HANG                  0x81fffd03

#define MODID_ISP_MIPI_TIMEOUT_ERROR             0x81fffd04
#define MODID_ISP_MIPI_RX_ERROR                  0x81fffd05
#define MODID_ISP_MIPI_HSRX_TO_ERROR             0x81fffd06
#define MODID_ISP_MIPI_DESKEW_ERROR              0x81fffd07
#define MODID_ISP_MIPI_PHY01_ERROR               0x81fffd08
#define MODID_ISP_MIPI_PHY02_ERROR               0x81fffd09
#define MODID_ISP_MIPI_CSI2_ERROR                0x81fffd0a
#define MODID_ISP_MIPI_FRAME_ERROR               0x81fffd0b
#define MODID_ISP_MIPI_LINE_ERROR                0x81fffd0c
#define MODID_ISP_MIPI_SDI_HD_FIFO_ERROR         0x81fffd0d
#define MODID_ISP_MIPI_SDI_PLD_FIFO_ERROR        0x81fffd0e
#define MODID_ISP_MIPI_SDI_WC_ERROR              0x81fffd0f
#define MODID_ISP_MIPI_BUS_ERROR                 0x81fffd10
#define MODID_ISP_MIPI_AXI_ERROR                 0x81fffd11
#define MODID_ISP_MIPI_WR_ERROR                  0x81fffd12
#define MODID_ISP_MIPI_SDI_BUF_ERROR             0x81fffd13

#define MODID_ISP_FE_ROUTER_SDI0_VBUS_ERROR      0x81fffd14
#define MODID_ISP_FE_ROUTER_SDI1_VBUS_ERROR      0x81fffd15
#define MODID_ISP_FE_ROUTER_SDI2_VBUS_ERROR      0x81fffd16
#define MODID_ISP_FE_ROUTER_SDI0_BUF_FULL        0x81fffd17
#define MODID_ISP_FE_ROUTER_SDI1_BUF_FULL        0x81fffd18
#define MODID_ISP_FE_ROUTER_SDI2_BUF_FULL        0x81fffd19
#define MODID_ISP_FE_ROUTER_DATA_DMA_READ        0x81fffd1a
#define MODID_ISP_FE_ROUTER_DATA_DMA_WRITE       0x81fffd1b
#define MODID_ISP_FE0_CMD_DMA_ERROR              0x81fffd1c
#define MODID_ISP_FE0_DATA_DMA_WRITE_ERROR       0x81fffd1d
#define MODID_ISP_FE0_IP_ERROR                   0x81fffd1e
#define MODID_ISP_FE1_CMD_DMA_ERROR              0x81fffd1f
#define MODID_ISP_FE1_DATA_DMA_WRITE_ERROR       0x81fffd20
#define MODID_ISP_FE1_IP_ERROR                   0x81fffd21
#define MODID_ISP_FE2_CMD_DMA_ERROR              0x81fffd22
#define MODID_ISP_FE2_DATA_DMA_WRITE_ERROR       0x81fffd23
#define MODID_ISP_FE2_IP_ERROR                   0x81fffd24

#define MODID_ISP_BE_DATA_DMA_READ_ERROR         0x81fffd25
#define MODID_ISP_BE_DATA_DMA_WRITE_ERROR        0x81fffd26
#define MODID_ISP_BE_CMD_DMA_ERROR               0x81fffd27

#define MODID_ISP_CVE_IP_ERROR                   0x81fffd28
#define MODID_ISP_CVE_DATA_DMA_READ_ERROR        0x81fffd29
#define MODID_ISP_CVE_DATA_DMA_WRITE_ERROR       0x81fffd2a
#define MODID_ISP_CVE_ALGIN_MFNR_ERROR           0x81fffd2b
#define MODID_ISP_CVE_ALGIN1_CMD_DMA_ERROR       0x81fffd2c
#define MODID_ISP_CVE_MFNR_CMD_DMA_ERROR         0x81fffd2d

#define MODID_ISP_PE_DATA_DMA_READ_ERROR         0x81fffd2e
#define MODID_ISP_PE_DATA_DMA_WRITE_ERROR        0x81fffd2f
#define MODID_ISP_PE_CMD_DMA_ERROR               0x81fffd30
#define MODID_ISP_PE_WARPEIS_SYS_ERROR           0x81fffd31
#define MODID_ISP_PE_WAPRTNR_SYS_ERROR           0x81fffd32

#define MODID_ISP_I2C_ERROR                      0x81fffd33
#define MODID_ISP_I3C_ERROR                      0x81fffd34
#define MODID_ISP_OIS_CAM_PROBE_ERROR            0x81fffd35
#define MODID_ISP_OIS_CAM_INIT_ERROR             0x81fffd36
#define MODID_ISP_CIS_CAM_PROBE_ERROR            0x81fffd37
#define MODID_ISP_EEPROM_CAM_PROBE_ERROR         0x81fffd38

extern wait_queue_head_t wq;
extern struct edr_event new_event;

static struct mdr_exception_info_s g_isp_exception[56] = {
	[0] = {
		.e_modid            = (u32)MODID_ISP_FW_PANIC,
		.e_modid_end        = (u32)MODID_ISP_FW_PANIC,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_FW_PANIC,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP FW PANIC",
	},
	[1] = {
		.e_modid            = (u32)MODID_ISP_FW_WDT_HANG,
		.e_modid_end        = (u32)MODID_ISP_FW_WDT_HANG,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_FW_WDT_HANG,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP FW WDT HANG",
	},
	[2] = {
		.e_modid            = (u32)MODID_ISP_FW_TIMER_HANG,
		.e_modid_end        = (u32)MODID_ISP_FW_TIMER_HANG,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_FW_TIMER_HANG,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP FW TIMER HANG",
	},
	[3] = {
		.e_modid            = (u32)MODID_ISP_MIPI_TIMEOUT_ERROR,
		.e_modid_end        = (u32)MODID_ISP_MIPI_TIMEOUT_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_MIPI_TIMEOUT_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP MIPI TIMEOUT",
	},
	[4] = {
		.e_modid            = (u32)MODID_ISP_MIPI_RX_ERROR,
		.e_modid_end        = (u32)MODID_ISP_MIPI_RX_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_MIPI_RX_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP MIPI RX ERROR",
	},
	[5] = {
		.e_modid            = (u32)MODID_ISP_MIPI_HSRX_TO_ERROR,
		.e_modid_end        = (u32)MODID_ISP_MIPI_HSRX_TO_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_MIPI_HSRX_TO_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP MIPI HSRX TO ERROR",
	},
	[6] = {
		.e_modid            = (u32)MODID_ISP_MIPI_DESKEW_ERROR,
		.e_modid_end        = (u32)MODID_ISP_MIPI_DESKEW_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_MIPI_DESKEW_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP MIPI DESKEW ERROR",
	},
	[7] = {
		.e_modid            = (u32)MODID_ISP_MIPI_PHY01_ERROR,
		.e_modid_end        = (u32)MODID_ISP_MIPI_PHY01_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_MIPI_PHY01_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP MIPI PHY01 ERROR",
	},
	[8] = {
		.e_modid            = (u32)MODID_ISP_MIPI_PHY02_ERROR,
		.e_modid_end        = (u32)MODID_ISP_MIPI_PHY02_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_MIPI_PHY02_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP MIPI PHY02 ERROR",
	},
	[9] = {
		.e_modid            = (u32)MODID_ISP_MIPI_CSI2_ERROR,
		.e_modid_end        = (u32)MODID_ISP_MIPI_CSI2_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_MIPI_CSI2_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP MIPI CSI2 ERROR",
	},
	[10] = {
		.e_modid            = (u32)MODID_ISP_MIPI_FRAME_ERROR,
		.e_modid_end        = (u32)MODID_ISP_MIPI_FRAME_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_MIPI_FRAME_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP MIPI FRAME ERROR",
	},
	[11] = {
		.e_modid            = (u32)MODID_ISP_MIPI_LINE_ERROR,
		.e_modid_end        = (u32)MODID_ISP_MIPI_LINE_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_MIPI_LINE_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP MIPI LINE ERROR",
	},
	[12] = {
		.e_modid            = (u32)MODID_ISP_MIPI_SDI_HD_FIFO_ERROR,
		.e_modid_end        = (u32)MODID_ISP_MIPI_SDI_HD_FIFO_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_MIPI_SDI_HD_FIFO_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP MIPI SDI HD FIFO ERROR",
	},
	[13] = {
		.e_modid            = (u32)MODID_ISP_MIPI_SDI_PLD_FIFO_ERROR,
		.e_modid_end        = (u32)MODID_ISP_MIPI_SDI_PLD_FIFO_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_MIPI_SDI_PLD_FIFO_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP MIPI SDI PLD FIFO ERROR",
	},
	[14] = {
		.e_modid            = (u32)MODID_ISP_MIPI_SDI_WC_ERROR,
		.e_modid_end        = (u32)MODID_ISP_MIPI_SDI_WC_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_MIPI_SDI_WC_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP MIPI SDI WC ERROR",
	},
	[15] = {
		.e_modid            = (u32)MODID_ISP_MIPI_BUS_ERROR,
		.e_modid_end        = (u32)MODID_ISP_MIPI_BUS_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_MIPI_BUS_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP MIPI BUS ERROR",
	},
	[16] = {
		.e_modid            = (u32)MODID_ISP_MIPI_AXI_ERROR,
		.e_modid_end        = (u32)MODID_ISP_MIPI_AXI_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_MIPI_AXI_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP MIPI AXI ERROR",
	},
	[17] = {
		.e_modid            = (u32)MODID_ISP_MIPI_WR_ERROR,
		.e_modid_end        = (u32)MODID_ISP_MIPI_WR_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_MIPI_WR_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP MIPI WR ERROR",
	},
	[18] = {
		.e_modid            = (u32)MODID_ISP_MIPI_SDI_BUF_ERROR,
		.e_modid_end        = (u32)MODID_ISP_MIPI_SDI_BUF_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_MIPI_SDI_BUF_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP MIPI SDI BUF ERROR",
	},
	[19] = {
		.e_modid            = (u32)MODID_ISP_FE_ROUTER_SDI0_VBUS_ERROR,
		.e_modid_end        = (u32)MODID_ISP_FE_ROUTER_SDI0_VBUS_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_FE_ROUTER_SDI0_VBUS_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP FE ROUTER SDI0 VBUS ERROR",
	},
	[20] = {
		.e_modid            = (u32)MODID_ISP_FE_ROUTER_SDI1_VBUS_ERROR,
		.e_modid_end        = (u32)MODID_ISP_FE_ROUTER_SDI1_VBUS_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_FE_ROUTER_SDI1_VBUS_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP ROUTER SDI1 VBUS ERROR",
	},
	[21] = {
		.e_modid            = (u32)MODID_ISP_FE_ROUTER_SDI2_VBUS_ERROR,
		.e_modid_end        = (u32)MODID_ISP_FE_ROUTER_SDI2_VBUS_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_FE_ROUTER_SDI2_VBUS_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP FE ROUTER SDI2 VBUS ERROR",
	},
	[22] = {
		.e_modid            = (u32)MODID_ISP_FE_ROUTER_SDI0_BUF_FULL,
		.e_modid_end        = (u32)MODID_ISP_FE_ROUTER_SDI0_BUF_FULL,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_FE_ROUTER_SDI0_BUF_FULL,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP FE ROUTER SDI0 BUF FULL",
	},
	[23] = {
		.e_modid            = (u32)MODID_ISP_FE_ROUTER_SDI1_BUF_FULL,
		.e_modid_end        = (u32)MODID_ISP_FE_ROUTER_SDI1_BUF_FULL,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_FE_ROUTER_SDI1_BUF_FULL,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP FE ROUTER SDI1 BUF FULL",
	},
	[24] = {
		.e_modid            = (u32)MODID_ISP_FE_ROUTER_SDI2_BUF_FULL,
		.e_modid_end        = (u32)MODID_ISP_FE_ROUTER_SDI2_BUF_FULL,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_FE_ROUTER_SDI2_BUF_FULL,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP FE ROUTER SDI2 BUF FULL",
	},
	[25] = {
		.e_modid            = (u32)MODID_ISP_FE_ROUTER_DATA_DMA_READ,
		.e_modid_end        = (u32)MODID_ISP_FE_ROUTER_DATA_DMA_READ,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_FE_ROUTER_DATA_DMA_READ,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP FE ROUTER DATA DMA READ ERROR",
	},
	[26] = {
		.e_modid            = (u32)MODID_ISP_FE_ROUTER_DATA_DMA_WRITE,
		.e_modid_end        = (u32)MODID_ISP_FE_ROUTER_DATA_DMA_WRITE,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_FE_ROUTER_DATA_DMA_WRITE,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP FE ROUTER DATA DMA WRITE ERROR",
	},
	[27] = {
		.e_modid            = (u32)MODID_ISP_FE0_CMD_DMA_ERROR,
		.e_modid_end        = (u32)MODID_ISP_FE0_CMD_DMA_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_FE0_CMD_DMA_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP FE0 CMD DMA ERROR",
	},
	[28] = {
		.e_modid            = (u32)MODID_ISP_FE0_DATA_DMA_WRITE_ERROR,
		.e_modid_end        = (u32)MODID_ISP_FE0_DATA_DMA_WRITE_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_FE0_DATA_DMA_WRITE_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP FE0 DATA DMA WRITE ERROR",
	},
	[29] = {
		.e_modid            = (u32)MODID_ISP_FE0_IP_ERROR,
		.e_modid_end        = (u32)MODID_ISP_FE0_IP_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_FE0_IP_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP FE0 IP ERROR",
	},
	[30] = {
		.e_modid            = (u32)MODID_ISP_FE1_CMD_DMA_ERROR,
		.e_modid_end        = (u32)MODID_ISP_FE1_CMD_DMA_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_FE1_CMD_DMA_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP FE1 CMD DMA ERROR",
	},
	[31] = {
		.e_modid            = (u32)MODID_ISP_FE1_DATA_DMA_WRITE_ERROR,
		.e_modid_end        = (u32)MODID_ISP_FE1_DATA_DMA_WRITE_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_FE1_DATA_DMA_WRITE_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP FE1 DATA DMA WRITE ERROR",
	},
	[32] = {
		.e_modid            = (u32)MODID_ISP_FE1_IP_ERROR,
		.e_modid_end        = (u32)MODID_ISP_FE1_IP_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_FE1_IP_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP FE1 IP ERROR",
	},
	[33] = {
		.e_modid            = (u32)MODID_ISP_FE2_CMD_DMA_ERROR,
		.e_modid_end        = (u32)MODID_ISP_FE2_CMD_DMA_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_FE2_CMD_DMA_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP FE2 CMD DMA ERROR",
	},
	[34] = {
		.e_modid            = (u32)MODID_ISP_FE2_DATA_DMA_WRITE_ERROR,
		.e_modid_end        = (u32)MODID_ISP_FE2_DATA_DMA_WRITE_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_FE2_DATA_DMA_WRITE_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP FE2 DATA DMA WRITE ERROR",
	},
	[35] = {
		.e_modid            = (u32)MODID_ISP_FE2_IP_ERROR,
		.e_modid_end        = (u32)MODID_ISP_FE2_IP_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_FE2_IP_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP FE2 IP ERROR",
	},
	[36] = {
		.e_modid            = (u32)MODID_ISP_BE_DATA_DMA_READ_ERROR,
		.e_modid_end        = (u32)MODID_ISP_BE_DATA_DMA_READ_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_BE_DATA_DMA_READ_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP BE DATA DMA READ ERROR",
	},
	[37] = {
		.e_modid            = (u32)MODID_ISP_BE_DATA_DMA_WRITE_ERROR,
		.e_modid_end        = (u32)MODID_ISP_BE_DATA_DMA_WRITE_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_BE_DATA_DMA_WRITE_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP BE DATA DMA WRITE ERROR",
	},
	[38] = {
		.e_modid            = (u32)MODID_ISP_BE_CMD_DMA_ERROR,
		.e_modid_end        = (u32)MODID_ISP_BE_CMD_DMA_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_BE_CMD_DMA_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP BE CMD DMA ERROR",
	},
	[39] = {
		.e_modid            = (u32)MODID_ISP_CVE_IP_ERROR,
		.e_modid_end        = (u32)MODID_ISP_CVE_IP_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_CVE_IP_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP CVE IP ERROR",
	},
	[40] = {
		.e_modid            = (u32)MODID_ISP_CVE_DATA_DMA_READ_ERROR,
		.e_modid_end        = (u32)MODID_ISP_CVE_DATA_DMA_READ_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_CVE_DATA_DMA_READ_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP CVE DATA DMA READ ERROR",
	},
	[41] = {
		.e_modid            = (u32)MODID_ISP_CVE_DATA_DMA_WRITE_ERROR,
		.e_modid_end        = (u32)MODID_ISP_CVE_DATA_DMA_WRITE_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_CVE_DATA_DMA_WRITE_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP CVE DATA DMA WRITE ERROR",
	},
	[42] = {
		.e_modid            = (u32)MODID_ISP_CVE_ALGIN_MFNR_ERROR,
		.e_modid_end        = (u32)MODID_ISP_CVE_ALGIN_MFNR_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_CVE_ALGIN_MFNR_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP CVE ALGIN MFNR ERROR",
	},
	[43] = {
		.e_modid            = (u32)MODID_ISP_CVE_ALGIN1_CMD_DMA_ERROR,
		.e_modid_end        = (u32)MODID_ISP_CVE_ALGIN1_CMD_DMA_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_CVE_ALGIN1_CMD_DMA_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP CVE ALGIN1 CMD DMA ERROR",
	},
	[44] = {
		.e_modid            = (u32)MODID_ISP_CVE_MFNR_CMD_DMA_ERROR,
		.e_modid_end        = (u32)MODID_ISP_CVE_MFNR_CMD_DMA_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_CVE_MFNR_CMD_DMA_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP CVE MFNR CMD DMA ERROR",
	},
	[45] = {
		.e_modid            = (u32)MODID_ISP_PE_DATA_DMA_READ_ERROR,
		.e_modid_end        = (u32)MODID_ISP_PE_DATA_DMA_READ_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_PE_DATA_DMA_READ_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP PE DATA DMA READ ERROR",
	},
	[46] = {
		.e_modid            = (u32)MODID_ISP_PE_DATA_DMA_WRITE_ERROR,
		.e_modid_end        = (u32)MODID_ISP_PE_DATA_DMA_WRITE_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_PE_DATA_DMA_WRITE_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP PE DATA DMA WRITE ERROR",
	},
	[47] = {
		.e_modid            = (u32)MODID_ISP_PE_CMD_DMA_ERROR,
		.e_modid_end        = (u32)MODID_ISP_PE_CMD_DMA_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_PE_CMD_DMA_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP PE CMD DMA ERROR",
	},
	[48] = {
		.e_modid            = (u32)MODID_ISP_PE_WARPEIS_SYS_ERROR,
		.e_modid_end        = (u32)MODID_ISP_PE_WARPEIS_SYS_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_PE_WARPEIS_SYS_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP PE WARPEIS SYS ERROR",
	},
	[49] = {
		.e_modid            = (u32)MODID_ISP_PE_WAPRTNR_SYS_ERROR,
		.e_modid_end        = (u32)MODID_ISP_PE_WAPRTNR_SYS_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_PE_WAPRTNR_SYS_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP PE WAPRTNR SYS ERROR",
	},
	[50] = {
		.e_modid            = (u32)MODID_ISP_I2C_ERROR,
		.e_modid_end        = (u32)MODID_ISP_I2C_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_I2C_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP I2C ERROR",
	},
	[51] = {
		.e_modid            = (u32)MODID_ISP_I3C_ERROR,
		.e_modid_end        = (u32)MODID_ISP_I3C_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_I3C_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP I3C ERROR",
	},
	[52] = {
		.e_modid            = (u32)MODID_ISP_OIS_CAM_PROBE_ERROR,
		.e_modid_end        = (u32)MODID_ISP_OIS_CAM_PROBE_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_OIS_CAM_PROBE_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP OIS CAM PROBE ERROR",
	},
	[53] = {
		.e_modid            = (u32)MODID_ISP_OIS_CAM_INIT_ERROR,
		.e_modid_end        = (u32)MODID_ISP_OIS_CAM_INIT_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_OIS_CAM_INIT_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP OIS CAM INIT ERROR",
	},
	[54] = {
		.e_modid            = (u32)MODID_ISP_CIS_CAM_PROBE_ERROR,
		.e_modid_end        = (u32)MODID_ISP_CIS_CAM_PROBE_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_CIS_CAM_PROBE_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP CIS CAM PROBE ERROR",
	},
	[55] = {
		.e_modid            = (u32)MODID_ISP_EEPROM_CAM_PROBE_ERROR,
		.e_modid_end        = (u32)MODID_ISP_EEPROM_CAM_PROBE_ERROR,
		.e_process_priority = MDR_OTHER,
		.e_reboot_priority  = MDR_REBOOT_NO,
		.e_notify_core_mask = MDR_ISP,
		.e_reset_core_mask  = MDR_ISP,
		.e_from_core        = MDR_ISP,
		.e_reentrant        = (u32)MDR_REENTRANT_DISALLOW,
		.e_exce_type        = ISP_S_EXCEPTION,
		.e_exce_subtype     = ISP_S_EEPROM_CAM_PROBE_ERROR,
		.e_upload_flag      = (u32)MDR_UPLOAD_YES,
		.e_from_module      = "ISP",
		.e_desc             = "ISP EEPROM CAM PROBE ERROR",
	},

};

int xrisp_mdr_exception_register(void);
int xrisp_mdr_exception_unregister(void);
int xrisp_exception_to_mdr(uint16_t type, uint16_t subtype);

#endif
