/* SPDX-License-Identifier: BSD-3-Clause-Clear
 *
 * Copyright (c) 2022, MediaTek Inc.
 */

#ifndef __MTK_DPMAIF_DRV_T800_H__
#define __MTK_DPMAIF_DRV_T800_H__

#define DPMAIF_DEV_PD_BASE		(0x1022D000)
#define DPMAIF_DEV_AO_BASE		(0x10011000)

#define DPMAIF_PD_BASE			DPMAIF_DEV_PD_BASE
#define DPMAIF_AO_BASE			DPMAIF_DEV_AO_BASE

#define BASE_NADDR_NRL2_DPMAIF_UL	((unsigned long)(DPMAIF_PD_BASE))
#define BASE_NADDR_NRL2_DPMAIF_DL	((unsigned long)(DPMAIF_PD_BASE + 0x100))
#define BASE_NADDR_NRL2_DPMAIF_AP_MISC	((unsigned long)(DPMAIF_PD_BASE + 0x400))
#define BASE_NADDR_NRL2_DPMAIF_PD_SRAM_UL	((unsigned long)(DPMAIF_PD_BASE + 0xD00))
#define BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL	((unsigned long)(DPMAIF_PD_BASE + 0xC00))
#define BASE_NADDR_NRL2_DPMAIF_DL_LRO_REMOVEAO_IDX	((unsigned long)(DPMAIF_PD_BASE + 0x900))
#define BASE_NADDR_NRL2_DPMAIF_MMW_HPC		((unsigned long)(DPMAIF_PD_BASE + 0x600))
#define BASE_NADDR_NRL2_DPMAIF_PD_SRAM_MISC2	((unsigned long)(DPMAIF_PD_BASE + 0xF00))
#define BASE_NADDR_NRL2_DPMAIF_AO_UL		((unsigned long)(DPMAIF_AO_BASE))
#define BASE_NADDR_NRL2_DPMAIF_AO_DL		((unsigned long)(DPMAIF_AO_BASE + 0x400))

/* dpmaif uplink part registers. */
#define NRL2_DPMAIF_UL_ADD_DESC		(BASE_NADDR_NRL2_DPMAIF_UL + 0x00)
#define NRL2_DPMAIF_UL_DBG_STA2		(BASE_NADDR_NRL2_DPMAIF_UL + 0x88)
#define NRL2_DPMAIF_UL_RESERVE_AO_RW	(BASE_NADDR_NRL2_DPMAIF_UL + 0xAC)
#define NRL2_DPMAIF_UL_ADD_DESC_CH0	(BASE_NADDR_NRL2_DPMAIF_UL + 0xB0)
#define NRL2_DPMAIF_UL_ADD_DESC_CH4	(BASE_NADDR_NRL2_DPMAIF_UL + 0xE0)

/* dpmaif downlink part registers. */
#define NRL2_DPMAIF_DL_BAT_INIT			(BASE_NADDR_NRL2_DPMAIF_DL + 0x00)
#define NRL2_DPMAIF_DL_BAT_INIT			(BASE_NADDR_NRL2_DPMAIF_DL + 0x00)
#define NRL2_DPMAIF_DL_BAT_ADD			(BASE_NADDR_NRL2_DPMAIF_DL + 0x04)
#define NRL2_DPMAIF_DL_BAT_INIT_CON0		(BASE_NADDR_NRL2_DPMAIF_DL + 0x08)
#define NRL2_DPMAIF_DL_BAT_INIT_CON1		(BASE_NADDR_NRL2_DPMAIF_DL + 0x0C)
#define NRL2_DPMAIF_DL_BAT_INIT_CON3		(BASE_NADDR_NRL2_DPMAIF_DL + 0x50)
#define NRL2_DPMAIF_DL_DBG_STA1			(BASE_NADDR_NRL2_DPMAIF_DL + 0xB4)

/* dpmaif ap misc part registers. */
#define NRL2_DPMAIF_AP_MISC_AP_L2TISAR0		(BASE_NADDR_NRL2_DPMAIF_AP_MISC + 0x00)
#define NRL2_DPMAIF_AP_MISC_APDL_L2TISAR0	(BASE_NADDR_NRL2_DPMAIF_AP_MISC + 0x50)
#define NRL2_DPMAIF_AP_MISC_AP_IP_BUSY		(BASE_NADDR_NRL2_DPMAIF_AP_MISC + 0x60)
#define NRL2_DPMAIF_AP_MISC_CG_EN		(BASE_NADDR_NRL2_DPMAIF_AP_MISC + 0x68)
#define NRL2_DPMAIF_AP_MISC_OVERWRITE_CFG	(BASE_NADDR_NRL2_DPMAIF_AP_MISC + 0x90)
#define NRL2_DPMAIF_AP_MISC_RSTR_CLR		(BASE_NADDR_NRL2_DPMAIF_AP_MISC + 0x94)

/* dpmaif uplink ao part registers. */
#define NRL2_DPMAIF_AO_UL_INIT_SET		(BASE_NADDR_NRL2_DPMAIF_AO_UL + 0x0)
#define NRL2_DPMAIF_AO_UL_CHNL_ARB0		(BASE_NADDR_NRL2_DPMAIF_AO_UL + 0x1C)
#define NRL2_DPMAIF_AO_UL_AP_L2TIMR0		(BASE_NADDR_NRL2_DPMAIF_AO_UL + 0x80)
#define NRL2_DPMAIF_AO_UL_AP_L2TIMCR0		(BASE_NADDR_NRL2_DPMAIF_AO_UL + 0x84)
#define NRL2_DPMAIF_AO_UL_AP_L2TIMSR0		(BASE_NADDR_NRL2_DPMAIF_AO_UL + 0x88)
#define NRL2_DPMAIF_AO_UL_AP_L1TIMR0		(BASE_NADDR_NRL2_DPMAIF_AO_UL + 0x8C)
#define NRL2_DPMAIF_AO_UL_APDL_L2TIMR0		(BASE_NADDR_NRL2_DPMAIF_AO_UL + 0x90)
#define NRL2_DPMAIF_AO_UL_APDL_L2TIMCR0		(BASE_NADDR_NRL2_DPMAIF_AO_UL + 0x94)
#define NRL2_DPMAIF_AO_UL_APDL_L2TIMSR0		(BASE_NADDR_NRL2_DPMAIF_AO_UL + 0x98)
#define NRL2_DPMAIF_AO_UL_AP_DL_UL_IP_BUSY_MASK	(BASE_NADDR_NRL2_DPMAIF_AO_UL + 0x9C)

/* dpmaif uplink pd sram part registers. */
#define NRL2_DPMAIF_AO_UL_CHNL0_CON0		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_UL + 0x10)
#define NRL2_DPMAIF_AO_UL_CHNL0_CON1		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_UL + 0x14)
#define NRL2_DPMAIF_AO_UL_CHNL0_CON2		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_UL + 0x18)
#define NRL2_DPMAIF_DLY_IRQ_TIMER3		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_UL + 0x1C)
#define NRL2_DPMAIF_DLY_IRQ_TIMER4		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_UL + 0x2C)
#define NRL2_DPMAIF_DLY_IRQ_TIMER5		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_UL + 0x3C)
#define NRL2_DPMAIF_DLY_IRQ_TIMER6		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_UL + 0x60)
#define NRL2_DPMAIF_DLY_IRQ_TIMER7		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_UL + 0x64)
#define NRL2_DPMAIF_AO_UL_CH0_STA		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_UL + 0xE0)

/* dpmaif downlink ao part registers. */
#define NRL2_DPMAIF_AO_DL_INIT_SET		(BASE_NADDR_NRL2_DPMAIF_AO_DL + 0x0)
#define NRL2_DPMAIF_AO_DL_LROPIT_INIT_CON5	(BASE_NADDR_NRL2_DPMAIF_AO_DL + 0x28)
#define NRL2_DPMAIF_AO_DL_LROPIT_TRIG_THRES	(BASE_NADDR_NRL2_DPMAIF_AO_DL + 0x34)

/* dpmaif downlink pd sram part registers. */
#define NRL2_DPMAIF_AO_DL_PKTINFO_CON0		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x0)
#define NRL2_DPMAIF_AO_DL_PKTINFO_CON1		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x4)
#define NRL2_DPMAIF_AO_DL_PKTINFO_CON2		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x8)
#define NRL2_DPMAIF_AO_DL_RDY_CHK_THRES		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0xC)
#define NRL2_DPMAIF_AO_DL_RDY_CHK_FRG_THRES	(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x10)
#define NRL2_DPMAIF_AO_DL_LRO_AGG_CFG		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x20)
#define NRL2_DPMAIF_AO_DL_LROPIT_TIMEOUT0	(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x24)
#define NRL2_DPMAIF_AO_DL_LROPIT_TIMEOUT1	(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x28)
#define NRL2_DPMAIF_AO_DL_HPC_CNTL		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x38)
#define NRL2_DPMAIF_AO_DL_PIT_SEQ_END		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x40)
#define NRL2_DPMAIF_AO_DL_DLY_IRQ_TIMER1	(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x58)
#define NRL2_DPMAIF_AO_DL_DLY_IRQ_TIMER2	(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x5C)
#define NRL2_DPMAIF_AO_DL_BAT_STA1		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0xD4)
#define NRL2_DPMAIF_AO_DL_BAT_STA2		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0xD8)
#define NRL2_DPMAIF_AO_DL_BAT_STA3		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0xDC)
#define NRL2_DPMAIF_AO_DL_PIT_STA2		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0xEC)
#define NRL2_DPMAIF_AO_DL_PIT_STA3		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x60)
#define NRL2_DPMAIF_AO_DL_FRGBAT_STA2		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0x78)
#define NRL2_DPMAIF_AO_DL_LRO_STA5		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0xA4)
#define NRL2_DPMAIF_AO_DL_LRO_STA6		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_DL + 0xA8)

/* dpmaif hpc part registers. */
#define NRL2_DPMAIF_HPC_SW_5TUPLE_TRIG		(BASE_NADDR_NRL2_DPMAIF_MMW_HPC + 0x030)
#define NRL2_DPMAIF_HPC_5TUPLE_STS		(BASE_NADDR_NRL2_DPMAIF_MMW_HPC + 0x034)
#define NRL2_DPMAIF_HPC_SW_ADD_RULE0		(BASE_NADDR_NRL2_DPMAIF_MMW_HPC + 0x060)
#define NRL2_DPMAIF_HPC_INTR_MASK		(BASE_NADDR_NRL2_DPMAIF_MMW_HPC + 0x0F4)

/* dpmaif LRO part registers. */
#define NRL2_DPMAIF_DL_LROPIT_INIT		(BASE_NADDR_NRL2_DPMAIF_DL_LRO_REMOVEAO_IDX + 0x0)
#define NRL2_DPMAIF_DL_LROPIT_ADD		(BASE_NADDR_NRL2_DPMAIF_DL_LRO_REMOVEAO_IDX + 0x10)
#define NRL2_DPMAIF_DL_LROPIT_INIT_CON0		(BASE_NADDR_NRL2_DPMAIF_DL_LRO_REMOVEAO_IDX + 0x14)
#define NRL2_DPMAIF_DL_LROPIT_INIT_CON1		(BASE_NADDR_NRL2_DPMAIF_DL_LRO_REMOVEAO_IDX + 0x18)
#define NRL2_DPMAIF_DL_LROPIT_INIT_CON2		(BASE_NADDR_NRL2_DPMAIF_DL_LRO_REMOVEAO_IDX + 0x1C)
#define NRL2_DPMAIF_DL_LROPIT_INIT_CON5		(BASE_NADDR_NRL2_DPMAIF_DL_LRO_REMOVEAO_IDX + 0x28)
#define NRL2_DPMAIF_DL_LROPIT_INIT_CON3		(BASE_NADDR_NRL2_DPMAIF_DL_LRO_REMOVEAO_IDX + 0x20)
#define NRL2_DPMAIF_DL_LROPIT_INIT_CON4		(BASE_NADDR_NRL2_DPMAIF_DL_LRO_REMOVEAO_IDX + 0x24)
#define NRL2_DPMAIF_DL_LROPIT_INIT_CON6		(BASE_NADDR_NRL2_DPMAIF_DL_LRO_REMOVEAO_IDX + 0x2C)

/* dpmaif pd sram misc2 part registers. */
#define NRL2_REG_TOE_HASH_EN		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_MISC2 + 0x0)
#define NRL2_REG_HASH_CFG_CON		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_MISC2 + 0x4)
#define NRL2_REG_HASH_SEC_KEY_0		(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_MISC2 + 0x8)
#define NRL2_REG_HPC_STATS_THRES	(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_MISC2 + 0x30)
#define NRL2_REG_HPC_STATS_TIMER_CFG	(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_MISC2 + 0x34)
#define NRL2_REG_HASH_SEC_KEY_UPD	(BASE_NADDR_NRL2_DPMAIF_PD_SRAM_MISC2 + 0X70)

/* dpmaif pd ul, ao ul config. */
#define DPMAIF_PD_UL_CHNL_ARB0		NRL2_DPMAIF_AO_UL_CHNL_ARB0
#define DPMAIF_PD_UL_CHNL0_CON0		NRL2_DPMAIF_AO_UL_CHNL0_CON0
#define DPMAIF_PD_UL_CHNL0_CON1		NRL2_DPMAIF_AO_UL_CHNL0_CON1
#define DPMAIF_PD_UL_CHNL0_CON2		NRL2_DPMAIF_AO_UL_CHNL0_CON2
#define DPMAIF_PD_UL_ADD_DESC_CH	NRL2_DPMAIF_UL_ADD_DESC_CH0
#define DPMAIF_PD_UL_DBG_STA2		NRL2_DPMAIF_UL_DBG_STA2

/* dpmaif pd dl config. */
#define DPMAIF_PD_DL_BAT_INIT		NRL2_DPMAIF_DL_BAT_INIT
#define DPMAIF_PD_DL_BAT_ADD		NRL2_DPMAIF_DL_BAT_ADD
#define DPMAIF_PD_DL_BAT_INIT_CON0	NRL2_DPMAIF_DL_BAT_INIT_CON0
#define DPMAIF_PD_DL_BAT_INIT_CON1	NRL2_DPMAIF_DL_BAT_INIT_CON1
#define DPMAIF_PD_DL_BAT_INIT_CON3	NRL2_DPMAIF_DL_BAT_INIT_CON3
#define DPMAIF_PD_DL_DBG_STA1		NRL2_DPMAIF_DL_DBG_STA1

/* dpmaif pd ap misc, ao ul misc config. */
#define DPMAIF_PD_AP_UL_L2TISAR0	NRL2_DPMAIF_AP_MISC_AP_L2TISAR0
#define DPMAIF_PD_AP_UL_L2TIMR0		NRL2_DPMAIF_AO_UL_AP_L2TIMR0
#define DPMAIF_PD_AP_UL_L2TICR0		NRL2_DPMAIF_AO_UL_AP_L2TIMCR0
#define DPMAIF_PD_AP_UL_L2TISR0		NRL2_DPMAIF_AO_UL_AP_L2TIMSR0
#define DPMAIF_PD_AP_DL_L2TISAR0	NRL2_DPMAIF_AP_MISC_APDL_L2TISAR0
#define DPMAIF_PD_AP_DL_L2TIMR0		NRL2_DPMAIF_AO_UL_APDL_L2TIMR0
#define DPMAIF_PD_AP_DL_L2TICR0		NRL2_DPMAIF_AO_UL_APDL_L2TIMCR0
#define DPMAIF_PD_AP_DL_L2TISR0		NRL2_DPMAIF_AO_UL_APDL_L2TIMSR0
#define DPMAIF_PD_AP_IP_BUSY		NRL2_DPMAIF_AP_MISC_AP_IP_BUSY
#define DPMAIF_PD_AP_DLUL_IP_BUSY_MASK	NRL2_DPMAIF_AO_UL_AP_DL_UL_IP_BUSY_MASK

/* dpmaif ao dl config. */
#define DPMAIF_AO_DL_PKTINFO_CONO	NRL2_DPMAIF_AO_DL_PKTINFO_CON0
#define DPMAIF_AO_DL_PKTINFO_CON1	NRL2_DPMAIF_AO_DL_PKTINFO_CON1
#define DPMAIF_AO_DL_PKTINFO_CON2	NRL2_DPMAIF_AO_DL_PKTINFO_CON2
#define DPMAIF_AO_DL_RDY_CHK_THRES	NRL2_DPMAIF_AO_DL_RDY_CHK_THRES
#define DPMAIF_AO_DL_BAT_STA2		NRL2_DPMAIF_AO_DL_BAT_STA2
#define DPMAIF_AO_DL_BAT_STA3		NRL2_DPMAIF_AO_DL_BAT_STA3
#define DPMAIF_AO_DL_PIT_STA2		NRL2_DPMAIF_AO_DL_PIT_STA2
#define DPMAIF_AO_DL_PIT_STA3		NRL2_DPMAIF_AO_DL_PIT_STA3
#define DPMAIF_AO_DL_FRG_CHK_THRES	NRL2_DPMAIF_AO_DL_RDY_CHK_FRG_THRES
#define DPMAIF_AO_DL_FRG_STA2		NRL2_DPMAIF_AO_DL_FRGBAT_STA2

/* DPMAIF AO register */
#define DPMAIF_AP_INFRA_CG_SET		0x100010C0
#define DPMAIF_AP_INFRA_CG_CLR		0x100010C4
#define DPMAIF_AP_INFRA_CG_VAL		0x100010C8
#define DPMAIF_AP_INFRA_CG_BIT		BIT(26)
#define DPMAIF_AP_RGU_ASSERT		0x10001120
#define DPMAIF_AP_RGU_DEASSERT		0x10001124
#define DPMAIF_AP_RST_BIT			BIT(4)
#define DPMAIF_AP_AO_RGU_ASSERT		0x10001140
#define DPMAIF_AP_AO_RGU_DEASSERT	0x10001144
#define DPMAIF_AP_AO_RST_BIT		BIT(3)
#define DPMAIF_AP_INFRA_CLITCH_PORT	0x10001208
#define DPMAIF_AP_GLITCH_PROT_BIT	BIT(15)

/* hw configuration */
#define DPMAIF_ULQSAR_N(q_num)\
	((DPMAIF_PD_UL_CHNL0_CON0) + (0x10 * (q_num)))

#define DPMAIF_UL_DRBSIZE_ADDRH_N(q_num)\
	((DPMAIF_PD_UL_CHNL0_CON1) + (0x10 * (q_num)))

#define DPMAIF_UL_DRB_ADDRH_N(q_num)\
	((DPMAIF_PD_UL_CHNL0_CON2) + (0x10 * (q_num)))

#define DPMAIF_ULQ_STA0_N(q_num)\
	((NRL2_DPMAIF_AO_UL_CH0_STA) + (0x04 * (q_num)))

#define DPMAIF_ULQ_ADD_DESC_CH_N(q_num)\
	((DPMAIF_PD_UL_ADD_DESC_CH) + (0x04 * (q_num)))

#define DPMAIF_ULQS			0x1F

#define DPMAIF_UL_ADD_NOT_READY		BIT(31)
#define DPMAIF_UL_ADD_UPDATE		BIT(31)
#define DPMAIF_UL_ALL_QUE_ARB_EN	(DPMAIF_ULQS << 8)

#define DPMAIF_DL_ADD_UPDATE		BIT(31)
#define DPMAIF_DL_ADD_NOT_READY		BIT(31)
#define DPMAIF_DL_FRG_ADD_UPDATE	BIT(16)

#define DPMAIF_DL_BAT_INIT_ALLSET	BIT(0)
#define DPMAIF_DL_BAT_FRG_INIT		BIT(16)
#define DPMAIF_DL_BAT_INIT_EN		BIT(31)
#define DPMAIF_DL_BAT_INIT_NOT_READY	BIT(31)
#define DPMAIF_DL_BAT_INIT_ONLY_ENABLE_BIT	0

#define DPMAIF_DL_PIT_INIT_ALLSET	BIT(0)
#define DPMAIF_DL_PIT_INIT_EN		BIT(31)
#define DPMAIF_DL_PIT_INIT_NOT_READY	BIT(31)

#define DPMAIF_PKT_ALIGN64_MODE		0
#define DPMAIF_PKT_ALIGN128_MODE	1

#define DPMAIF_BAT_REMAIN_SZ_BASE	16
#define DPMAIF_BAT_BUFFER_SZ_BASE	128
#define DPMAIF_FRG_BUFFER_SZ_BASE	128

#define DPMAIF_PIT_SIZE_MSK		0x3FFFF

#define DPMAIF_BAT_EN_MSK		BIT(16)
#define DPMAIF_FRG_EN_MSK		BIT(28)
#define DPMAIF_BAT_SIZE_MSK		0xFFFF

#define DPMAIF_BAT_BID_MAXCNT_MSK	0xFFFF0000
#define DPMAIF_BAT_REMAIN_MINSZ_MSK	0x0000FF00
#define DPMAIF_PIT_CHK_NUM_MSK		0xFF000000
#define DPMAIF_BAT_BUF_SZ_MSK		0x0001FF00
#define DPMAIF_FRG_BUF_SZ_MSK		0x0001FF00
#define DPMAIF_BAT_RSV_LEN_MSK		0x000000FF
#define DPMAIF_PKT_ALIGN_MSK		(0x3 << 22)

#define DPMAIF_BAT_CHECK_THRES_MSK	(0x3F << 16)
#define DPMAIF_FRG_CHECK_THRES_MSK	0xFF
#define DPMAIF_PKT_ALIGN_EN		BIT(23)
#define DPMAIF_DRB_SIZE_MSK		0x0000FFFF

#define DPMAIF_DL_PIT_WRIDX_MSK		0x3FFFF
#define DPMAIF_DL_BAT_WRIDX_MSK		0x3FFFF
#define DPMAIF_DL_FRG_WRIDX_MSK		0x3FFFF

/* DPMAIF_PD_UL_DBG_STA2 */
#define DPMAIF_UL_IDLE_STS_MSK		BIT(11)
#define DPMAIF_UL_IDLE_STS		BIT(11)

/* DPMAIF_PD_DL_DBG_STA1 */
#define DPMAIF_DL_IDLE_STS		BIT(23)
#define DPMAIF_DL_PKT_CHECKSUM_EN	BIT(31)
#define DPMAIF_PORT_MODE_MSK		BIT(30)
#define DPMAIF_PORT_MODE_PCIE		BIT(30)

/* BASE_NADDR_NRL2_DPMAIF_WDMA */
#define DPMAIF_DL_BAT_CACHE_PRI		BIT(22)
#define DPMAIF_DL_BURST_PIT_EN		BIT(13)
#define DPMAIF_MEM_CLR_MASK		BIT(0)
#define DPMAIF_SRAM_SYNC_MASK		BIT(0)
#define DPMAIF_UL_INIT_DONE_MASK	BIT(0)
#define DPMAIF_DL_INIT_DONE_MASK	BIT(0)

#define DPMAIF_DL_PIT_SEQ_MSK		0xFF
#define DPMAIF_PCIE_MODE_SET_VALUE	0x55
#define DPMAIF_PCIE_MODE_SUSPEND_VALUE	0xEE
#define DPMAIF_PCIE_MODE_RESUME_VALUE	0xFF

#define DPMAIF_UDL_IP_BUSY_MSK		BIT(0)

#define DP_UL_INT_DONE_OFFSET		0
#define DP_UL_INT_EMPTY_OFFSET		5
#define DP_UL_INT_MD_NOTRDY_OFFSET	10
#define DP_UL_INT_PWR_NOTRDY_OFFSET	15
#define DP_UL_INT_LEN_ERR_OFFSET	20

/* Enable and mask/unmaks UL interrupt */
#define DPMAIF_UL_INT_QDONE_MSK			(DPMAIF_ULQS << DP_UL_INT_DONE_OFFSET)
#define DPMAIF_UL_TOP0_INT_MSK			BIT(9)

/* UL interrupt status */
#define DPMAIF_UL_INT_QDONE		(DPMAIF_ULQS << DP_UL_INT_DONE_OFFSET)

/* Enable and  Mask/unmask DL interrupt */
#define DPMAIF_DL_INT_BATCNT_LEN_ERR_MSK	BIT(2)
#define DPMAIF_DL_INT_FRG_LEN_ERR_MSK		BIT(7)
#define DPMAIF_DL_INT_DLQ0_QDONE_MSK		BIT(8)
#define DPMAIF_DL_INT_DLQ1_QDONE_MSK		BIT(9)
#define DPMAIF_DL_INT_DLQ0_PITCNT_LEN_ERR_MSK	BIT(10)
#define DPMAIF_DL_INT_DLQ1_PITCNT_LEN_ERR_MSK	BIT(11)
#define DPMAIF_DL_INT_Q2TOQ1_MSK		BIT(24)
#define DPMAIF_DL_INT_Q2APTOP_MSK		BIT(25)

/* DL interrupt status */
#define DPMAIF_DL_INT_DUMMY_STATUS		BIT(0)
#define DPMAIF_DL_INT_BATCNT_LEN_ERR		BIT(2)
#define DPMAIF_DL_INT_FRG_LEN_ERR		BIT(7)
#define DPMAIF_DL_INT_DLQ0_PITCNT_LEN_ERR	BIT(8)
#define DPMAIF_DL_INT_DLQ1_PITCNT_LEN_ERR	BIT(9)
#define DPMAIF_DL_INT_DLQ0_QDONE		BIT(13)
#define DPMAIF_DL_INT_DLQ1_QDONE		BIT(14)

/* DPMAIF LRO HW configure */
#define DPMAIF_HPC_LRO_PATH_DF			3
/* 0: HPC rules add by HW; 1: HPC rules add by Host */
#define DPMAIF_HPC_ADD_MODE_DF			0
#define DPMAIF_HPC_TOTAL_NUM			8
#define DPMAIF_HPC_MAX_TOTAL_NUM		8
#define DPMAIF_AGG_MAX_LEN_DF			65535
#define DPMAIF_AGG_TBL_ENT_NUM_DF		50
#define DPMAIF_HASH_PRIME_DF			13
#define DPMAIF_MID_TIMEOUT_THRES_DF		100
#define DPMAIF_LRO_TIMEOUT_THRES_DF		100
#define DPMAIF_LRO_PRS_THRES_DF			10
#define DPMAIF_LRO_HASH_BIT_CHOOSE_DF		0

#define DPMAIF_LROPIT_EN_MSK			0x100000
#define DPMAIF_LROPIT_CHAN_OFS			16
#define DPMAIF_ADD_LRO_PIT_CHAN_OFS		20

#define DPMAIF_DL_PIT_BYTE_SIZE		16
#define DPMAIF_DL_BAT_BYTE_SIZE		8
#define DPMAIF_DL_FRG_BYTE_SIZE		8
#define DPMAIF_UL_DRB_BYTE_SIZE		16

#define DPMAIF_UL_DRB_ENTRY_WORD	(DPMAIF_UL_DRB_BYTE_SIZE >> 2)
#define DPMAIF_DL_PIT_ENTRY_WORD	(DPMAIF_DL_PIT_BYTE_SIZE >> 2)
#define DPMAIF_DL_BAT_ENTRY_WORD	(DPMAIF_DL_BAT_BYTE_SIZE >> 2)

#define DPMAIF_HW_BAT_REMAIN		64
#define DPMAIF_HW_PKT_BIDCNT		1

#define DPMAIF_HW_CHK_BAT_NUM		62
#define DPMAIF_HW_CHK_FRG_NUM		3
#define DPMAIF_HW_CHK_PIT_NUM		(2 * DPMAIF_HW_CHK_BAT_NUM)

#define DPMAIF_DLQ_NUM			2
#define DPMAIF_ULQ_NUM			5
#define DPMAIF_PKT_BIDCNT		1

#define DPMAIF_TOEPLITZ_HASH_EN		1

/* word num */
#define DPMAIF_HASH_SEC_KEY_NUM		40
#define DPMAIF_HASH_DEFAULT_VALUE	0
#define DPMAIF_HASH_BIT_MASK_DF		0x7
#define DPMAIF_HASH_INDR_MASK_DF	0xF0

/* 10k */
#define DPMAIF_HPC_STATS_THRESHOLD	0x2800

/* 0x7A1- 1s: unit:512us */
#define DPMAIF_HPC_STATS_TIMER_CFG	0

#define DPMAIF_HASH_INDR_SIZE		(DPMAIF_HASH_BIT_MASK_DF + 1)
#define DPMAIF_HASH_INDR_MASK		0xFF00FFFF
#define DPMAIF_HASH_DEFAULT_V_MASK	0xFFFFFF00
#define DPMAIF_HASH_BIT_MASK		0xFFFFF0FF

/* dpmaif interrupt configuration */
#define DPMAIF_AP_UL_L2INTR_EN_MASK DPMAIF_UL_INT_QDONE_MSK

#define DPMAIF_AP_DL_L2INTR_EN_MASK\
	(DPMAIF_DL_INT_DLQ0_QDONE_MSK | DPMAIF_DL_INT_DLQ1_QDONE_MSK |\
	DPMAIF_DL_INT_DLQ0_PITCNT_LEN_ERR_MSK | DPMAIF_DL_INT_DLQ1_PITCNT_LEN_ERR_MSK |\
	DPMAIF_DL_INT_BATCNT_LEN_ERR_MSK | DPMAIF_DL_INT_FRG_LEN_ERR_MSK)

#define DPMAIF_AP_UDL_IP_BUSY_EN_MASK (DPMAIF_UDL_IP_BUSY_MSK)

/* dpmaif interrupt mask status by interrupt source */
#define DPMAIF_SRC0_DL_STATUS_MASK\
	(DPMAIF_DL_INT_DLQ0_QDONE | DPMAIF_DL_INT_DLQ0_PITCNT_LEN_ERR |\
	DPMAIF_DL_INT_BATCNT_LEN_ERR | DPMAIF_DL_INT_FRG_LEN_ERR | DPMAIF_DL_INT_DUMMY_STATUS)

#define DPMAIF_SRC1_DL_STATUS_MASK\
	(DPMAIF_DL_INT_DLQ1_QDONE | DPMAIF_DL_INT_DLQ1_PITCNT_LEN_ERR)

#endif
