// SPDX-License-Identifier: BSD-3-Clause-Clear
/*
 * Copyright (c) 2022, MediaTek Inc.
 */

#ifndef __MTK_PCI_DRV_T800_H__
#define __MTK_PCI_DRV_T800_H__

/* BROM SRAM original log region */
#define ATR_PCIE_BROM_SRAM_ORI_OFFSET			0
#define ATR_PCIE_BROM_SRAM_ORI_SIZE			0x1000
#define ATR_PCIE_BROM_SRAM_ORI_TRASL_ADDR		0x00101000
#define ATR_PCIE_BROM_SRAM_ORI_TABLE_NUM		1
#define PCIE_BROM_SRAM_READ_ORI_OFFSET			0x900

/* BROM SRAM copied log region */
#define ATR_PCIE_BROM_SRAM_OFFSET			0x1000
#define ATR_PCIE_BROM_SRAM_SIZE				0x1000
#define ATR_PCIE_BROM_SRAM_TRASL_ADDR			0x00124000
#define ATR_PCIE_BROM_SRAM_TABLE_NUM			2
#define PCIE_BROM_SRAM_READ_OFFSET			0xC00
#define PCIE_BROM_SRAM_LOG_SIZE				0x400

/* Preloader SRAM log region */
#define ATR_PCIE_PL_SRAM_OFFSET				0x10000
#define ATR_PCIE_PL_SRAM_SIZE				0x10000
#define ATR_PCIE_PL_SRAM_TRASL_ADDR			0x00120000
#define ATR_PCIE_PL_SRAM_TABLE_NUM			3
#define PCIE_PL_SRAM_READ_OFFSET			0x5000
#define PCIE_PL_SRAM_LOG_SIZE				0x5000

/* Preloader DRAM log region */
#define ATR_PCIE_PL_DRAM_OFFSET				0x40000
#define ATR_PCIE_PL_DRAM_SIZE				0x40000
#define ATR_PCIE_PL_DRAM_TRASL_ADDR			0x9C1C0000
#define ATR_PCIE_PL_DRAM_TABLE_NUM			4
#define PCIE_PL_DRAM_READ_OFFSET			0
#define PCIE_PL_DRAM_LOG_SIZE				0x40000

/* ATF DRAM log region */
#define ATR_PCIE_ATF_DRAM_OFFSET			0x80000
#define ATR_PCIE_ATF_DRAM_SIZE				0x80000
#define ATR_PCIE_ATF_DRAM_TRASL_ADDR			0x9DC00000
#define ATR_PCIE_ATF_DRAM_TABLE_NUM			5
#define PCIE_ATF_DRAM_READ_OFFSET			0
#define PCIE_ATF_DRAM_LOG_SIZE				0x40000

#endif
