# SPDX-License-Identifier: GPL-2.0

# O1 basic
dtb-y += soc/O1_basic.dtb

# ASIC Overlay Resurce
dtb-y += overlay/product/phone/phone_o2s/o2s_phone_overlay.dtbo
dtb-y += overlay/product/pad/pad_o80/o80_pad_overlay.dtbo
