obj-$(CONFIG_XRING_CLK) += xr-clk.o

#clk basic driver
xr-clk-y := xr-clk-fixed-rate.o \
		xr-clk-gate.o \
		xr-clk-scgate.o \
		xr-clk-divider.o \
		xr-clk-mux.o \
		xr-clk-pll.o \
		xr-clk-pmu.o \
		xr-clk-fast-dfs.o \
		clk.o \
		dvfs/xr-dvs-ctrl.o \
		xr-clk-dvfs.o \
		xr-dvfs-vote.o \
		dvfs/xr-common-hw-dvs.o

#clk common dependences
xr-clk-$(CONFIG_XRING_CLK_COMMON) += xr-clk-common.o
xr-clk-$(CONFIG_XRING_CLK_PM_MONITOR) += xr-clk-pm-monitor.o
#clk platform relative driver
xr-clk-$(CONFIG_XRING_CLK_O1) += platform/clk-o1.o


media-dvfs-objs += dvfs/xr-media-hw-dvs.o
obj-$(CONFIG_XRING_CLK_MEDIADVFS) += media-dvfs.o

peri-dvfs-objs += dvfs/xr-peri-hw-dvs.o
obj-$(CONFIG_XRING_CLK_PERIDVFS) += peri-dvfs.o

ccflags-y += -I$(KERNEL_SRC)/../xring-modules/drivers
ccflags-y += -I$(KERNEL_SRC)/../../platform/common/clk/include/O1
ccflags-y += -I$(KERNEL_SRC)/../../platform/common/pmu/include/O1
ccflags-y += -I$(KERNEL_SRC)/../xring-modules/drivers/xsp
