mali_kbase-y += \
    platform/$(MALI_PLATFORM_DIR)/mali_kbase_config_platform.o \
    platform/$(MALI_PLATFORM_DIR)/mali_kbase_xr_pm.o \
    platform/$(MALI_PLATFORM_DIR)/mali_kbase_gpu_memory_procfs.o \
    platform/$(MALI_PLATFORM_DIR)/mali_kbase_xr_query_info.o \
    platform/$(MALI_PLATFORM_DIR)/mali_kbase_xr_debugfs.o \
    platform/$(MALI_PLATFORM_DIR)/mali_kbase_xr_hw_access.o \
    platform/$(MALI_PLATFORM_DIR)/mali_kbase_xr_hotplug.o \
    platform/$(MALI_PLATFORM_DIR)/mali_kbase_xr_virtual_freq.o

mali_kbase-$(CONFIG_MALI_MIDGARD_DVFS) += \
    platform/$(MALI_PLATFORM_DIR)/mali_kbase_xr_dvfs.o

mali_kbase-$(CONFIG_MALI_XR_MDR) += \
    platform/$(MALI_PLATFORM_DIR)/mali_kbase_xr_mdr.o

mali_kbase-$(CONFIG_MALI_XR_GPU_PROTECTED_MEMORY) += \
    platform/$(MALI_PLATFORM_DIR)/mali_kbase_xr_protected_memory_allocator.o \
    platform/$(MALI_PLATFORM_DIR)/mali_kbase_xr_csf_protected_memory.o
