// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (C) 2022-2025, X-Ring technologies Inc., All rights reserved.
 */
#ifndef SYS_DOZE_HEADER_H
#define SYS_DOZE_HEADER_H

#if defined(__KERNEL__) && !defined(__NuttX__)
#include <dt-bindings/xring/platform-specific/sys_ctrl.h>
#include <dt-bindings/xring/platform-specific/dfx_memory_layout.h>
#include <dt-bindings/xring/platform-specific/lpctrl_dram_layout.h>
#else
#include "../../sys_ctrl.h"
#include "../../dfx_memory_layout.h"
#include "../../lpctrl_dram_layout.h"
#endif


#define SYS_CTRL_VOTER_BIT_AP         SYS_CTRL_NOR2DOZ_SOFT_VOTE_SEC_NOR2DOZ_SOFT_VOTE_SEC0_SHIFT
#define SYS_CTRL_VOTER_BIT_LPCORE     SYS_CTRL_NOR2DOZ_SOFT_VOTE_SEC_NOR2DOZ_SOFT_VOTE_SEC1_SHIFT
#define SYS_CTRL_VOTER_BIT_XCTRL_CPU  SYS_CTRL_NOR2DOZ_SOFT_VOTE_SEC_NOR2DOZ_SOFT_VOTE_SEC2_SHIFT


#define SYS_CTRL_VOTER_BIT_TEE_SPI0   SYS_CTRL_NOR2DOZ_SOFT_VOTE_SEC_NOR2DOZ_SOFT_VOTE_SEC3_SHIFT
#define SYS_CTRL_VOTER_BIT_TEE_SPI1   SYS_CTRL_NOR2DOZ_SOFT_VOTE_SEC_NOR2DOZ_SOFT_VOTE_SEC4_SHIFT
#define SYS_CTRL_VOTER_BIT_TEE_SPI2   SYS_CTRL_NOR2DOZ_SOFT_VOTE_SEC_NOR2DOZ_SOFT_VOTE_SEC5_SHIFT
#define SYS_CTRL_VOTER_BIT_RSV6       SYS_CTRL_NOR2DOZ_SOFT_VOTE_SEC_NOR2DOZ_SOFT_VOTE_SEC6_SHIFT
#define SYS_CTRL_VOTER_BIT_RSV7       SYS_CTRL_NOR2DOZ_SOFT_VOTE_SEC_NOR2DOZ_SOFT_VOTE_SEC7_SHIFT
#define SYS_CTRL_VOTER_BIT_RSV8       SYS_CTRL_NOR2DOZ_SOFT_VOTE_SEC_NOR2DOZ_SOFT_VOTE_SEC8_SHIFT
#define SYS_CTRL_VOTER_BIT_RSV9       SYS_CTRL_NOR2DOZ_SOFT_VOTE_SEC_NOR2DOZ_SOFT_VOTE_SEC9_SHIFT
#define SYS_CTRL_VOTER_BIT_RSV10      SYS_CTRL_NOR2DOZ_SOFT_VOTE_SEC_NOR2DOZ_SOFT_VOTE_SEC10_SHIFT
#define SYS_CTRL_VOTER_BIT_RSV11      SYS_CTRL_NOR2DOZ_SOFT_VOTE_SEC_NOR2DOZ_SOFT_VOTE_SEC11_SHIFT
#define SYS_CTRL_VOTER_BIT_RSV12      SYS_CTRL_NOR2DOZ_SOFT_VOTE_SEC_NOR2DOZ_SOFT_VOTE_SEC12_SHIFT
#define SYS_CTRL_VOTER_BIT_RSV13      SYS_CTRL_NOR2DOZ_SOFT_VOTE_SEC_NOR2DOZ_SOFT_VOTE_SEC13_SHIFT
#define SYS_CTRL_VOTER_BIT_RSV14      SYS_CTRL_NOR2DOZ_SOFT_VOTE_SEC_NOR2DOZ_SOFT_VOTE_SEC14_SHIFT
#define SYS_CTRL_VOTER_BIT_RSV15      SYS_CTRL_NOR2DOZ_SOFT_VOTE_SEC_NOR2DOZ_SOFT_VOTE_SEC15_SHIFT

#define DOZE_VOTE_SEC_SEL BIT(SYS_CTRL_VOTER_BIT_AP)

#define DOZE_SEC_REG  (SYS_CTRL_NOR2DOZ_SOFT_VOTE_SEC)
#define DOZE_USEC_REG (SYS_CTRL_NOR2DOZ_SOFT_VOTE_USEC)

#define STAT_DOZE1 0x11
#define STAT_DOZE2 0x12

#define SYS_PM_SHMEM_SIZE (LPCTRL_DDR_DOZE_SIZE)
#define DOZE_DDR_ADDR_AP (DFX_MEM_LPCTRL_ADDR + LPCTRL_DDR_DOZE_OFFSET)

#endif
